### ISSUE TITLE
Links on the Kubernetes page are outdated

### ISSUE THREAD

**Issue by Duologic** [google/jsonnet#1000]
There are a number of projects mentioned on the [kubernetes page](https://jsonnet.org/articles/kubernetes.html) but some of them are now deprecated or abandoned.

- kubecfg -> [archived](https://github.com/vmware-archive/kubecfg) on Github, forked to https://github.com/kubecfg/kubecfg
- ksonnet -> website [ssl expired](https://ksonnet.io/) (abandoned), [archived](https://github.com/ksonnet/ksonnet) on Github
- kpm -> [deprecated](https://github.com/coreos/kpm#-deprecation-warning-), last commit in 2017

I'd like to update the link to kubecfg, remove ksonnet/kpm and add the following:

- [jsonnet-libs/k8s](https://github.com/jsonnet-libs/k8s) project with most notably [k8s-libsonnet](https://jsonnet-libs.github.io/k8s-libsonnet/)  as the ksonnet-lib successor
- [Tanka](https://tanka.dev/), the spiritual successor of ksonnet, maintained by Grafana Labs

Additionally I'd suggest to remove references to Heptio:

- On Tools: heptio/vscode-jsonnet -> [archived](https://github.com/heptio/vscode-jsonnet) on Github (can be replaced with [grafana/vscode-jsonnet](https://github.com/grafana/vscode-jsonnet))
- On index page: Logo in footer -> website [ssl expired](https://tanzu.vmware.com/tanzu) (I see a commented out Grafana logo in the footer, perhaps surface that? Don't know why it is commented out @sparkprime?)

_Also the Kausal logo still resides in the footer, cc/ @tomwilkie, maybe that could be removed too?_

WDYT?

**Comment by sparkprime** [comment]
Congrats on getting issue 1000 :)

This all sounds good to me.  The commented out logos are the ones I never got permission for (i.e. never asked).  I guess I got distracted and forgot about it.

**Comment by sparkprime** [comment]
It might be worth checking on the slack chat to see if other projects should be mentioned.  The more links the better (as long as they work!)

**Comment by Duologic** [comment]
Great, I'll come up with a PR soonish.
