### ISSUE TITLE
Remove trailing empty newline from rendered multi-line strings

### ISSUE THREAD

**Issue by tgdfool2** [google/jsonnet#1018]
Hi All,

Is there an easy way to remove the trailing empty newline that is added in multi-line strings?

Given the following code:
```
local script = |||
  case "$ver" in
    %(current)s)
      echo "Same"
      exit 0
      ;;
    %(upgrade)s
    *)
      echo "Wrong"
      exit 2
      ;;
  esac
|||;

script % {
  current: '10',
  target: '20',
  upgrade: (if $.current != '20' then
  |||
    %(target)s)
        echo "Different"
        exit 1
        ;;
  ||| % { current: $.current, target: $.target } else ''),
}
```

It produces the following output:
```
case "$ver" in
  10)
    echo "Same"
    exit 0
    ;;
  20)
    echo "Different"
    exit 1
    ;;

  *)
    echo "Wrong"
    exit 2
    ;;
esac
```

I would like to get rid of the empty line that was added between the `20` and `*` cases. Is there an easy way to do this?

Thanks in advance for your help!

**Comment by sparkprime** [comment]
The best way right now is probably to write a function that strips is and call that around the |||.

Related FRs:

https://github.com/google/jsonnet/issues/289
https://github.com/google/jsonnet/issues/915

**Comment by tgdfool2** [comment]
Thanks for your answer and your hint :-). This one did the trick:
```
  upgrade: (if $.current != '2.0' then
    std.rstripChars(|||
      %(target)s)
          echo "Different"
          exit 1
          ;;
    ||| % { current: $.current, target: $.target }, '\n') else ''),
```

**Comment by vergenzt** [comment]
FYI for those following I implemented a "chomped multiline string" syntax in a PR at #1175. Would love some feedback on it and/or to get it merged! 🙂
