### ISSUE TITLE
Breakage of `import_callback` in 0.19.0

### ISSUE THREAD

**Issue by whitty** [google/jsonnet#1025]
I'm suddenly getting failures of this form since 0.19.0 came out

```
    model_string = _jsonnet.evaluate_file(file, import_callback=deps_import_cb)
RuntimeError: RUNTIME ERROR: couldn't open import "../../common_patches.libjsonnet": import_callback did not return (string, bytes)
	/path/to/base_patches.jsonnet:2:25-79	thunk <patches_common>
	/path/to/base_patches.jsonnet:99:26-40	object <anonymous>
	During manifestation	
```

I'm not sure what the correct fix is and what downstream issues that may cause.

I saw a single line fix to your unit-test so it looks like the API breakage is intentional - is there any documentation on what needs to change.

My thought was to open as binary

```
def try_path(directory, rel):
...
    with open(full_path, "rb") as f:
        return full_path, f.read()
```

You've done a version with `f.read().encode()` - which might be equivalent (but does re-encoding).  Both approaches

however this is then leading to parse errors on further imports, suggesting the resulting imports are not compatible.

```
RuntimeError: STATIC ERROR: /path/to/other_screen_patches.jsonnet:99:26-40 unexpected: end of file while parsing field definition
```

Looking at the patch (importbin) is there a reason the import mode for "jsonnet" changed (ie traditional `import`)?

**Comment by whitty** [comment]
OK - I eventually worked it through - not sure how to pin blame (except on non-emacs users ;-) )

The issue is in changing the way files are read changes the behaviour around EOF.

Specifically (some) of these imported files were written by an editor that doesn't ensure a newline is emitted before EOF.

It looks like the handling of imported files as strings has changed with that binary import change.  I'm not sure how intentional that behaviour change was.  Its certainly confusing to the user - here are the two errors I had - they only make sense now in retrospect:

```
RuntimeError: STATIC ERROR: /path/file:line:char unexpected: end of file while parsing field definition
RuntimeError: STATIC ERROR: /path/file:line:char expected a comma before next 
```

I was able to workaround this by adding a newline at end of line (presumably that's usually safe)

```
def try_path(directory, rel):
...
    with open(full_path) as f:
        return full_path, (f.read() + "\n").encode()
```

**Comment by whitty** [comment]
I'm also looking for a way to make my code compatible between both pre and post 0.19 versions - I don't think there is a version string to query.

**Comment by whitty** [comment]
For reference I've used a trick to detect which type of callback is needed

```
# Return True if new "bytes" import is needed (supported)
def check_import_version():
    def v0_19_callback(directory, rel):
        return "foo.jsonnet", "[]\n".encode()

    try:
        _jsonnet.evaluate_snippet("test.jsonnet", "{\nlocal foo = import 'foo.jsonnet',\n \n 'bar': foo\n }\n", import_callback=v0_19_callback)
        return True
    except:
        return False
```

Similarly you can reproduce my failure by using the following based on that snippet above

```
def no_nl_eof(directory, rel):
    return "foo.jsonnet", b"[]"

_jsonnet.evaluate_snippet("test.jsonnet", "{\nlocal foo = import 'foo.jsonnet',\n \n 'bar': foo\n }\n", import_callback=no_nl_eof)
```

**Comment by sparkprime** [comment]
The C APi changed but the python module was adjusted for that so the new
python module ought to be compatible with the last.

I think what's happening is there is an off-by-one error that's truncating
the last line of the file.  When the file ends with a \n that is not
noticeable but in your case it is.

**Comment by sparkprime** [comment]
Ok so the Python interface did change because it now expects you to return
bytes instead of a string, which is essentially the same as the change in
the C API.  I'm looking into making the Python API accept both so you won't
have to add the .encode() unless you actually want to support importbin for
binary files with \0 in the middle of them.  We should probably also add
the version string to the Python API but that's a separate issue.

**Comment by sparkprime** [comment]
Ok I updated jsonnet HEAD to make the python interface compatible -- if
you choose to use encode() then you won't be able to support 0.18.0
anymore, but if you don't use encode() then you will still be able to use
0.19.0 with the caveat that if you importbin something with a \0 in the
middle, it will be truncated

**Comment by sparkprime** [comment]
On second thoughts that approach is going to result in subtle divergences
in the behaviour of a jsonnet program depending on the version of the tool
using it... And that's much worse than requiring users of the Python
interface to insert an encode() call.  So I'm going to revert the behaviour
to always require bytes again in Python3.  However, I'll add a version code
so you can at least have a clean way of supporting both Jsonnet versions
with the same code.

**Comment by sparkprime** [comment]
Ok I'm about to release a new version that has a jsonnet.version field in
the Python bindings, as well as fixing the off-by-one error.  You can use
it as so:

import _jsonnet
import semver

import_returns_bytes = semver.compare(getattr(_jsonnet, 'version',
'v0.18.0')[1:], '0.18.0') > 0

def no_nl_eof(directory, rel):
    if import_returns_bytes:
        return "foo.jsonnet", b"42"
    else:
        return "foo.jsonnet", "42"

_jsonnet.evaluate_snippet("test.jsonnet", "{\nlocal foo = import
'foo.jsonnet',\n \n 'bar': foo\n }\n", import_callback=no_nl_eof)

**Comment by whitty** [comment]
Thanks for the quick response/fix - verified I no longer need the `+ "\n"` in 0.19.1
