### ISSUE TITLE
jsonnet unable to install on Mac M1 OS13.0.1

### ISSUE THREAD

**Issue by aliabbasjaffri** [google/jsonnet#1036]
I recently updated my OSX version to 13.0.1, and since then, i've been seeing this error on installation of jsonnet==0.19.1
```shell
  File "somefile.py", line 16, in 
    import _jsonnet as jsn
ImportError: dlopen(venv/lib/python3.9/site-packages/_jsonnet.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_jsonnet_destroy'
```

Python version: 3.9.6

**Comment by sparkprime** [comment]
How did you install it

**Comment by sparkprime** [comment]
That looks like what happens if you compile a library in C++ without `extern "C"` and try to use it from C... Excvept that we do have `extern "C"` in the `libjsonnet.cpp`

**Comment by aliabbasjaffri** [comment]
A bit hasty from my side. 😬
Deleting virtual env and reinstalling it fixed it!
