### ISSUE TITLE
How to import local variable from another jsonnet file

### ISSUE THREAD

**Issue by XiaosongWen** [google/jsonnet#1045]
Hi I have file `a.libsonnet`:
```
local panel = {
  new(...)::{... },
  createFromConfig(config)::
    this.new(),
};

local config = std.extVar('config');
panel.createFromConfig(config)
```
It seams if i only do in another file   `local panel = import 'a.libsonnet'` will also execute `panel.createFromConfig(config)`.
Is there a way I can only import `panel`?

**Comment by sparkprime** [comment]
Some options:

- Put panel in its own libsonnet file and import it from both
- return an object like { panel: ..., config: ... } and then when you import it as `foo`, you can do `foo.config` or `foo.panel` depending on what you want.

**Comment by XiaosongWen** [comment]
@sparkprime Thanks for your suggestion, this is what I finaly did.
