### ISSUE TITLE
Support native extensions

### ISSUE THREAD

**Issue by mikedanese** [google/jsonnet#108]
```
local nativeExtension = import src/jsonnet_regexp.h;
```

dlopens a libarary, calls jsonnet_regexp_registered_functions() (or some other well-known name), which returns a list of builtins to register and declare in the nativeExtension object.

**Comment by sparkprime** [comment]
That's very specific to the implementation language (C++).

But we could do is something like
std.builtin("foo")
and require the application code linking the jsonnet library to provide callbacks (just like we already allow import callbacks for doing I/O).

There is already an AST node for builtins, but it is only introduced during desugaring, it is not part of the actual syntax of the language.  We could make it part of the actual syntax and allow adding more builtins as well.

**Comment by sparkprime** [comment]
Example here: https://gist.github.com/sparkprime/5b2ab0a1b72beceab2cf5ea524db228c

**Comment by mikedanese** [comment]
This is awesome!

**Comment by vitiral** [comment]
I think this is related: https://groups.google.com/forum/#!topic/jsonnet/OhWV2RKlUFE
