### ISSUE TITLE
Publish binary releases

### ISSUE THREAD

**Issue by mikedanese** [google/jsonnet#109]
Preferably nightly and at every tag for mac osx and linux.

**Comment by sparkprime** [comment]
On debian/ubuntu I think having a ppa is an advantage, although pip install jsonnet works pretty well for the Python case.  I don't know much about mac.  Is homebrew sufficient?

**Comment by davidzchen** [comment]
For mac, I think homebrew is sufficient until somebody requests macports.

**Comment by mikedanese** [comment]
It looks easy to update: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/jsonnet.rb

Kubernetes distributes (mostly?) static binaries for various architecture {windows,darwin,linux}x{i386,x86_64} of kubectl from the github release page. https://github.com/kubernetes/kubernetes/releases

I like static binary distribution because it works when all else fails.

**Comment by huggsboson** [comment]
Is a new release of jsonnet on its way?  I'd love to be able to use named args and friends in some of our kube configs.

**Comment by sparkprime** [comment]
Alas I never got around to it before disappearing on Paternity leave.  I could do it from here though.

**Comment by timpeoples** [comment]
Yes, please do :D


*Timothy E. Peoplestim@timpeoples.com <tim@timpeoples.com>*

**Comment by huggsboson** [comment]
I'm happy to do the brew wrangling (what little there is, I'd just prefer to point it at a proper release/tag).

**Comment by sparkprime** [comment]
It is done!

**Comment by huggsboson** [comment]
Thank you!

**Comment by lorrin** [comment]
> For mac, I think homebrew is sufficient until somebody requests macports.

I would appreciate a MacPorts release. :-)

**Comment by discordianfish** [comment]
I've create a small build repo which creates dynamically and statically linked binaries for jsonnet: https://github.com/latency-at/jsonnet-releases/releases

**Comment by sbarzowski** [comment]
@discordianfish That's cool! I've also checked that the same script can be used to build Windows binaries (in context of discussion in #380).

**Comment by discordianfish** [comment]
@sbarzowski happy to accept PRs for other platforms

**Comment by sbarzowski** [comment]
We have binary releases these days, for Linux and OS X. I'm going to close this. Many thanks to everyone who worked on this stuff!

**Comment by DocX** [comment]
Can we add 64 bit linux binaries please?

**Comment by sbarzowski** [comment]
@DocX The Linux binaries are 64 bit.
