### ISSUE TITLE
Missing std.manifestJson and incorrect description of std.manifestJsonMinified in doc/ref/stdlib.html

### ISSUE THREAD

**Issue by RadxaYuntian** [google/jsonnet#1151]
I just want a simple function to output a Json file. `stdlib.html` told me there are either `std.manifestJsonEx` or `std.manifestJsonMinified` for me to choose. But you really have to look at `std.manifestYamlDoc` to know that there is actually a 3rd `std.manifestJson` function, which doesn't need any additional parameters, and prints in nice formatting.

Also the explanation of `std.manifestJsonMinified` is broken, which reads `Under the covers, it calls std.manifestJsonEx:')`. That's not a valid function call.

**Comment by johnbartholomew** [comment]
Thanks for reporting the missing docs! Fixed by #1154
