### ISSUE TITLE
ERROR: Dynamic field with Comprehension does not recornize variables

### ISSUE THREAD

**Issue by youngbo89** [google/jsonnet#1168]
###  Description

Expect Dynamic field with Comprehension does works, but not:
```jsonnet
// test.jsonnet 
{
  local myList = [
    {
      name: 'A',
    },
    {
      name: 'B',
    },
  ],

  [item.name]: item for item in myList
}
```

```shell
$ jsonnet test.jsonnet 
test.jsonnet:11:33-39 Unknown variable: myList

  [item.name]: item for item in myList
```

But this case, it works
```jsonnet
// test2.jsonnet 
local myList = [
  {
    name: 'A',
  },
  {
    name: 'B',
  },
];

{
  [item.name]: item
  for item in myList
}
```

```shell
$  jsonnet test2.jsonnet            
{
   "A": {
      "name": "A"
   },
   "B": {
      "name": "B"
   }
}

```

### version
```
$  jsonnet --version
Jsonnet commandline interpreter (Go implementation) v0.20.0
```

**Comment by CertainLach** [comment]
This is not a bug, locals defined inside of comprehensions may only be used by defined fields, and may use locals defined by comprehension, but can't be used by comprehension itself.
I.e

```jsonnet
{
  local valueX2 = value * 2;
  [key]: valueX2
  for [key, value] in {a: 1, b: 2}
} == {a: 2, b: 4}
```

**Comment by youngbo89** [comment]
> This is not a bug, locals defined inside of comprehensions may only be used by defined fields, and may use locals defined by comprehension, but can't be used by comprehension itself. I.e
> 
> ```jsonnet
> {
>   local valueX2 = item.value * 2,
>   [item.key]: valueX2,
>   for item in {a: 1, b: 2}
> } == {a: 2, b: 4}
> ```

It does not work for "Top-level object" case. For example:

```JSONnet
{
  [obj.name]: {
  }
  for obj in $.myObjects
}
```

and I got this result:
```shell
jsonnet my-objects.libsonnet:87:13-14 No top-level object found.
```


Is it also expected result, too?

**Comment by CertainLach** [comment]
> Is it also expected result, too?

Yes.

Object comprehension is evaluated eagerly, before object extension is done, so `$`, `self`, `super` don't work in that context.
We can't get fields of object, whose fields we may not yet know.

**Comment by youngbo89** [comment]
Thank you for kind explanations!
