### ISSUE TITLE
Ugly error as there is no string formatter for AST

### ISSUE THREAD

**Issue by jbeda** [google/jsonnet#120]
```
$ ./jsonnet -e 'function(a, 1)'
STATIC ERROR: <cmdline>:1:13: Not an identifier: 0x7fbd51500350
```

It looks like, in parseParams, we are trying to output an AST object but there is no string formatter for ASTs.  Perhaps unparse the AST there?  Or try not to dump the text?

**Comment by sparkprime** [comment]
Doing what you did on the Go side is probably good enough: "Expected an identifier but got a complex expression"
