### ISSUE TITLE
Use a library for argument parsing

### ISSUE THREAD

**Issue by davidzchen** [google/jsonnet#125]
I think using a library such as getopt or gflags for argument parsing can make the code in the jsonnet tool a lot cleaner. We would probably want to go with getopt since gflags has a slightly different syntax for flags (getopt --long-opt vs gflags --long_opt).

**Comment by sparkprime** [comment]
Obvious question is do we want to add extra dependencies?  I did use getopt in some previous projects and I found it rather obtuse.  That's just my opinion though.

By how much would it make the code cleaner?
