### ISSUE TITLE
Defining mutually recursive local variables

### ISSUE THREAD

**Issue by copumpkin** [google/jsonnet#127]
Is this currently possible?

```
local foo = f(bar);
local bar = g(foo);
```

Or something like that? If I write literally the code above, it complains that `bar` isn't in scope.

**Comment by sparkprime** [comment]
```
local foo = f(bar),
      bar = g(foo);
```

I advise using the other syntax unless you actually need mutual recursion, though.  That way it's clear when it's happening / not happening.  This is something the formatter will probably enforce in future.

**Comment by copumpkin** [comment]
Makes sense, thanks!
