### ISSUE TITLE
Set up Bazel build for Travis

### ISSUE THREAD

**Issue by davidzchen** [google/jsonnet#137]
Currently, we are only running make test in the Travis build.

**Comment by sparkprime** [comment]
I couldn't figure out how to run two separate things in travis, do we just do them sequentially?

Once you've done this I volunteer to do the same thing for setup.py :)

This will mean I don't have to manually test this stuff when I make releases, which should speed stuff up a lot.

**Comment by mbrukman** [comment]
@davidzchen — are you working on this? I was about to file the same issue, good thing you beat me to it. Getting Bazel to work well with Travis CI is a bit of a project, but I've solved this issue previously on another project; see my [`.travis.yml`](https://github.com/mbrukman/autogen/blob/master/.travis.yml) for the details.

Let me know if you have any questions or need some help, I'm happy to help add Bazel support to this repo as well.

**Comment by sbarzowski** [comment]
We do this for go-jsonnet already, but not here.

**Comment by johnbartholomew** [comment]
The Travis build went away, but we now have a GitHub actions workflow, which does run the Bazel build:

https://github.com/google/jsonnet/blob/master/.github/workflows/build_and_test.yml#L70-L80
