### ISSUE TITLE
Please publish 0.8.7 final to pypi

### ISSUE THREAD

**Issue by benley** [google/jsonnet#150]
https://pypi.python.org/pypi/jsonnet still only has v0.8.7-pre6, which is making it difficult to update embedded dependencies.

(aside: "v0.8.7" isn't a valid setuptools version number - "0.8.7" would be better, but that might be a separate issue)

**Comment by sparkprime** [comment]
Should be up now

**Comment by sparkprime** [comment]
Should be up now

**Comment by sparkprime** [comment]
I didn't realize v was not allowed in semantic version, I actually thought it was required :)  I wonder if it's OK to remove it in future versions.

**Comment by sparkprime** [comment]
It ultimately comes from include/libjsonnet.h

#define LIB_JSONNET_VERSION "v0.8.7"
