### ISSUE TITLE
jsonnet --version is incorrect on v0.8.8 release and HEAD

### ISSUE THREAD

**Issue by mikedanese** [google/jsonnet#163]
Looks like it's hard coded and wasn't updated.

**Comment by sparkprime** [comment]
Yeah that is bad, although 0.8.8 and 0.8.7 are binary compatible so I'll probably just leave it until the next release.  I wonder what should go in there in HEAD.  Maybe just "HEAD"?  Or should it always be the next planned release (usually vx.y.z-rc1 or whatever).
