### ISSUE TITLE
fmt on json does not identify keys that are keywords

### ISSUE THREAD

**Issue by jschnare** [google/jsonnet#170]
If you run jsonnet fmt on something like this:

```
{
  "assert": null,
  "error": null,
  "function": null,
  "import": null
}
```
The output is invalid jsonnet:
```
{
  assert: null,
  error: null,
  function: null,
  import: null,
}
```

It should probably either error or quote any key that matches a defined keyword.

I'd like to mention, though, that otherwise it's much much better than my hacky json/jsonnet conversion scripts :-)

**Comment by sparkprime** [comment]
Thanks for the report, it was an easy fix :)
