### ISSUE TITLE
Arrays of dictionaries with same keys 

### ISSUE THREAD

**Issue by raman2805** [google/jsonnet#178]
The follow ill formatted json 
```  
[
    {
      "Value": 1.25
    } 
    {
      "Value": 2.5 
    }
]
```
gets converted to 
```
[
    {
      "Value": 2.5
    }
]
```

I would expect it to get converted to 
```  
[
    {
      "Value": 1.25
    }, 
    {
      "Value": 2.5 
    }
]
```

**Comment by igorpeshansky** [comment]
The second object overrides the first when the comma is missing, doesn't it?
        Igor

**Comment by raman2805** [comment]
Is this part of the documentation, maybe I missed it. Can this be disabled or this is an intended feature ?

**Comment by mikedanese** [comment]
@igorpeshansky is right. In the [spec](http://jsonnet.org/language/spec.html):
```
desugar(expr { ... }, b)	=	desugar(expr + { ... }, b)
```
Which means:
```
{ "Value": 1.25} {"Value": 2.5}
```
is desugared to:
```
{ "Value": 1.25} + {"Value": 2.5}
```

This is a language feature meant to allow convinient syntax

**Comment by sparkprime** [comment]
Yeah it's "unfortunate" that in this case forgetting a comma results in
different behavior rather than an error.  But it is intended, e.g. the
first example on jsonnet.org uses it:
person2: self.person1 { name: "Bob" }
