### ISSUE TITLE
"Room for names" in dictionary comprehensions

### ISSUE THREAD

**Issue by copumpkin** [google/jsonnet#205]
When I'm writing something of the form `{ [k]: v for foo in bar }`, if there's a big common subexpression between `k` and `v`, I don't think there's a place for me to abstract it out.

**Comment by sparkprime** [comment]
Duplicate of #90

**Comment by copumpkin** [comment]
Oh sorry! I'll close this

**Comment by sparkprime** [comment]
No worries, I had to dig to the second page to find it ;)

**Comment by sparkprime** [comment]
Specifically you'd write:

```
{ [big]: big for foo in bar local big = ... }
```
