### ISSUE TITLE
std.mergePatch loses hidden fields

### ISSUE THREAD

**Issue by guoshimin** [google/jsonnet#219]
```
% jsonnet -e 'local a = {a:: "foo"}; local b = std.mergePatch(a, {}); b.a'
RUNTIME ERROR: Field does not exist: a
	<cmdline>:1:57-59
```

**Comment by sparkprime** [comment]
This is because mergePatch is a JSON standard and the value is effectively manifested to JSON first.  What are you trying to do?

**Comment by guoshimin** [comment]
Sorry for the late response. I can't recall what motivated this issue report. I guess it was just that this behavior didn't seem intuitive to me. I'll close it for now and reopen if I have a real use case.

**Comment by dxlr8r** [comment]
Sorry for resurrecting and old thread. But I came a cross the same issue the other day. I use Jsonnet for Terraform, and the way I create modules using Jsonnet, and want to pass data between the modules (which are merged using std.mergePatch), hidden fields I want to lookup are missing after I merge them.
