### ISSUE TITLE
Read file contents and do string replacement on that

### ISSUE THREAD

**Issue by garo** [google/jsonnet#238]
I have an use case with Terraform that I would want to read a file from system, do a set of string replacements in that file based in variables defined in jsonnet and then base64 encode the resulted string so that I can pass that into the created json.

I suppose that I could do a pull request for a function which loads a file from the filesystem as a string, if it's generally agreed that it's a feature suitable to the stdlib.

**Comment by mikedanese** [comment]
Can you use 'importstr'?

**Comment by sparkprime** [comment]
Use importstr and then do python-style string formatting, e.g.
(importstr "myfile.txt") % { foo: "bar" } and inside the file, do

```
I spend most of my time at the %(foo)s.
```
