### ISSUE TITLE
documentation: Multiple file output command goes wrong

### ISSUE THREAD

**Issue by fairy-tale007** [google/jsonnet#243]
In [Multiple file output](http://jsonnet.org/implementation/commandline.html) section,
this line command goes wrong without specify a directory when using `-m` option.

``` bash
// ERROR
$ jsonnet -m multiple_output.jsonnet

// CORRECT, output multiple files in the current directory .
$ jsonnet -m . multiple_output.jsonnet
```

**Comment by sparkprime** [comment]
Docs are out of date, thanks for the heads up.

**Comment by fairy-tale007** [comment]
hi, @sparkprime 
can jsonnet output multiple files using Python API. I haven't found such API, however I'd like to need such kind of API. 

thanks:)

**Comment by sparkprime** [comment]
No, the Python API doesn't write any files.  It just gives you the string back, from there you can parse it into JSON, and do the file writing yourself.  Likewise the C API does not write anything, it is the jsonnet commandline utility (a client of the C library) that implements -m.

**Comment by sparkprime** [comment]
Ok that's a bit of a lie because the C API will carve up the JSON for you, to avoid parsing JSON in the C client app.  But that's because parsing JSON requires a 3rd party library in C whereas in Python it's trivial.

**Comment by fairy-tale007** [comment]
I understand, so a straightfoward way is to call `jsonnet -m <dir> <filename>` command in Python code,[here is a example ](http://stackoverflow.com/a/3777308/6155876). Drawback here is Python code has to rely on jsonnet commandline utility.

Another way is to split the string returned by Python API and to write into multiple files, but it seems a tough job and I haven't found a feasible solution.

**Comment by sparkprime** [comment]
It's not so hard:

```
import _jsonnet
import json

json_str = _jsonnet.evaluate_snippet('<inline>', '{ "x.json": "foo", "y.json": "bar"}')
json_ast = json.loads(json_str)
for k, v in json_ast.iteritems():
  with open(k, 'w') as f:
    f.write(v)
```

**Comment by fairy-tale007** [comment]
Tried, it did work. Think of the returned string as `key:value` pairs which is corresponding to `filename:filecontent`
Really, beautiful! many thanks.

**Comment by sparkprime** [comment]
Glad you like it.  I updated the docs re: original bug report, so closing now.
