### ISSUE TITLE
Create new release for jsonnet

### ISSUE THREAD

**Issue by huggsboson** [google/jsonnet#245]
Can we create a new release to take advantage of the perf improvements introduced?  (Our current upgrade process involves upgrading the central brew repo and asking our users to upgrade).

@sparkprime

**Comment by huggsboson** [comment]
@ahakanbaba

**Comment by sparkprime** [comment]
Sure, ping me on Monday

**Comment by ahakanbaba** [comment]
Hi Dave,
I would like to send you a friendly reminder about generating a new
release.
Thanks
Hakan

**Comment by sparkprime** [comment]
Done
