### ISSUE TITLE
jsonnet_native_callback comment should mention that params array is null-terminated

### ISSUE THREAD

**Issue by anguslees** [google/jsonnet#256]
I haven't dug much deeper than finding that jsonnet seems to cast the C++ argv vector to create the `jsonnet_native_callback` C `const char * const *params` arg.  Afaics, there is no way to specify the *length* of this array, and this is a bug.

I note the python API tracks the length of this array in the context.  This works for the python callback itself to examine the arguments passed, and I thought this was sufficient.  I've just tried using this feature (not via python) and discovered that jsonnet also uses the argument list to validate the number of arguments passed before calling my callback - and this means jsonnet itself is trying to determine the size of this array!  Without an understanding of how the length is passed, how does this work?  Is this a segfault waiting to happen?

**Comment by anguslees** [comment]
Aha! I take it all back.

I finally read the code of `jsonnet_native_callback` itself and it quite clearly expects a NULL-terminated array, which is just fine.

I'll change this into a much lower-urgency documentation wishlist:  We should mention that the params array is null-terminated ;)

**Comment by sparkprime** [comment]
Sorry that wasn't clear and thanks for looking into it.  Also congrats on getting bug number 256 :)
