### ISSUE TITLE
Python 3.x Compatibility

### ISSUE THREAD

**Issue by tyler-elric** [google/jsonnet#26]
I forked and converted to use Visual Studio, and I also changed support from Python 2 C API to Python 3.4 API. It wasn't horribly difficult to do either task, but the project is there for anybody who needs or wants it.

**Comment by wiseman** [comment]
Would this project accept a pull request that made jsonnet compatible with both Python 2 and Python 3?

**Comment by sparkprime** [comment]
Yes, please submit a PR to google/jsonnet with the changes to _jsonnet.c.  How does this work, do we distribute it via a separate pypy package?

**Comment by benley** [comment]
I had a go at a hybrid python2/python3 module with a bunch of `#ifdef`s.  It should not require a separate pypi package, since jsonnet is distributed as a source tarball there.
