### ISSUE TITLE
CLI redirecting file contents

### ISSUE THREAD

**Issue by dewdad** [google/jsonnet#270]
I'm on windows. I have a working jsonnet.exe. I tried,

> jsonnet.exe < config.jsonnet
> jsonnet.exe -e < config.jsonnet
> jsonnet.exe -S < config.jsonnet
> jsonnet.exe -S -e < config.jsonnet
> type config.jsonnet | jsonnet.exe
> type config.jsonnet | jsonnet.exe -e
> type config.jsonnet | jsonnet.exe -e -S

Can't get it to work. At best I get the following errors:
ERROR: Must give code
ERROR: Must give filename

How can I put jsonnet on stdin to be transpiled?

Thank you,
Avital

**Comment by sparkprime** [comment]
You should be able to do it with jsonnet.exe -

**Comment by dewdad** [comment]
Do you have a working example?
