### ISSUE TITLE
Usage in NodeJS applications as build transform

### ISSUE THREAD

**Issue by dewdad** [google/jsonnet#274]
I would like to use Jsonnet as a build tool in my NodeJS project. I've tried using some ports to JS with no luck. I have succeeded in using the cmd tool, but then I would need a separate binary for each platform installed in my project sources.

Is there a way to compile Jsonnet to JavaScript along with the command line interface like the executable build?

**Comment by dewdad** [comment]
I think if you provided a CLI for the NodeJS community the beautiful language could really light up.

**Comment by sparkprime** [comment]
The new Go port is much easier to embed into a build system in a cross-platform way, and could even be transpiled to js using gopherjs so I think this is now covered.
