### ISSUE TITLE
pip install fails with versions 0.9.1 and 0.9.2

### ISSUE THREAD

**Issue by mhmxs** [google/jsonnet#298]
I tried to use `pip install jsonnet`, but it failed. The reason is:
```
    core/vm.cpp:27:17: fatal error: md5.h: No such file or directory
     #include "md5.h"
                     ^
    compilation terminated.
    make: *** [core/vm.o] Error 1
```

I downloaded the packages and `third_party` directory is missing. Version 0.9.0 works as well.

**Comment by sparkprime** [comment]
I get it too.  It looks like it needs an extra item in the list of includes.

Weird that the travis test still works, it's designed to test this stuff.  https://travis-ci.org/google/jsonnet/jobs/196793982

**Comment by mhmxs** [comment]
During compile time third_party/md5.h was [there](https://travis-ci.org/google/jsonnet/jobs/196793982#L313) and it is also in the release bundle on github, but missing from that [archive](https://pypi.python.org/pypi/jsonnet/0.9.2).

**Comment by sparkprime** [comment]
It'll be the MANIFEST.in file

**Comment by sparkprime** [comment]
0.9.3 should work
