### ISSUE TITLE
Add a way to check the presence of ext vars

### ISSUE THREAD

**Issue by chrismcbride** [google/jsonnet#304]
Sorry if this is possible already and I overlooked it. I'd like a way to see if an ext var is defined without getting a hard error. Something like std.hasExtVar('myvar'). Id like to be able to optionally pass in ext vars.

**Comment by sparkprime** [comment]
This comes up a lot.  We decided not to allow this because extVars buried deep in the config can get forgotten about and it makes it possible for a config to have surprising behavior if you forget an extVar or mistype it.  So the solution is to use top level arguments instead.  Practically, this just means wrapping your top level Jsonnet file in function (...) ...

```
$ jsonnet -e 'function(myvar="default") { x: myvar }' --tla-str myvar=foo
{
   "x": "foo"
}
```

```
$ jsonnet -e 'function(myvar="default") { x: myvar }' 
{
   "x": "default"
}
```

**Comment by sparkprime** [comment]
The point is that myvar is only in scope for that one file.  If you want it in other files you have to explicitly thread it through as a function argument or some other explicit mechanism.

**Comment by sparkprime** [comment]
You could just use null for the default in that case.  --tla-str will only ever override it with a string so it won't confuse "null" and null.

**Comment by chrismcbride** [comment]
Sounds good, Ill close this.

**Comment by laciferin2024** [comment]
jsonnet -V Message=1 default.dart 
RUNTIME ERROR: Field does not exist: hasExtVar
        default.dart:2:6-19     function <getExt>
        default.dart:20:11-108  thunk from <object <anonymous>>
        Array element 1
        Field "Entrypoint"
        Field "Docker"
        Field "Spec"
        Field "job"
        During manifestation

```
local getExt(varName, default) =
  if std.hasExtVar(varName) then std.extVar(varName) else default;

```
