### ISSUE TITLE
"Returning" an item from a function

### ISSUE THREAD

**Issue by hausdorff** [google/jsonnet#306]
This is somewhat related to the (OT) [tangent discussion](https://github.com/google/jsonnet/issues/302#issuecomment-282866371) I brought up on issue #302. So, I apologize if this stutters a bit, but I'm curious to hear what you think about a more general pattern that this tangent fits in to.

In Jsonnet I often find myself wanting to use an object in a function to "hide" locals, but then later "return" one of the locals I used. For example, if you imagine some syntax for `return` (I'm not proposing this as a solution, but presenting it as a way of expressing what I'd like to do), you might write something like:

```c++
{
  foo():: {
    // `bar` is "hidden" in the body of `foo` because it is `local`.
    local bar = [... do some fancy work here ...]

    // But we want to "return" the result of `processBar`, rather
    // than an object containing it.
    return processBar(baz),
  },
}
```

What is the Jsonnet-y way to accomplish this?

**Comment by hausdorff** [comment]
Ah. I think I found out how to do it something that has a similar effect as above. You can do something like this:

```c++
{
  bar(a):: { a: a },
  foo(a)::
    local f = a;
    self.bar(f),
  baz: self.foo(4),
}
```

```json
{
   "baz": {
      "a": 4
   }
}
```

This use of `local` is not documented as far as I can tell; I think it's worth mentioning it at least in the tutorial. If you like, I can create a pull request to add it.

**Comment by sparkprime** [comment]
It could be clearer but it is mentioned in the local variables section in
the context of putting an import at the top level. If you think you can
make it clearer, please submit a pr
