### ISSUE TITLE
Alpine based Docker image

### ISSUE THREAD

**Issue by devth** [google/jsonnet#308]
I'd be happy to help set this up.

**Comment by sparkprime** [comment]
Go for it.

**Comment by devth** [comment]
Should it be built and pushed during CI?

I typically push a `latest` from CI, and if it's a `tag` event I use the tag to build a released version.

**Comment by devth** [comment]
If you create an Automated Build at https://hub.docker.com/r/google/jsonnet you can get `latest` (from master) and exact versions from tags built automatically on every `push`. Config should look like:

![image](https://cloud.githubusercontent.com/assets/86107/25854875/c8a494a2-348e-11e7-99c2-840edaf6b6b1.png)

**Comment by devth** [comment]
Hey @sparkprime, have a chance to look at this?

**Comment by sparkprime** [comment]
I couldn't set it up under 'google' as that org did not exist.  I set it up here https://hub.docker.com/r/sparkprime/jsonnet/ but not sure if that's ideal.  I guess, as it's a public repo, anyone can set this up if they need it, so it's not a big deal :)

**Comment by devth** [comment]
Oh, that's strange. https://hub.docker.com/u/google/ exists.

**Comment by sparkprime** [comment]
Ah yes, I just don't have access.  I will ask for access...

**Comment by devth** [comment]
@sparkprime any luck getting access to push the docker image to `google/jsonnet`?

**Comment by ghostsquad** [comment]
@sparkprime I'm also looking for the official jsonnet image. It doesn't look like it's been uploaded to google's docker account yet.

**Comment by sparkprime** [comment]
Not sure why I closed this...

I found some internal documentation saying that Google Container Registry is preferred over Docker Hub. Is that OK?

**Comment by mdub** [comment]
I too am keen to see an "official" published `jsonnet` repository.

I think either/any public registry would do the trick.

**Comment by mkmik** [comment]
In the meantime I asked my colleagues at bitnami to setup an automated build pipeline for the [bitnami/jsonnet](https://github.com/bitnami/bitnami-docker-jsonnet) image, since I had a practical need for it.

An official google/jsonnet image would be nice. Or you can just off-source that to bitnami (we'll track github releases automatically) if you prefer.

It's based on [minideb](https://github.com/bitnami/minideb) instead of alpine. It's 55Mb in size.

```
$ docker run bitnami/jsonnet --version
Jsonnet commandline interpreter v0.11.2
```

**Comment by sbarzowski** [comment]
I've never used it, but I think we have one? I can see alpine-based Dockerfile. I'm going to close this issue, but feel free to reopen / comment if it's not sufficient.

**Comment by marcusschiesser** [comment]
@sbarzowski can you please link the official jsonnet image here? https://hub.docker.com/r/google/jsonnet does not exist anymore

**Comment by sbarzowski** [comment]
Ah, ok, I misunderstood this issue. It's about having an image in a registry. I'm going to reopen this.

There is no official image currently. If someone wants to just try it out quickly, I have created `sbarzowski/jsonnet`.

**Comment by mkmik** [comment]
Why not just offsource the official image to Bitnami? We have a good track record on keeping images up to date with upstreams (and make up a good chunk of the popular images in public cloud marketplaces, including GCP)

**Comment by sbarzowski** [comment]
It's fine with me.

@sparkprime What do you think?

**Comment by sparkprime** [comment]
Go for it

**Comment by sbarzowski** [comment]
The Jsonnet containers provided by Bitname are out there. I'm closing this.
