### ISSUE TITLE
Feature proposal: std.prune

### ISSUE THREAD

**Issue by jbeda** [google/jsonnet#313]
For ksonnet I created a `prune` method that removes all empty object, arrays and nulls from a parent structure.  This can clean up "cruft" that is left over by initialized fields for mixins.

https://github.com/ksonnet/ksonnet-lib/blob/master/ksonnet.beta.1/util.libsonnet#L3

I'd be happy to submit a PR to add this to the std library if there is any desire.

**Comment by sparkprime** [comment]
Sure, it seems pretty re-usable.  But I would make inline pruneObj and pruneArr into prune, and make isContext a local function inside prune, so the top-level footprint is just the single function prune.
