### ISSUE TITLE
external variables / top-level arguments not mentioned in the tutorial

### ISSUE THREAD

**Issue by sparkprime** [google/jsonnet#347]

**Comment by kinghrothgar** [comment]
This would be very helpful. I came across this trying to figure out how to use these and the differences between them.

**Comment by sbarzowski** [comment]
Related SO question: https://stackoverflow.com/questions/48412535/how-to-call-parameterized-jsonnet-from-bash/48415992?noredirect=1#comment83861454_48415992

**Comment by sparkprime** [comment]
I'm rewriting the tutorial right now, will include them

**Comment by tylermauthe** [comment]
@sparkprime - if it's available on a branch or something I'm happy to be an alpha tester.

**Comment by sparkprime** [comment]
http://spark.gritengine.com/learning/tutorial.html

There's a bunch of pages uploaded but they're all broken except that one and the top-level index

**Comment by sparkprime** [comment]
Website now live
