### ISSUE TITLE
Add a list of companies using Jsonnet to GitHub repo

### ISSUE THREAD

**Issue by mbrukman** [google/jsonnet#349]
New users often like to know who else is already using a project, who is already running it in production or otherwise critically depending on it, before deciding to bet on it themselves. Also, even if you have a developer who's a fan of Jsonnet, they will have to convince their leads / management to run it in production, and having third-party voices that are already doing that makes more users comfortable with taking the leap of putting Jsonnet in the critical production stacks.

In other words: everyone wants someone else to be the pioneer / bleeding edge tester, but once it's proven, it's a snowball effect since everyone wants to be using what other successful users are already using. Thus, having a list of existing production users is critical to growing the Jsonnet user base.

**Note: please be sure to get explicit permission from each of the companies before adding their name to a public list.**

Here are some companies that are pretty clearly using Jsonnet already:

* Box - see [blog post](https://blog.box.com/blog/kubernetes-box-microservices-maximum-velocity/)
* Databricks - see [blog post](https://databricks.com/blog/2017/06/26/declarative-infrastructure-jsonnet-templating-language.html)
* Heptio - see [ksonnet project](https://github.com/ksonnet/)

Potential sources of other users:

* [LinkedIn search for "jsonnet"](https://www.linkedin.com/search/results/index/?keywords=jsonnet)
* comments such as [this one](https://news.ycombinator.com/item?id=13901416) on HackerNews:
  > Take a look at jsonnet: http://jsonnet.org. It extends JSON with loops, conditionals, variables and more in an elegant way. We don't write JSON anymore and treat it like an "assembly language." We use jsonnet to generate CloudFormation templates, terraform templates and Kubernetes resource definitions.

For inspiration from other projects, see these lists:

* [Apache Airflow (incubating)](https://github.com/apache/incubator-airflow#who-uses-airflow)
* [JanusGraph](https://github.com/janusgraph/janusgraph/#users)

**Comment by sparkprime** [comment]
New website has a list of users on the front page.  Hopefully the list will grow as I send more emails :)
