### ISSUE TITLE
Explain how to use Bazel with Jsonnet

### ISSUE THREAD

**Issue by mbrukman** [google/jsonnet#352]
By which I mean, not build Jsonnet with Bazel, but how a Jsonnet user can use Bazel.

Specifically, I'm referring to explaining how one can use https://github.com/bazelbuild/rules_jsonnet in their own Jsonnet project. Jsonnet project itself uses these rules, but to an external observer, there does not appear to be docs in this repo to explain how to use Bazel + Jsonnet in the context of another project.

**Comment by sparkprime** [comment]
So we basically need to link to https://github.com/bazelbuild/rules_jsonnet/blob/master/README.md somewhere on the website

**Comment by johnbartholomew** [comment]
It's a little sparse, but https://jsonnet.org/learning/tools.html links to https://github.com/bazelbuild/rules_jsonnet since #851 (October 2020).
