### ISSUE TITLE
Tutorial: Document importstr

### ISSUE THREAD

**Issue by fluffysquirrels** [google/jsonnet#371]
My use case is some certificate and private key files that are direct output from openssl, which I'd like to package up with the rest of my configuration into a single .json file.

**Comment by fluffysquirrels** [comment]
Whoops, just seen that this was <https://github.com/google/jsonnet/issues/14>. Any specific reason that that was closed?

**Comment by sbarzowski** [comment]
> Any specific reason that that was closed?

Because this functionality was added in the linked change.

You can do `importstr 'private_key'` and it will return a string.

**Comment by sbarzowski** [comment]
Maybe it could be mentioned in the tutorial. It seems it's only in the specification at the moment.

**Comment by fluffysquirrels** [comment]
Oh dear, double whoops! I presume it'd be useful for me to submit a PR to add `importstr` to the tutorial?

**Comment by sbarzowski** [comment]
Sure!
