### ISSUE TITLE
Naive quoting of import paths

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#372]
```
importstr " \" \' \n\n\t\t"
```
```
RUNTIME ERROR: Couldn't open import " " ' 

                ": No match locally or in the Jsonnet library paths.
        testdata/nonexistent_import_crazy.input:1:1-39
```

This is not a very big problem in practice as people calling their libraries " \" \' \n\n\t\t" probably deserve this :-).

**Comment by sparkprime** [comment]
You're referring to the fact the error message doesn't re-quote the string, right?

**Comment by sbarzowski** [comment]
Well, it puts it in quotes, but it doesn't escape any special characters.
