### ISSUE TITLE
can not import bazel project using Jetbrains Clion

### ISSUE THREAD

**Issue by mqliang** [google/jsonnet#384]
Can not import bazel project using Jetbrains Clion

![image](https://user-images.githubusercontent.com/12423751/31170846-a1ba01dc-a938-11e7-9d7f-934318a9da26.png)
![image](https://user-images.githubusercontent.com/12423751/31170864-b1e5c06e-a938-11e7-99b6-f184ace8477b.png)
![image](https://user-images.githubusercontent.com/12423751/31170889-c629974e-a938-11e7-9e28-b4b9e92fc9c1.png)
![image](https://user-images.githubusercontent.com/12423751/31170906-d8c45f1a-a938-11e7-9f45-4773d5b29eda.png)
![image](https://user-images.githubusercontent.com/12423751/31170934-f45e439e-a938-11e7-866b-2fd1a5eddc1d.png)

**Comment by mqliang** [comment]
If I select to "Create from scratch" instead of "Import form workspace", then Clion can not find include files.

![image](https://user-images.githubusercontent.com/12423751/31171679-89ca1fa0-a93b-11e7-81d2-310794bdb977.png)
![image](https://user-images.githubusercontent.com/12423751/31171685-9113b820-a93b-11e7-9632-f74e305aef73.png)
![image](https://user-images.githubusercontent.com/12423751/31171691-96f0c77e-a93b-11e7-920b-890b5bd00334.png)

**Comment by sparkprime** [comment]
I'm not familiar with CLion and only somewhat familiar with the Bazel build of Jsonnet.  @davidzchen might know more.  At first glance it looks like CLion isn't using the latest version of Bazel, or something like that?

**Comment by poryfly** [comment]
> Can not import bazel project using Jetbrains Clion
> 
> ![image](https://user-images.githubusercontent.com/12423751/31170846-a1ba01dc-a938-11e7-9d7f-934318a9da26.png)
> ![image](https://user-images.githubusercontent.com/12423751/31170864-b1e5c06e-a938-11e7-99b6-f184ace8477b.png)
> ![image](https://user-images.githubusercontent.com/12423751/31170889-c629974e-a938-11e7-9e28-b4b9e92fc9c1.png)
> ![image](https://user-images.githubusercontent.com/12423751/31170906-d8c45f1a-a938-11e7-9f45-4773d5b29eda.png)
> ![image](https://user-images.githubusercontent.com/12423751/31170934-f45e439e-a938-11e7-866b-2fd1a5eddc1d.png)



> If I select to "Create from scratch" instead of "Import form workspace", then Clion can not find include files.
> 
> ![image](https://user-images.githubusercontent.com/12423751/31171679-89ca1fa0-a93b-11e7-81d2-310794bdb977.png)
> ![image](https://user-images.githubusercontent.com/12423751/31171685-9113b820-a93b-11e7-9632-f74e305aef73.png)
> ![image](https://user-images.githubusercontent.com/12423751/31171691-96f0c77e-a93b-11e7-920b-890b5bd00334.png)

hi,how do you import bazel projiect finally? I also have this problem.
