### ISSUE TITLE
Add an environment variable for JPATH

### ISSUE THREAD

**Issue by josdotso** [google/jsonnet#395]
Hi. This page doesn't mention an env var manner of setting `-J`.  Is there a colon-delimited env var for this?

http://jsonnet.org/implementation/commandline.html

Thanks!

**Comment by sparkprime** [comment]
No but it is a good idea.  Feel free to add it to cmd/jsonnet.cpp :)

**Comment by andreabedini** [comment]
Closed by d41445767f7528c9dd8096c158d366f05188cda3 :)

**Comment by josdotso** [comment]
Thanks!
