### ISSUE TITLE
ApplyBrace uses AST_BINARY ASTType, instead of  say AST_APPLY_BRACE

### ISSUE THREAD

**Issue by malkia** [google/jsonnet#396]
I made a larger patch (not yet proposed), that changes all dynamic_casts in core/desugarer.cpp and core/static_analysis.cpp (right now, few more files later) to use the ASTType instead of dynamic_cast. This imrpoves one specific case from ksonnet-lib from 2.9 secs to 1.5 secs (and possibly less once all dynamic_casts are done).

Anyway, why doing this I've found that ApplyBrace is misuing(?) AST_BINARY as ASTType, and should have its own. This might (or might not) have some impact on core/vm.cpp where AST_BINARY is directly checked, but assuming dynamic_cast would be on just Binary (possibly oversight).

Nothing urgent, just wondering if I can fix it for my own patch, and would it still work. I've took a brief look, and all AST Nodes are one-level inhertiance over, so I could possibly assume that dynamic_cast<> can completely be changed with switch case over ASTType (as done in core/vm.cpp)

Thanks!

**Comment by sparkprime** [comment]
That is a good idea, please do it.

ApplyBrace should have its own enum value, that is a bug, please fix it.  ApplyBrace is desugared so will not arise in the VM's internal switch.

Can you give some commands for checking out and running jsonnet on this ksonnet-lib file?  I'd like to try it on go-jsonnet too.
