### ISSUE TITLE
Functions vs. Keys

### ISSUE THREAD

**Issue by jmdots** [google/jsonnet#403]
I'm new to jsonnet.  Is it possible create a function that takes arguments and interpolates keys (not values) with them?  

Suppose that I want the name of `b` (second occurrence below) to be assigned from argument `b` (first occurrence).  Is this possible?   

In general, can we name keys generated inside functions by resolving argument names?
```
{
  a(b, c, d)::
    {
      b: [
        {
          "c": c,
          "d": [
            {
              "x": d,
            },
          ],
        },
      ],
    },
}
```

**Comment by sbarzowski** [comment]
Yes, it is possible. 

```
{
  a(b, c, d)::
    {
      [b]: [
        {
          "c": c,
          "d": [
            {
              "x": d,
            },
          ],
        },
      ],
    },
}
```

Generally you can use any expression as key:
```
{
  ["a" + "b" + "c"]: "something"
}
```

**Comment by jmdots** [comment]
This is very helpful.  Thank you!
