### ISSUE TITLE
jsonnet argument parser spits arguments wrong on spaces

### ISSUE THREAD

**Issue by farcaller** [google/jsonnet#408]
Jsonnet cannot handle arguments that contain a space properly, spitting them. It's most noticeable in `--ext-code` and `--tla-code`:

```bash
% echo 'std.extVar("myvar")' | jsonnet --ext-code 'myvar={a: 1}' -
```

expected result:
```json
{
   "a": 1
}
```

actual result:
```
ERROR: Already specified filename as "1}"
```

**Comment by sbarzowski** [comment]
@farcaller 
Thanks for the report, but well, it works on my machine...

Which version of jsonnet are you using (`jsonnet -v`)? I tried it on 0.9.4, 0.9.5 and go-jsonnet and I got the expected output every time.

**Comment by farcaller** [comment]
It's with v0.9.4. The HEAD works fine for me, though.
