### ISSUE TITLE
Bad list comprehension fmt output 

### ISSUE THREAD

**Issue by ashi009** [google/jsonnet#410]
I'm trying to auto format my code with `jsonnet fmt`, but the output for list comprehension is not ideal.

Input:
```jsonnet
local env = {
  fromMap(envs):: [
    { name: name, value: envs[name] } for name in std.objectFields(envs)
  ],
};
env
```

After `jsonnet fmt --string-style s --pad-arrays`:
```jsonnet
local env = {
  fromMap(envs):: [
    { name: name, value: envs[name] }
for name in std.objectFields(envs) // <--- this doesn't LGTM
  ],
};
env
```

```
$ jsonnet --version
Jsonnet commandline interpreter v0.9.5
```

**Comment by sbarzowski** [comment]
The defaults are the problem here, see #359.

After adding `-n 2` option the result will be reasonable:
```
jsonnet fmt --string-style s --pad-arrays -n 2
```

By default we don't reindent the code, but some newlines may still be inserted.

**Comment by sparkprime** [comment]
We should disable newline insertion if n is 0

**Comment by ashi009** [comment]
I think this can be marked as obsolete in favor of #359.
