### ISSUE TITLE
FR: Allow configuring library search path from environment variable

### ISSUE THREAD

**Issue by ashi009** [google/jsonnet#411]
It would be more convenient to set jsonnet library search path from environment variable instead of from argument.

```
export JSONNETPATH="${HOME}/abc"
jsonnet "$@"
# ==> equivalent to
# jsonnet -J "${JSONNETPATH}" "$@"
```

**Comment by sbarzowski** [comment]
I like it.

Technical note:
-J <path> adds another directory in which jsonnet will look for libraries.
So if you want multiple paths added you need to use -J option for each path. The environment variable would need to behave a bit differently - using  `:` as separator is the standard solution I believe.

**Comment by sparkprime** [comment]
Presumably it should use ; on windows?  Anyone know what Java does?

**Comment by sbarzowski** [comment]
Seems like Java uses `;`. See: https://stackoverflow.com/questions/1672281/environment-variables-for-java-installation

**Comment by sparkprime** [comment]
Duplicate: https://github.com/google/jsonnet/issues/395

**Comment by sparkprime** [comment]
In Go this is very easy: https://golang.org/pkg/path/filepath/#SplitList

**Comment by ashi009** [comment]
I meant to keep this simple, like GOPATH.  A common place to keep all the relevant jsonnet packages.

**Comment by sparkprime** [comment]
Splitting it by : or ; if _WIN32 isn't hard.  It would be weird to support multiple paths with -J and only one with env var.
