### ISSUE TITLE
Travis broken on Mac? /Users/travis/.travis/job_stages: line 166: shell_session_update: command not found

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#420]
`/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found`

Even though we already have a workaround for that in travis.yml. Are we doing something wrong or it it a problem with travis? 

People here had a similar problem and fixed it: https://github.com/mithro/yosys/commit/d2850b5b809759bafa7aead995d069acc023af15.

What's really happening there? What can we do about it?

**Comment by sparkprime** [comment]
I think the workaround has stopped working, and is therefore no longer working around the original issue, which still exists.  I'm confirming that by removing the rvm get line to see what happens.

**Comment by sparkprime** [comment]
There's another error at the top of the log, printed by rvm

**Comment by sparkprime** [comment]
Looks like the workaround isn't necessary any more.
