### ISSUE TITLE
Empty map key format error

### ISSUE THREAD

**Issue by ashi009** [google/jsonnet#424]
```
$ jsonnet -v
Jsonnet commandline interpreter v0.9.5
```

```
{
  '': true,
}
```

becomes

```
{
  : true,
}
```

**Comment by sbarzowski** [comment]
I vaguely remember a commit that fixes this. It might have not been released yet. Let me see.

**Comment by ashi009** [comment]
SG.  Cheers.

**Comment by sbarzowski** [comment]
Here's the commit https://github.com/google/jsonnet/commit/5c17788d4d692f0012592e9dd8e1914a0c2444fc

**Comment by ashi009** [comment]
Thanks!
Closing.
