### ISSUE TITLE
Support oct/hex number literals

### ISSUE THREAD

**Issue by ashi009** [google/jsonnet#425]
It's weird to not support non-decimal literals in a configuration language.

```
{
 container: k8s.Container {
  ...,
  args: {
   fileMode: 0644,  <----- STATIC ERROR: Expected a comma before next field.
  },
  ...
 }
}
```

**Comment by sparkprime** [comment]
That is also an unhelpful error message.

**Comment by sparkprime** [comment]
We could add octal and hex, but you have to be careful because we don't actually have integers, only doubles.  On the other hand, we do have bit arithmetic (Javascript semantics) so I guess the horse already bolted on that one.

**Comment by sparkprime** [comment]
In Javascript console:

0xFFFFFFFFFFFFFFFF == 0xFFFFFFFFFFFFFFFE
true

**Comment by ashi009** [comment]
True.

But theoretically Jsonnet can export to something other than json from ast.
For instance a text pb message.
Dave Cunningham <notifications@github.com>于2018年1月3日 周三下午11:25写道：

**Comment by sparkprime** [comment]
We added std.parseHex and std.parseOctal which should be good enough for putting the occasional bitflag / permission in.  I don't think it's worth complicating the lexer, formatter, all editor integrations, etc. for something that has relatively narrow use cases.
