### ISSUE TITLE
Record the inheritance tree

### ISSUE THREAD

**Issue by FRidh** [google/jsonnet#427]
As mentioned in https://github.com/google/jsonnet/issues/426 I am investigating whether we can use `jsonnet`. The dataset we have is large, consisting of about 3000 objects, that are built up through inheritance. One requirement we have is that we can compute the inheritance tree for analysis purposes.

Is there any support for getting this information out? Or do you have any suggestion? I thought of building up the dataset as
```
{
    TC0: { 
      attributes: {
        tc0: [ 0 ],
      }
    },

    TC1: {
      parents: [ "TC0" ],
      attributes: {
        tc1: [ 1 ],
      }
    },
    TC2: { 
      parents: [ "TC1" ],
      attributes: {
        tc2: [ 2 ],
        tc1+: [ 2 ],
      }
    }
    
}
```
and then map a function to perform the actual composition while still storing the `parents` field as a hidden field. However, I doubt operations like `tc1+: [ 2 ],` would work as desired. Any suggestions on how to track parents?

The function that would perform the object concatenation would do something like a fold. That would require a function (not the operator) for object concatenation. Does such function exist? I could not find it in the standard library.

**Comment by sbarzowski** [comment]
Hmm... I see a few options. It depends on what you really want to do with the tree.

Here are some ideas:

1) Have a custom addition function, that keeps information about the parents explicitly, for example:
`addObjects(left, right): left + right + ( left_parent:: left, right_parent:: right)`

2) If linearized inheritance is what you want (jsonnet inheritance is associative, so it's equivalent), it's enough to have something like `local obj = { inheritance +:: [obj]` field }`. 

You can have a function like `visibleInheritance(obj) = obj + { inheritance +:: [obj]` field}`. Then if you wanted some object to appear in inheritance list you would just wrap it in `visibleInheritance`.

3) There's no reflection available now for inheritance, but it's something that could be added. It will require some discussion, b/c it may limit our options of how objects are represented .

**Comment by FRidh** [comment]
I want to keep for each `TC` the `parents` field.

I'm thinking of something like
```
// Add two parents
local addParents(a, b) = a.attributes + b.attributes;

local macro(dict) = std.foldl(addParents, dict.parents, {}) + dict.attributes + {parents:: dict.parents};
{    
    TC0: macro ({ 
      parents: [],
      attributes: {
        tc0: [ 0 ],
      }
    }),

    TC1: macro ({
      parents: [ "TC0" ],
      attributes: {
        tc1: [ 1 ],
      }
    }),
    TC2: macro ({ 
      parents: [ "TC1" ],
      attributes: {
        tc2: [ 2 ],
        tc1+: [ 2 ],
      }
    })
    
}
```
I'll need to expose `self` so the `TC` can actually be found. I suppose I would have to add a parameter to macro and use a partially applied version so references to the `TCx` can be resolved.

**Comment by sparkprime** [comment]
There is no way to reflect over the tree built via mixin composition.  I don't think I'd want to add such a feature without broader need for it. I quite like your solution in comment 3 though. A similar option is to build up the structure and then use a post-pass to "squash" it.

You don't need to use `"TC0"`, since the fields are lazy.  You can just do parents: [$.TC0].

I'm getting very curious what your actual use case is.

**Comment by FRidh** [comment]
The use case is that we have test cases that are, in `jsonnet` terminology, objects. Inheritance is used to compose these objects. Currently, there are several thousand such objects. When one makes a change somewhere in the tree, it may make it difficult to see what is being affected. Obviously, introducing a change, manifesting to JSON and creating a diff will show you what is changed, but by analyzing the inheritance graph we can already see what cases are affected by a change and reason about where changes should and should not be made.

I've continued a bit, and have currently
```
txt = """

// Add two parents
local 
  
  // parents(self, [])
  parents(s, p) = local 
    getObjects(names) = [s[name] for name in names], 
    addParents(a, b) = a + b;
  std.foldl(addParents, getObjects(p), {}) + {_parents: p};

{   
    // self.parents([])
    parents(p):: local 
      getObjects(names) = [self[name] for name in names], 
      addParents(a, b) = a + b;
    std.foldl(addParents, getObjects(p), {}) + {_parents: p},

    TC0: {
      tc0: [ 0 ],
    },
    
    TC1: {
        foo: "Bar",
        some: ["Foo"],
    },
    TC2: self.parents(["TC1"]) + {
        some+: ["Bar"]
        // above is equivalent to
        //some: super.some + ["Bar"]
    },
    TC3: {
        x: [1, 2, 3, 4, 5, 6]
    },
    TC4: {
        y: [4]
    },
    TC5: self.parents(["TC3", "TC4"]) + {
        z: super.x + super.y    
    }
}
"""
```

Because the test cases are also grouped in files and references exist to cases in other files, we need to use a a fixed-point combinator in order to get a proper `self`-reference.

**Comment by sparkprime** [comment]
What about something like this:

```
local Test(name) = {
    _stack+:: [name],
    _parents: self._stack[0:std.length(self._stack) - 1]
};  
    
{     
    TC0: Test("TC0") { 
      tc0: [ 0 ],
    },
    
    TC1: Test("TC1") {
        foo: "Bar",
        some: ["Foo"],
    },
    TC2: $.TC1 + Test("TC2") {
        some+: ["Bar"]
    },
    TC3: Test("TC3") {
        x: [1, 2, 3, 4, 5, 6]
    },  
    TC4: Test("TC4") {
        y: [4]
    },
    TC5: ($.TC3 + $.TC4) + Test("TC5") {
        z: super.x + super.y,
    }
}   
```

**Comment by sparkprime** [comment]
The main irritation in there is the stuttering (saying TC0 and then "TC0"). We had a long discussion about that in the context of Kubernetes services. The best proposal we came up with is for a new keyword "here" which resolves to the enclosing field name (syntax sugar).  So then it looks like TC0: Test(here) { ... }

**Comment by andreabedini** [comment]
> The best proposal we came up with is for a new keyword "here" which resolves to the enclosing field name (syntax sugar). So then it looks like TC0: Test(here) { ... }

Just chipping in to say I'd love this feature and I would find it very useful (I was close to suggest it myself).

**Comment by sparkprime** [comment]
feature now has its own bug https://github.com/google/jsonnet/issues/437

**Comment by FRidh** [comment]
Thanks for the suggestion. 

> You can just do parents: `[$.TC0]`.

I prefer not to use the `$` solution, because I find it rather ugly: it requires you not only to know the structure of your object, but also how it is positioned in the file.

> The main irritation in there is the stuttering (saying TC0 and then "TC0")

What is actually the motivation for not requiring double quotes? As a newcomer I found it confusing that
- sometimes you use quotes, sometimes not
- `:` or `=`

**Comment by sbarzowski** [comment]
> I prefer not to use the $ solution

Instead of using $, you can give it a local name. Example:
```
local obj = {
    some_field: 42,
    self_referencing: obj.some_field
}; obj
```

> sometimes you use quotes, sometimes not

Object field names can be arbitrary strings. So you can do `{"with space": 42}` or `obj["with space"]`. It's often handy to treat object field names as identifiers - but that's just syntax sugar. So `{ blah: 42 }` is equivalent to `{ "blah": 42 }` and `obj.field` is equivalent to `obj["field"]`. There is no more magic to it. Is it more clear? Or did you mean something else?

> `:` or `=`

`:` (as well as `::` and `:::`, and their variants with `+`) is used for object fields. `=` is used for locals (and there is only one option there). For simple object fields we follow JSON convention. But `:` doesn't make much sense for local vars IMO.

**Comment by sparkprime** [comment]
We deliberately wanted the syntax for local fields to be a bit different (`=` vs `:`) because their semantics are completely different - they are lexically scoped and statically bound instead of using late bound OO. Also they are accessed directly (without self).

**Comment by sparkprime** [comment]
Example without $:

```
local Test(name) = {
    _stack+:: [name],
    _parents: self._stack[0:std.length(self._stack) - 1]
};  
    
{
    local tests = self,
    TC0: Test("TC0") { 
      tc0: [ 0 ],
    },
    
    TC1: Test("TC1") {
        foo: "Bar",
        some: ["Foo"],
    },
    TC2: tests.TC1 + Test("TC2") {
        some+: ["Bar"]
    },
    TC3: Test("TC3") {
        x: [1, 2, 3, 4, 5, 6]
    },  
    TC4: Test("TC4") {
        y: [4]
    },
    TC5: (tests.TC3 + tests.TC4) + Test("TC5") {
        z: super.x + super.y,
    }
}
```

(Actually this is the desugaring that implements $)

**Comment by sparkprime** [comment]
Or you can just use `self` instead of defining `tests`

**Comment by sparkprime** [comment]
Anything more we can do for you on this issue?

**Comment by FRidh** [comment]
I'll have to try and see what works best in my case. Thank you for the suggestions and the discussion.

**Comment by sparkprime** [comment]
No problem :)  Whatever you decide, please give us feedback.
