### ISSUE TITLE
Add GitHub Linguist config for Jsonnet

### ISSUE THREAD

**Issue by davidzchen** [google/jsonnet#43]
We should add an entry to [github/linguist](https://github.com/github/linguist) for Jsonnet so that GitHub can 1) add proper syntax highlighting for displaying .jsonnet files and 2) include them in the language stats for repositories.

**Comment by sparkprime** [comment]
I'd love that.  How hard is it?  Is it just a case of identifying some keywords and regular expressions?

**Comment by sparkprime** [comment]
I just added a syntax file that works for atom.  I understand that is the first step on this process.

**Comment by davidzchen** [comment]
FYI apparently GitHub's policy is that there needs to be a few hundred samples before they would be willing to accept a patch to Linguist. [Bazel's](https://github.com/google/bazel/issues/72) [pull request](https://github.com/github/linguist/pull/2348) was unfortunately rejected for the time being for this reason.

**Comment by davidzchen** [comment]
Here is the latest Jsonnet usage in GitHub: https://github.com/search?utf8=✓&q=extension%3Ajsonnet+NOT+nothack&type=Code&ref=searchresults

With over 300 files, we should now be meeting GitHub's criteria for adding Jsonnet to Linguist.

I have created a patch to Linguist that I will run through the proper channels before sending the PR. In the meantime, according to the [Linguist CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md), the grammar must be in its own repository since it will be included by Linguist as a Git submodule.

We will need to move the language-jsonnet Atom syntax package you added into its own repository before we can submit the PR to Linguist.

**Comment by sparkprime** [comment]
It says in there that it needs to be hundreds of repos, not hundreds of files.  I think we only have 10 repos or so so maybe we can't do this yet.

**Comment by davidzchen** [comment]
Though from github/linguist#2348:

> We normally require hundreds of samples before adding support for an extension

I'd be fine with waiting until we have some more usage before sending a PR.

In comparison, there are (546 .capnp files](https://github.com/search?p=3&q=extension%3Acapnp+NOT+nothack&ref=searchresults&type=Code&utf8=%E2%9C%93), though capnp was added along with a bunch of other languages in bulk in github/linguist#1714.

**Comment by sparkprime** [comment]
Ok in that case perhaps we should try.  It would definitely be useful.

**Comment by sparkprime** [comment]
Any idea how we would maintain the syntax highlighting after the fact?

**Comment by davidzchen** [comment]
Are you referring to the language-jsonnet repo that contains the Atom syntax files?

**Comment by sparkprime** [comment]
Yeah if we pushed changes to that would it all just work, or would we have to open a ticket to get it brought in.

**Comment by davidzchen** [comment]
Yes, we just need to move the contents of language-jsonnet into the repo. In my PR to Linguist, I just add the repo to .gitmodules: https://github.com/davidzchen/linguist/commit/caa74247a163f7e476163053064d3663ffc81747

**Comment by davidzchen** [comment]
By the way, do you have a preference for the color to use for Jsonnet in GitHub repository language stats?

**Comment by sparkprime** [comment]
Not really.  Is there any kind of system you know of that other languages
use?

**Comment by davidzchen** [comment]
Not in particular. It's usually pretty arbitrary, though some languages pick colors that match their logo color. Here's a sample of some of the colors used by different languages: https://github.com/ozh/github-colors

I'm currently using `#00BCD4` (cyan) in my patch.

**Comment by sparkprime** [comment]
The website is #402010 maybe we should use that.

**Comment by davidzchen** [comment]
Sounds good to me.

**Comment by sbarzowski** [comment]
Syntax highlighting for Jsonnet has been working in Github for a while now. Closing.
