### ISSUE TITLE
Optional fields in object comprehension

### ISSUE THREAD

**Issue by hausdorff** [google/jsonnet#432]
The following command outputs an error:

```bash
$ jsonnet -e "{ [if false then 'foo']: 1, for i in [1] }"
RUNTIME ERROR: field must be string, got: null
	<cmdline>:1:1-42
```

I would expect this to actually return `{}`.

Do we consider this to be a bug?

**Comment by sbarzowski** [comment]
This actually returns `{}` in Go version currently - it seemed pretty obvious to me. 

But I've just checked that the semantics explicitly disallow it, so technically C++ jsonnet behavior is correct.
efield[ei/x]↓v≠𝚗𝚞𝚕𝚕 in (object-comp) rule.

@sparkprime ?

**Comment by sparkprime** [comment]
I think my reasoning was that there's no reason to allow it because you can always put 'if blah' at the end of the composition instead of inside the [].

However it may be easier for everyone just to allow it.

**Comment by sparkprime** [comment]
Actually that's not a correct reading of the spec.  The spec says that you have n elements in the array, but only m for which the field expression 1) evaluates to a value 2) the value is not null.  Then those m become the fields of the resulting object.

So it does permit `{[null]: true for x in [1]} == {}`

Unfortunately it's also wrong in that it does not distinguish returning null from raising an error (i.e. not satisfying (1)), so it also says that` {[error "foo"]: true for x in [1]} == {}`.  That's clearly nonsense, so we have to fix the spec and the C++ implementation.

**Comment by sparkprime** [comment]
For posterity:

```
dcunnin@dcunnin7:~$ go-jsonnet -e '{[null]: true for x in [1]}'
{ }
dcunnin@dcunnin7:~$ jsonnet -e '{[null]: true for x in [1]}'
RUNTIME ERROR: field must be string, got: null
        <cmdline>:1:1-28
dcunnin@dcunnin7:~$ go-jsonnet -e '{[error "foo"]: true for x in [1]}'
RUNTIME ERROR: foo
        <cmdline>:1:3-14        $
        <builtin>       builtin function <$objectFlatMerge>
        During evaluation

dcunnin@dcunnin7:~$ jsonnet -e '{[error "foo"]: true for x in [1]}'
RUNTIME ERROR: foo
        <cmdline>:1:3-14
```

**Comment by sparkprime** [comment]
I fixed the spec, as clearly that was the highest priority ;)
