### ISSUE TITLE
Objects can't have unquoted field called "for"

### ISSUE THREAD

**Issue by benley** [google/jsonnet#446]
This breaks jsonnet:

```rb
{
  alert: "FooBroken",
  expr: "stuff",
  for: "5m",
}

## STATIC ERROR: metamon.jsonnet:6:7-9: Object comprehension can only have one field.
```
If you add quotes around "for" it works:

```rb
{
  alert: "FooBroken",
  expr: "stuff",
  "for": "5m",
}
```

**Comment by sparkprime** [comment]
Yeah this is true of all keywords

assert else error false for function if import importstr in local null tailstrict then self super true

**Comment by benley** [comment]
oh, yeah.  I figured there was a good chance this would be a Working As Intended thing.

**Comment by sparkprime** [comment]
"Soft keywords" are possible but I don't think it's worth the extra complexity :)
