### ISSUE TITLE
--{tla,ext}-code-file files don't handle relative imports

### ISSUE THREAD

**Issue by camh-** [google/jsonnet#452]
If you provide code to jsonnet via --tla-code-file or --ext-code-file, the file is read and is passed to the VM as a string. This loses the path of the file so if the the code in the file imports other files, the path of the import is not evaluated relative to the original file.

e.g.

foo/foo.jsonnet:
`import "bar/bar.jsonnet"`

foo/bar/bar.jsonnet:
`"hello"`

```
$ jsonnet foo/foo.jsonnet
"hello"

$ jsonnet --tla-code-file a=foo/foo.jsonnet -e 'function(a) a'
RUNTIME ERROR: Couldn't open import "bar/bar.jsonnet": No match locally or in the Jsonnet library paths.

$ jsonnet --tla-code a='import "foo/foo.jsonnet"' -e 'function(a) a'
"hello"
```

This affects the C++ and go versions of jsonnet.

**Comment by sbarzowski** [comment]
Workaround: Use `-J foo/` to add `foo/` to searched paths.

**Comment by camh-** [comment]
Yeah, that's the workaround I've always had but didn't figure out why I needed it until now. I am now using --tla-code 'var=import "file"' as the workaround which works better for my use case.

**Comment by sparkprime** [comment]
The filename is set here for external vars https://github.com/google/jsonnet/blob/master/core/vm.cpp#L1218 and here for top level args: https://github.com/google/jsonnet/blob/master/core/desugarer.cpp#L923

The bigger problem is that the API does not require the client to pass through the filename: https://github.com/google/jsonnet/blob/master/include/libjsonnet.h#L186

**Comment by camh-** [comment]
It makes sense to not require a filename in the API - the code may not come from a file at all.

Perhaps "--tla-code-file var=filename" (and ext-code-file) could be turned into 'import "filename"' instead of reading the file. That way it is lazily read too. Probably also makes sense for tla-str-file (and ext-str-file) to be 'importstr "filename"'

**Comment by sparkprime** [comment]
Yeah I'd be fine with that. The code is in cmd/jsonnet.cpp and jsonnet/cmd.go in that case.  It's a bit different to the snippet vs file stuff but that's fine.
