### ISSUE TITLE
Add upper/lower case functions to stdlib

### ISSUE THREAD

**Issue by jlewi** [google/jsonnet#453]
It would be useful to have functions in stdlib to change the case of a string to all upper or all lower.

**Comment by jlewi** [comment]
FWIW this is what I came up with

```
       upper:: function(x) {
		local cp(c) = std.codepoint(c),
		local upLetter(c) = if cp(c) >= 97 && cp(c) < 123 then 
			std.char(cp(c) - 32) 
			else c,
		result:: std.join("", std.map(upLetter, std.stringChars(x))),
	}.result,
```

**Comment by sparkprime** [comment]
In general this is really hard because of all the different languages in unicode.  Usually you would link a library like ICU to do it, which has all of the tables defined.  We could certainly add an ASCII-only version though like what you have done here.

Some small improvements in your code:

```
       upper(x)::
		local cp = std.codepoint;
		local upLetter(c) = if cp(c) >= 97 && cp(c) < 123 then 
			std.char(cp(c) - 32) 
			else c;
		std.join("", std.map(upLetter, std.stringChars(x))),
```

**Comment by sbarzowski** [comment]
maybe we could call it asciiUpper, then...

**Comment by sparkprime** [comment]
yes
