### ISSUE TITLE
Add AppVeyor builds

### ISSUE THREAD

**Issue by marcelocantos** [google/jsonnet#469]
Getting a Windows binary is a PITA for many users. It would be quite useful to build and publish a Windows exe, using AppVeyor, as part of each release.

**Comment by marcelocantos** [comment]
I've gotten AppVeyor builds roughly working ([branch](https://github.com/marcelocantos/jsonnet/tree/appveyor), [release](https://github.com/marcelocantos/jsonnet/releases)). As per the go-jsonnet variant https://github.com/google/go-jsonnet/pull/206, it'll need an AppVeyor auth token owned by a jsonnet maintainer.

**Comment by sparkprime** [comment]
This is a github api token encrypted via appveyor's web app, is that what you need?
```
environment:
  my_variable:
    secure: 01ia4TetCWEiBYMfHXfIZhP0hm58gov1Nnbj4DHnMSgqY0r1209z9mH5guCP0hdj
```
