### ISSUE TITLE
Arithmetic operators allow manifesting NaN 

### ISSUE THREAD

**Issue by dhaffey** [google/jsonnet#47]
$ jsonnet -e '1e309 - 1e309'
    -nan

**Comment by sparkprime** [comment]
I think you need #2 to get the behavior you're looking for?

**Comment by dhaffey** [comment]
The spec mentioned "floating-point arithmetic", so I'd already assumed IEEE doubles. It's more an issue of consistently handling special float values and avoiding invalid JSON output (eg, "1 / 0" sensibly produces an error rather than manifesting "inf").

Switching to arbitrary-precision rationals would certainly do the trick. Though std.sin and friends may get a little trickier to implement :)

**Comment by dhaffey** [comment]
On a related note:

    $ jsonnet -e 1e309
    inf

**Comment by sparkprime** [comment]
Ah yes, I had forgotten that JSON does not allow these values.  So the question is, should they generate errors whenever they appear as immediate values (fail fast) or should there only be an error if they reach manifestation time.  It seems to me that the latter behavior will be quite annoying.  The NaN / inf will propagate through values and it will be hard to know where it originally came from.  I can't think of any compelling use cases for allowing NaN and inf in a config language.

**Comment by dhaffey** [comment]
+1 for failing fast. NaN is an atrocity, and the best argument I can think of for allowing an intermediate inf is that it's occasionally convenient as an initial value in algorithms like computing a minimum. Not very compelling.
