### ISSUE TITLE
Allow partial evaluation for external variables

### ISSUE THREAD

**Issue by ceridwen** [google/jsonnet#478]
This is a feature request.  I'm calling the Python library to evaluate jsonnet that I'm then passing to the Kubernetes API, injecting randomly-generated labels and other kinds of state from Python using std.extVar().  Because the state doesn't all become available at the same time, it makes sense to evaluate variables at different points during execution, but currently jsonnet evaluation is once and done.  Instead, I'm looking at creating a Python object that holds a mapping of external variables that's evaluated at the final step, directly replacing std.extVar() calls of the right form and then passing the resulting string to jsonnet, or generating jsonnet code at run time and placing it into a file that other jsonnet files import, but these are all kludges.  Because jsonnet is a pure functional language, partial evaluation should be straightforward to implement.  (If I'm wrong about that, please tell me.)

**Comment by sbarzowski** [comment]
Thanks for the suggestion.

Could you provide example code using the proposed feature? This could clarify things a lot.

**Comment by sparkprime** [comment]
It sounds like you need to interleave Jsonnet execution with external execution.  Is that right?  And can you motivate that a bit with more context?

**Comment by sparkprime** [comment]
Some people in the past have needed UUIDs but I think the best way to support that is to return some strings from Jsonnet (generated from the names of things you're building) and have some post-pass turn those unique strings into unique IDs, perhaps injecting a timestamp or randomness as needed to make these UUIDs unique against other runs of Jsonnet.

**Comment by ceridwen** [comment]
For anyone who doesn't know Kubernetes: Kubernetes's fundamental unit is something called a resource, which comes in many different kinds.  Resources can have metadata assigned to them as key-value pairs or things called selectors that operate on the metadata.  A simplified example of the situation I'm dealing with:

```
{
    "kind": "Pod",
    "metadata": {
        "labels": {"foo": std.extVar("foo"),
                       "bar": std.extVar("bar")}
    }
}
```

Here, the labels `foo` and `bar` need to be instantiated at different times: `foo` is global and the same for all resources that belong to a given collection, but "bar" is generated later because it needs to be coordinated with a selector on another resource:

```
{
    "kind": "NetworkPolicy",
    "metadata": {
        "labels": {"foo": std.extVar("foo")
    }
    "spec": {
        "podSelector": {
            "matchLabels": {
                "bar": std.extVar("bar")
            }
        },
}
```

I'd like to be able to partially evaluate the first resource with `jsonnet -V "foo=793048c9-6e1b-405b-aaed-64afdfde3c77"` and get back,

```
{
    "kind": "Pod",
    "metadata": {
        "labels": {"foo": "793048c9-6e1b-405b-aaed-64afdfde3c77",
                       "bar": std.extVar("bar")}
}
```

In the real code there's potentially a lot more indirection because the external variables end being passed to functions that compose larger objects from smaller ones.  Because many of these smaller objects end up being reused in multiple places in the same final object, generating unique strings takes including the whole path to the subobject, which isn't any easier (IMO) than some of the other workarounds I mentioned in my first post.

**Comment by sbarzowski** [comment]
Ok, from what I see the proposal is to support basic symbolic evaluation. And I think this is quite tricky.

We would need to choose where unknowns block further evaluation (arithemetic, `if` condition,...) and where they don't (fields of objects literals, arguments of user-defined functions, ...). For example it's hard to know what `std.extVar('unknown')  + std.extVar('unknown')` is, but you can tell that `(function(x) {a: x})(std.extVar('unknown'))` is just `{a: std.extVar('unknown')}`. 

It gets problematic with builtins - they require actual values. If we made all builtins block evaluation and all user-defined function get expanded, it would expose implementation details. We would need to think hard about how it affects compatibility. I'm also slightly worried about how it could affect performance (especially how hard it would be to reason about the performance of symbolic evaluation).

That said, I think the use case is interesting and we should dig deeper into it. It sounds like something that we should have a good answer to.

**Comment by sbarzowski** [comment]
@ceridwen Do I understand correctly that the intention is to:
1) Run jsonnet on initially available data ("foo"). Get result A.
2) Extract some data from A, do some (impure) computations outside of jsonnet, get data B ("bar").
3) Provide B to jsonnet. Get final result.

**Comment by sparkprime** [comment]
Partial execution would massively increase the complexity of the interpreter, and one of the design goals of Jsonnet was to be simple.  There must be a better way of achieving what you need.

Can you go into more detail about "but "bar" is generated later because it needs to be coordinated with a selector on another resource:"

Also, is it not possible to leave placeholders in the generated config that are then handled by a small post pass?

**Comment by ceridwen** [comment]
It sounds like this is probably too hard based on what you've said about jsonnet internals.  If there's another way to do it, I'm curious.

@sbarzowski, Yes, that's correct.

@sparkprime, To outline the situation in something closer to its fuller complexity:

There's another system adjoining Kubernetes that uses annotations on resources to embed metadata for its use.  The annotations need to contain unique identifiers, which in this case the Python controller creates.  These identifiers need to be sent to both the other system and Kubernetes.  For separations-of-concerns reasons, I'd prefer for this part of the controller not to need to know a lot of details about the Kubernetes-specific code.

The Kubernetes resources also have relationships that need to be calculated.  For instance, I need to either generate or let Kubernetes generate (using the generateName field) the names of namespaces to put other resources in.  (Letting Kubernetes do it here works better because if Kubernetes can't assign a unique name, it will raise an error, whereas if the controller does it, the controller also has to check for uniqueness and that's subject to race conditions if two controllers are independently creating resources at the same time).  Likewise, I need to add unique labels to Deployments, Services, and Network Policies so that otherwise-identical copies of resources can only talk to the corresponding members of their own groups.

I don't know how to do make generated placeholders work easily.  A lot of resources have repeated elements that are best generated by functions:

```
{
    "kind": "NetworkPolicy",
    "spec": {
        "ingress": [
	    rule(std.extVar('label1'), 'TCP', 5555),
	    rule(std.extVar('label2'), 'TCP', 5555),
        ]
}
```

Here the extVar calls are used by the controller to assign unique values for those labels.  I'd believe there's some way to make those two function calls return different things, but it's not obvious to me how.

**Comment by sparkprime** [comment]
So these are two separate use cases, right?

1) Embed a unique identifier deep in each component of a config, so that they can be distinguished.

2) The naturally unhermetic need to invent names that do not already exist.

For (1) you can pass enough context into each Jsonnet template / function to construct unique names.  These names might get very long, but you can condense them back down to short strings in a functional way (inside or outside Jsonnet).  We have a proposal to add some syntax sugar to help with the generation of names, so you don't have to repeat "foo" here:

```
{
    foo: MyThing("foo") { ... },
}
```

Instead you do something like this, where `here` evaluates to the closest field string (syntax TBD):

```
{
    foo: MyThing(here) { ... },
}
```

For (2) there are many systems that have this problem.  In some cases (e.g. AWS) you need to know the generated id of a thing before you can refer to it when creating another thing.  This affects the config language of AWS Cloud Formation in that it needs to interleave config elaboration and deployment actions, which makes a hermetic layer impossible.  The best answer I have to that, is to have some minimal layer that wires everything up after the fact.  It is possible to use Terraform & AWS CF in this way, by making minimal use of their inbuilt config languages to do the post-hoc wiring, and doing everything else in Jsonnet.

**Comment by ceridwen** [comment]
That's fair enough.  My current plan is still to use external variables to do the post-hoc wiring, because (at least with jsonnet's current syntax) generating unique names looks like it would require boilerplate in the jsonnet files and care on the part of the person writing the jsonnet files.
