### ISSUE TITLE
std.parseJson

### ISSUE THREAD

**Issue by jwise** [google/jsonnet#479]
I have recently found myself with cause to parse some ill-formed partial JSON -- a library that we are incrementally converting to Jsonnet was originally parsed by the C preprocessor, and had files like this:

`main.jh`:
```
{
  "unit_1": {
#include "unit_1.jh"
  },
  "unit_2": {
#include "unit_2.jh
  },
  ...
}
```

`unit_1.jh`:
```
  "out": {
    ... data ...
  }
```

I'd like to be able to load a `unit_1.jh` directly into Jsonnet without invoking an external pass.  Obviously, I can't hand it to `import`, since it's ill-formed.  `importstr` can load it so that I can do extra work on it, but once I have a string, I can't convert it to an object.  Really, I'd like to be able to do something like:

`eval ("{" + importstr "unit_1.jh" + "}")`

Or, even better,

`local importjh(f) = eval("{" + importstr f + "}")`

though that would require changes along the lines of #196, too.

This is closely related to #460, but maybe more general.  One key difference is that #460 wants to be "safe"; in this case, "everybody knows" that any time you type "`eval`", you deserve whatever happens next :smile: We intend to use this only on trusted JSON databases.

**Comment by sbarzowski** [comment]
If `unit_1.jh` is json without outer braces, `parseJson` (mentioned in #196) would be enough. Or is there some reason to treat it as jsonnet?

**Comment by sparkprime** [comment]
Yeah I had that thought too.

**Comment by jwise** [comment]
`parseJson` would be okay too, but I imagine that `eval` is probably lower effort to implement -- and works equally well for my application (trusted input).

**Comment by sparkprime** [comment]
`eval` is easy to implement but 1) code using it is hard to read 2) any language forcing you to use it for trivial things probably isn't very good.  `parseJson` seems to come up fairly frequently though.

**Comment by glerchundi** [comment]
Any update on this? Would love to see this implemented!

**Comment by glerchundi** [comment]
Good to hear, thanks for the update!

**Comment by sparkprime** [comment]
I think vendoring a small json parser into the C++ implementation would be reasonable.

**Comment by sbarzowski** [comment]
I think we can close it now (https://github.com/google/jsonnet/commit/06c1ce1e6ac65f3c34960ee02b720c4772b17a84).
