### ISSUE TITLE
More simple JSON with comments

### ISSUE THREAD

**Issue by spmbt** [google/jsonnet#48]
I develop jsonComm format with comments in JS or Yaml style.
https://github.com/spmbt/jsonComm
It need mach more simple code for coding and decoding (2 KBytes in JS only).

**Comment by sparkprime** [comment]
Thanks for the heads up.  Jsonnet differs in being a full programming language, and therefore has a lot more features beyond comments.  That is why it needs more code :)

**Comment by spmbt** [comment]
Of course, we are understand it. But one more language and technology is not always is good :) For example, Yaml has a lot of rules, and this leads to the fact that many developers use  subset of features. JSON: we had 1 simple technology. Jsonnet - 1 complex and 1 preprocessor language for static calculations.
