### ISSUE TITLE
Python bindings don't accept a MappingProxy object in place of a dict

### ISSUE THREAD

**Issue by ceridwen** [google/jsonnet#486]
I have jsonnet code with a top-level function.  When I run `jsonnet.evaluate_snippet('', code, tla_vars=variables)` with variables as a MappingProxy object (`types.MappingProxyType`), I get a RuntimeError telling me that one of the parameters was not bound in the call.  Do tla_vars and ext_vars work with anything other than dicts?  The work-around is straightforward, the type has a copy() method that creates a dict, but this was a surprising failure of duck-typing.

**Comment by sparkprime** [comment]
So what specifically is happening here is that `PyArg_ParseTupleAndKeywords` is used to bind the argument to a PyObject* on the C side.  The type is allowed to be anything at that point.  Then, the following code iterates over the given PyObject as if it were a dict.  I assumed that if it had iteritems(), it would satisfy this:

https://github.com/google/jsonnet/blob/master/python/_jsonnet.c#L278

**Comment by sparkprime** [comment]
It's possible we could modify that code to test if the type is a dict, and if not, call Copy()?  But it'd be interesting to know why types.MappingProxyType cannot be iterated over with that existing C code.

**Comment by sparkprime** [comment]
Did you build the _jsonnet.so module for Python3 or Python 2.7?

**Comment by ceridwen** [comment]
I can't say in general (it's certainly easy to break duck-typing with the Python C API), but in my experience, I expect it to work, particularly for types in the standard library.  MappingProxyType in particular has been around since Python 2 and was exposed in Python 3 as Guido's answer to the problem of not having an immutable mapping type.  It's implemented in C, IIRC, which may be the problem?  At the Python level MappingProxyType doesn't have iteritems() in Python 3.  I don't know off the top of my head at the C level.

I installed the jsonnet Python bindings using Python3's pip, so it ought to have compiled it for Python 3.  The file name is `_jsonnet.cpython-36m-darwin.so`, which suggests yes.

**Comment by sparkprime** [comment]
If it doesn't have iteritems then it doesn't quack like a duck :)

**Comment by ceridwen** [comment]
Nothing in Python 3 has iteritems() at the Python level, though, since items() returns an iterator.  Are the C-level functions still called iteritems() in Python 3?

**Comment by ceridwen** [comment]
I looked through the code and documentation for dict objects in [Python 2](https://docs.python.org/2.7/c-api/dict.html) and [3](https://docs.python.org/3/c-api/dict.html) and couldn't find iteritems or functions with similar names.  What exactly is jsonnet calling?

**Comment by sparkprime** [comment]
It just calls this, but I'm not sure what that does on non-dicts:  https://docs.python.org/3.2/c-api/dict.html#PyDict_Next

**Comment by sbarzowski** [comment]
I'm going to close this now. If there is any remaining issue feel free to reopen.
