### ISSUE TITLE
Unexpected fmt behavior if jsonnet code is commented

### ISSUE THREAD

**Issue by ahakanbaba** [google/jsonnet#488]
We see this at `jsonnet fmt -n 4 --string-style l`  output

```
{
    resources: {
        // TODO add limits
        //                limits: {
        //                    cpu: "0.002",
        //                    memory: "20Mi",
        //                },
    },
}
```

Can the fmt be confused between code and comment in this example ?

**Comment by sbarzowski** [comment]
jsonnet formatter doesn't care what is inside the comments. It treats them like an opaque string of characters. It will not modify the contents of the comments.  So it is going to indent one-line comments to the current indentation level.  If you add `//` before the indentation when commenting out some code, it will end up with "double indentation" as in your example.

**Comment by ahakanbaba** [comment]
ok I see what you mean 

this : 
```
{
    resources: {
        // TODO add limits
                       // limits: {
                           // cpu: "0.002",
                           // memory: "20Mi",
                       // },
    },
}
```

gets formatted into this 
```
{
    resources: {
        // TODO add limits
        // limits: {
        // cpu: "0.002",
        // memory: "20Mi",
        // },
    },
}
```

Which looks nice.
Adding the comment before the indentation threw me off.
