### ISSUE TITLE
terminate called after throwing an instance of 'std::ios_base::failure'

### ISSUE THREAD

**Issue by loverszhaokai** [google/jsonnet#49]
`$ ls folder`
input.jsonnet
`$ cat folder/input.jsonnet`
```
import "" {
    cocktails +: {
        "Whiskey Sour": {
            ingredients: [
                { kind: "Scotch", qty: 1.5 },
                { kind: "Lemon Juice", qty: 0.75 },
            ],
            garnish: "Lemon Peel",
            served: "On The Rocks",
        }
    }
}
```
`$ ../jsonnet folder/input.jsonnet`
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_filebuf::underflow error reading the file
**Aborted**

**Comment by sparkprime** [comment]
Good catch.  I'm adding explicit checks for importing the empty strings and directories.  But you can still import "." which I can't detect is a directory in standard C++.  So I'll just turn the IO error into a Jsonnet runtime error:

$ jsonnet -e 'import ""'
RUNTIME ERROR: Couldn't open import "": The empty string is not a valid filename
        <cmdline>:1:1-9
$ jsonnet -e 'import "."'
RUNTIME ERROR: Couldn't open import ".": basic_filebuf::underflow error reading the file
        <cmdline>:1:1-10
$ jsonnet -e 'import "/"'
RUNTIME ERROR: Couldn't open import "/": Attempted to import a directory
        <cmdline>:1:1-10

Hopefully that's good enough.
