### ISSUE TITLE
setMember does not find entries after the first entry

### ISSUE THREAD

**Issue by ahakanbaba** [google/jsonnet#492]
This 

```
{
    metadata: {
        a: if std.setMember("a", ["k", "b", "a", "b"]) then "yes" else "no",
        b: if std.setMember("b", ["k", "b", "a", "b"]) then "yes" else "no",
        k: if std.setMember("k", ["k", "b", "a", "b"]) then "yes" else "no",
    },
}
```

Prints 

```
{
   "metadata": {
      "a": "no",
      "b": "no",
      "k": "yes"
   }
}

```

As a workaround one can use something like the following

`contains(arr, val):: if std.count(arr, val) == 0 then false else true,`

Looking at the tests 
https://github.com/google/jsonnet/blob/master/test_suite/stdlib.jsonnet#L373

This scenario does not look like covered. .

**Comment by sparkprime** [comment]
yeah a set by definition is an ordered list, which is a bit weird but there's no set in JSON.  You can make a set from an arbitrary list with std.set().

**Comment by ahakanbaba** [comment]
Ohhh I see. 
The documentation mentions it at the top of the set block 

> Sets are represented as ordered arrays without duplicates.
