### ISSUE TITLE
Serve jsonnet.org over TLS

### ISSUE THREAD

**Issue by danderson** [google/jsonnet#500]
The jsonnet website is currently being served from github. Adding `https` to the URL results in a certificate error, because the cert is for github.com. It'd be nice if jsonnet.org were served securely.

If github cannot do this, I can suggest https://netlify.com . It's trivial to autodeploy from git, run on a custom domain name (e.g. https://metallb.universe.tf), and has a one-click integration with Let's Encrypt for TLS.

**Comment by sparkprime** [comment]
I've had a request internally to use HTTPS and HSTS, and to do it via Google Cloud Platform.  It's being tracked on an internal bug but I'll update here when it's done.

**Comment by lukegb** [comment]
FYI: GitHub has rolled out support for Let's Encrypt certificates and has automatically issued them for custom domains on GitHub Pages, so this is now "solved".

Consider repurposing (and renaming) this bug to track the effort to move the documentation to GCP?

**Comment by sparkprime** [comment]
Yes and we're now using it :) I'd rather not host it outside of gh-pages as possible.  I'm going to close this bug.
