### ISSUE TITLE
Wrong link to articles/design.html in doc/learning/tutorial.html

### ISSUE THREAD

**Issue by filippog** [google/jsonnet#501]
Hi,

In https://github.com/google/jsonnet/blob/cd22b4e75beee2388026359c3daa7b1d5934f7c8/doc/learning/tutorial.html#L506 the link is to `articles/design.html` though when browsing the page at http://jsonnet.org/learning/tutorial.html the link results in a 404 linking to http://jsonnet.org/learning/articles/design.html

**Comment by sparkprime** [comment]
Thanks for the report
