### ISSUE TITLE
formatting breaks compilation with assignment and $

### ISSUE THREAD

**Issue by ahakanbaba** [google/jsonnet#503]
Consider the following code 

```
{
    defaultVariable:: "default",
    metadata(p= $.defaultVariable):: {
    },
}
```

Which compiles fine 

```
$ jsonnet  test.jsonnet
{ }

```

Running fmt on it makes it look like this 
`$ jsonnet fmt -i test.jsonnet`

```
{
  defaultVariable:: 'default',
  metadata(p=$.defaultVariable):: {
  },
}
```
Note that the space around the assignment of the default parameter value has been removed. 
Now compiling again results in a compilation error 

```
$ jsonnet  test.jsonnet
STATIC ERROR: test.jsonnet:3:13-15: not a binary operator: =$
```

As a workaround one can re-write this like the following which compiles fine 

```
{
  defaultVariable:: 'default',
  metadata(p=
  $.defaultVariable):: {
  },
}
```

**Comment by ahakanbaba** [comment]
If you also agree that this is a bug, I think I can help adding the fix. However it would be great to discuss how this should be fixed. 

Making the fmt put spaces around default value assignments may be one approach. 
For example

```
{
  defaultVariable:: 'default',
  metadata(p = $.defaultVariable, k = "a"):: {
  },
}
```

Alternatively, we could make fmt change the formatting if `$.` gets involved. 

Or maybe I am missing some piece of documentation and this is expected. 
On the other hand,  I would not expect fmt to break compilation no matter the circumstances.

**Comment by sbarzowski** [comment]
This is definitely a bug. Reformatting should never ever change the result.

It is primarily a lexer issue. IMO `=$` should not be treated as an operator. I don't see any reason to allow including `$` in operators at all.

**Comment by sparkprime** [comment]
Or just `($)`, or you can insert a `/* comment */` to separate them.

I think the most consistent change we can make is to change this rule:

> If the sequence has more than one character, it is not allowed to end in any of `+-~!`

to

> If the sequence has more than one character, it is not allowed to end in any of `+-~!$`

That will cause p=$ to parse correctly.

It will also mean we can remove this special case I think:
https://github.com/google/jsonnet/blob/master/core/formatter.cpp#L598
