### ISSUE TITLE
Add user home directory lookup function to stdlib.

### ISSUE THREAD

**Issue by josdotso** [google/jsonnet#508]
Not all hosts set `$HOME`, so it would be nice to have a function for this.

**Comment by kardianos** [comment]
$HOME doesn't have a meaning on all systems. If calling from Go, I would recommend using user.CurrentUser to then injecting that as a standard HOME variable.

**Comment by sparkprime** [comment]
This would violate hermiticity, you must set it at the commandline with `jsonnet --ext-str HOME` or `jsonnet -tla-str HOME`.  If you don't have it in an environment variable, you can use `HOME=%HOME%` or whatever is appropriate.

**Comment by sbarzowski** [comment]
Closing, see the comment above.
