### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [google/jsonnet#51]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [jsonnet_evaluate_snippet_aux](https://github.com/google/jsonnet/blob/85766f077110b1056fc0cd776154bab9b7831a74/libjsonnet.cpp#L148)
- [jsonnet_realloc](https://github.com/google/jsonnet/blob/85766f077110b1056fc0cd776154bab9b7831a74/libjsonnet.cpp#L264 "Memory reallocation") ⇒ [from_string](https://github.com/google/jsonnet/blob/85766f077110b1056fc0cd776154bab9b7831a74/libjsonnet.cpp#L33)

**Comment by sparkprime** [comment]
Yes that's needed.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/google/jsonnet/commit/2b83ce57a10de7b7c302b9754d70cbf1206b97c6 "Better error handling").
