### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [google/jsonnet#53]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/google/jsonnet/blob/a6b18fc485233e86db953a658e6c68371d296e2e/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](http://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by davidzchen** [comment]
It would be great to add a [Bazel](http://bazel.io) BUILD file as well.

**Comment by benley** [comment]
autotools is such a weird thing to set up, but I've gotten a decent start on it now.

**Comment by sparkprime** [comment]
I've studiously avoided autotools for 2 decades but I suppose I won't get away with it anymore ;)

**Comment by benley** [comment]
At least it ought to be fairly low-maintenance once it's set up :-)

**Comment by johnbartholomew** [comment]
Going through old issues. Jsonnet has had a Bazel build since #63 (2015) and a CMake build since #303 (2017).

**Comment by elfring** [comment]
Thanks for the improved development tool support.
