### ISSUE TITLE
std.strReplace max stack frames exceeded

### ISSUE THREAD

**Issue by Globegitter** [google/jsonnet#531]
I am trying to import this file: https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended and output it as a multiline json string (without visible \n), not succeeding with it and on the way seemed to have stumbled on a bug. I am passing it in via `-ext-str-file modsecurity_conf=modsecurity.conf` and in my jsonnet file have 

```
local modsecurityConf = std.extVar("modsecurity_conf");

local test = std.strReplace(modsecurityConf, 'engine', 'something');
....
local config = {
  data: {
    "modsecurity.conf": test,
  }
};
...
{
  items: [
    config,
  ],
}
```

I get the following error:

```
RUNTIME ERROR: max stack frames exceeded.
	std.jsonnet:174:15-23	object <invar>
	std.jsonnet:195:16-26	thunk <a>
	std.jsonnet:195:16-38	function <anonymous>
	std.jsonnet:195:16-38	thunk <slice>
	std.jsonnet:190:15-20	thunk <slice>
	std.jsonnet:(188:11)-(194:12)	function <build>
	std.jsonnet:(188:11)-(194:12)	function <build>
	std.jsonnet:195:7-68	function <anonymous>
	std.jsonnet:119:25-44	thunk <a>
	std.jsonnet:119:25-52	function <anonymous>
	...
	./common/jsonnet/k8s.libsonnet:276:28-50	thunk <a>
	./common/jsonnet/k8s.libsonnet:276:28-62	function <anonymous>
	./common/jsonnet/k8s.libsonnet:276:28-62	thunk <nonstrings>
	./common/jsonnet/k8s.libsonnet:277:23-33	
	./common/jsonnet/k8s.libsonnet:277:12-34	thunk <a>
	./common/jsonnet/k8s.libsonnet:277:12-39	function <anonymous>
	./common/jsonnet/k8s.libsonnet:277:12-39	thunk <object_assert>
	path/to/config.jsonnet:93:5-11	thunk <array_element>
	path/to/config.jsonnet:(91:10)-(96:4)	object <anonymous>
	During manifestation	
```

The example above is slightly simplified but should show off the case. I have no idea why this happens.

**Comment by Globegitter** [comment]
Ahh, I see the current implementation is in jsonnet and is recursive so reaches max stack frame on a long string. I guess implementing it natively would solve the issue.

**Comment by sparkprime** [comment]
It's missing tailstrict in the recursive calls, that's how you avoid stack smash in lazy functional languages:

```
        replace_after(new_index, new_index, acc + str[start_index:curr_index] + to) tailstrict
      else
        replace_after(start_index, curr_index + 1, acc) tailstrict;
```

**Comment by sparkprime** [comment]
Can you try adding those 2 keywords, rebuild the jsonnet executable and see if it fixes it

**Comment by Globegitter** [comment]
ah yes, that fixes it indeed. Should I submit a PR for it?

**Comment by sparkprime** [comment]
Yes please!
