### ISSUE TITLE
how to properly generate yaml files?

### ISSUE THREAD

**Issue by ZihanTang** [google/jsonnet#544]
Hi there, I got troubles while making yaml example to work. I followed example here(https://jsonnet.org/ref/stdlib.html) and got a yaml.jsonnet file as bellow.
``` bash
xhdeMacBook-Air-5:envs xh$ cat yaml.jsonnet
std.manifestYamlDoc(
{
    x: [1, 2, 3, true, false, null,
        "string\nstring\n"],
    y: { a: 1, b: 2, c: [1, 2] },
})
```
Then I used jsonnet to generate yaml file with following result.
```
xhdeMacBook-Air-5:envs xh$ jsonnet yaml.jsonnet
"\"x\": \n- 1\n- 2\n- 3\n- true\n- false\n- null\n- |\n  string\n  string\n\"y\": \n  \"a\": 1\n  \"b\": 2\n  \"c\": \n  - 1\n  - 2"
```
However, the expected result should be something like 
```
"x": 
  - 1
  - 2
  - 3
  - true
  - false
  - null
  - |
    string
    string
"y": 
  "a": 1
  "b": 2
  "c": 
    - 1
    - 2
```
My environment is 
- Mac OSX: 10.12.6
- Jsonnet: version v0.11.2 from brew

Can I have some suggestions to make it work?

**Comment by ZihanTang** [comment]
I figured out that I should use -S command to generate plaintext.
```
xhdeMacBook-Air-5:envs xh$ jsonnet -S backend-env.jsonnet
"x":
- 1
- 2
- 3
- true
- false
- null
- |
  string
  string
"y":
  "a": 1
  "b": 2
  "c":
  - 1
  - 2
```
However, how to combine this output with `-m` option?

**Comment by sparkprime** [comment]
With -m and -S, the content of every file in the dict will be expected to be a string.  If you have some that are plain JSON, you can use std.manifestJson(foo) to turn them into a string.

**Comment by sparkprime** [comment]
Or std.toString(foo) for that matter.

**Comment by ZihanTang** [comment]
Thank you for quick response. Instead of `jsonnet -mS . yaml.jsonnet`, I should use `jsonnet -m . yaml.jsonnet -S`. It worked well and I'll close this one.
