### ISSUE TITLE
Typing inconsistency/error with imported functions

### ISSUE THREAD

**Issue by bshi** [google/jsonnet#552]
`arr.jsonnet`:
```
local lib = 'import arr.libsonnet';
{
  works: lib.F([1, 2, 3]) + [12, 1]
}
```
`arr.libsonnet`
```
{
  F(a):: a,
}
```

`works.jsonnet`:
```
local lib = {
  F(a):: a,
};
{
  works: lib.F([1, 2, 3]) + [12, 1]
}
```

I would expect works.jsonnet to be functionally identical to arr.jsonnet but one errors out:  

```
bshi@bshi:~$ jsonnet --version
Jsonnet commandline interpreter v0.11.2

bshi@bshi:~$ jsonnet arr.jsonnet
RUNTIME ERROR: string index must be a number, got string.
	arr.jsonnet:3:16-21	object <anonymous>
	During manifestation	
```
```
bshi@bshi:~$ jsonnet works.jsonnet
{
   "works": [
      1,
      2,
      3,
      12,
      1
   ]
}
```

**Comment by sbarzowski** [comment]
@bshi Take a look at the first line: `local lib = 'import arr.libsonnet';` Look at where you put `'`. The variable `lib` in `arr.jsonnet` is not the imported thing, but the string "import arr.libsonnet". Hence the error.

**Comment by bshi** [comment]
Gah!  Thanks @sbarzowski & sorry for the noise.
