### ISSUE TITLE
SSL on jsonnet.org has expired

### ISSUE THREAD

**Issue by gytisgreitai** [google/jsonnet#556]
Issued by: Let's Encrypt Authority X3
Expired: Tuesday, 2 October 2018 at 02:21:41 Eastern European Summer Time

**Comment by sbarzowski** [comment]
@sparkprime

**Comment by sparkprime** [comment]
This is due to a change in DNS configuration on the Google side (the site itself is hosted by Github, which also registers the certificates).  It's currently being looked at.

**Comment by sbarzowski** [comment]
It seems to be good now. Can we close?
