### ISSUE TITLE
std.escapeStringJson escapes ~ as if it was unicode

### ISSUE THREAD

**Issue by lihaoyi-databricks** [google/jsonnet#557]
```bash
$ cat foo.jsonnet
std.escapeStringJson("~")

$ jsonnet foo.jsonnet
"\"\\u007e\""
```

I'd expect `~` to be left untouched, since it plays no role in any JSON syntax and doesn't affect quoting or escaping at all

**Comment by sparkprime** [comment]
I believe it is intended to find all control characters. 159 is 9f here: https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)

126 should definitely not be included in that range, since it is printable.
