### ISSUE TITLE
Hello, I have achieved support for PHP.

### ISSUE THREAD

**Issue by Neeke** [google/jsonnet#58]
JsonNet for PHP :  http://pecl.php.net/package/jsonnet

git:   https://github.com/Neeke/JsonNet

**Comment by sparkprime** [comment]
Very cool.  I should maintain a list of these integrations on the website.

**Comment by sparkprime** [comment]
By the way if you call it JsonNet as opposed to Jsonnet, people will be more likely to confuse it with JSON.NET which is a different project.

**Comment by Neeke** [comment]
all right, it will be named JsonNet-PHP.
It's ok?

**Comment by sparkprime** [comment]
How about Jsonnet-PHP :)

**Comment by Neeke** [comment]
yeah, cool.

**Comment by Neeke** [comment]
Hi, done.

https://github.com/Neeke/Jsonnet-PHP

**Comment by sparkprime** [comment]
Thanks.

I have created a list of these 3rd party integrations here https://google.github.io/jsonnet/doc/bindings.html
