### ISSUE TITLE
RFE: (std.sortFn) sort function that accepts a function, result of function is what is evaluated for sorting

### ISSUE THREAD

**Issue by ghostsquad** [google/jsonnet#583]
It would be nice to be able to sort based on an arbitrary function. Example use case:
```
{
  foos: [
    { foo: 3 },
    { foo: 1 },
    { foo: 2 },
  ],

  sorted: std.sortFn(function(f) f.foo, $.foos),
}
```
expected result:
```
sorted: [
  { foo: 1 },
  { foo: 2 },
  { foo: 3 },
]
```

**Comment by seh** [comment]
You're in luck: It's already there, as [the second parameter to `std.sort`](https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet#L1093).

This came up recently [in the "ksonnet" channel](https://kubernetes.slack.com/archives/C6JLE4L9X/p1543368494217000?thread_ts=1543364503.216000&cid=C6JLE4L9X) of the "Kubernetes" Slack team.

**Comment by sbarzowski** [comment]
It's not mentioned in the docs (https://jsonnet.org/ref/stdlib.html#sort)), though. We should add it.

**Comment by ghostsquad** [comment]
Ah, ya, the docs don't mention it. So I had no idea!

**Comment by sbarzowski** [comment]
It's documented for some time now (thanks to @redbaron). I'm going to close this issue.
