### ISSUE TITLE
std.join ignores empty string as first entry

### ISSUE THREAD

**Issue by gregory-lyons** [google/jsonnet#588]
This is a behavior change from v0.11.2 to v0.12.0.

Previously, `std.join` would recognize empty string as a valid first entry and would add a leading delimiter to the output:
```
glyons@mbp-005245 jsonnet-0.11.2 $ ./jsonnet -v
Jsonnet commandline interpreter v0.11.2
glyons@mbp-005245 jsonnet-0.11.2 $ ./jsonnet -e 'std.join("_", ["", "test"])'
"_test"
```

Now, `std.join` ignores a first entry of empty string and does not add a leading delimiter. It does appear to recognize empty string as long as it isn't the first entry:
```
glyons@mbp-005245 jsonnet-0.12.0 $ ./jsonnet -v
Jsonnet commandline interpreter v0.12.0
glyons@mbp-005245 jsonnet-0.12.0 $ ./jsonnet -e 'std.join("_", ["", "test"])'
"test"
glyons@mbp-005245 jsonnet-0.12.0 $ ./jsonnet -e 'std.join("_", ["", "test", ""])'
"test_"
glyons@mbp-005245 jsonnet-0.12.0 $ ./jsonnet -e 'std.join("_", ["", "test", "", "test2"])'
"test__test2"
```

Correct me if I'm wrong, but I don't think this change was expected nor announced.

**Comment by sparkprime** [comment]
Yes this is not intentional

**Comment by sparkprime** [comment]
I see the bug, it's using running.empty() to determine whether to insert the delimiter, but that does not distinguish the case where an empty string was pre-pended in the first iteration.

**Comment by sbarzowski** [comment]
I checked go-jsonnet and it behaves as expected, i.e:

    $ ./jsonnet -e 'std.join("_", ["", "test", "", "test2"])'
    "_test__test2"

**Comment by sparkprime** [comment]
It was a c++ version of the join() that had the bug, so no need to update Go.
