### ISSUE TITLE
Broken indentation with std.manifestYamlDoc when used with arrays

### ISSUE THREAD

**Issue by Andor** [google/jsonnet#591]
I have an issue with function `std.manifestYamlDoc()` when it is used with array-type value.

Jsonnet version: `7af3b8496c0d8fd811c996686cfba5958384c77d` from `github.com/google/go-jsonnet/jsonnet`

Here is an example (node square brackets):
```
std.manifestYamlDoc([{
    x: [1, 2, 3, true, false, null, "string\nstring\n"],
    y: { a: 1, b: 2, c: [1, 2] },
}])
```
returns me the string:
```
"- \"x\": \n- 1\n- 2\n- 3\n- true\n- false\n- null\n- |\n  string\n  string\n\"y\": \n  \"a\": 1\n  \"b\": 2\n  \"c\": \n  - 1\n  - 2"
```
which is effectively is:
```
- "x": 
- 1
- 2
- 3
- true
- false
- null
- |
  string
  string
"y": 
  "a": 1
  "b": 2
  "c": 
  - 1
  - 2
```

And this is definitely not a valid YAML structure.

**Comment by seh** [comment]
At [line 951 in _std.jsonnet_](https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet#L951), substituting `cindent` with `'  '` appears to fix the problem—for a small test case, anyway. It's probably wrong once more nesting comes into play.
