### ISSUE TITLE
Jsonnet fmt should be a builtin capable of operating on snippets or strings

### ISSUE THREAD

**Issue by dan-compton** [google/jsonnet#594]
See https://github.com/google/go-jsonnet/issues/193#issuecomment-455824042  for additional details

My goal is to get away from using go to make mass-changes to our service manifests.  Currently, the only way to print out jsonnet code at runtime is via importstr (AFAIK) -- otherwise it is desugared to pure json (e.g. std.toString does this).   It is also possible to use the formatting tool to do this, but the formatting tool expects a string. I haven't gotten this method to work.

Is the only option for me to write a lexer and parser in jsonnet or is there a better way.  I've noticed some functions (e.g. in fmt.h etc) that look promising, but haven't had luck so far.

I feel as though it would be easy to accomplish this if jsonnet fmt was a builtin std.fmt which wrote out the resultant jsonnet as a string (similar to importstr).   Open to other ideas as well.

**Comment by sbarzowski** [comment]
I think it was discussed a lot in other issues and in the mailing list. I'm going to close this one. Feel free to reopen if you have further questions or proposals (especially concrete ones).
