### ISSUE TITLE
Tutorial: if/else too greedy?

### ISSUE THREAD

**Issue by zeisss** [google/jsonnet#595]
Url: https://jsonnet.org/learning/tutorial.html
Example: Conditionals

In this example the Virgin Mojito only gets "Mint" as an ingredient; afaict it misses the syrup/lime/soda that is added to the array after the the `if/else`. it seems the else is interpreted to not only contain the `[]` but also the `+ [ {... } ]`. Putting the if/else into paranthesis fixes this.

Not sure if this is an interpreter bug or the example should contain paranthesis.

**Comment by sbarzowski** [comment]
Thanks for reporting. The if/else behavior is correct. It's just that the parens are missing in the example. 

This looks like this old issue: https://github.com/google/jsonnet/issues/567. The example in the repo was updated, but perhaps it wasn't propagated to the website in the end. I can see the correct version here: https://github.com/google/jsonnet/blob/master/examples/conditionals.jsonnet

@sparkprime Can you take a look?

**Comment by sparkprime** [comment]
Woops, thanks for the heads up
