### ISSUE TITLE
Confusing output of std.join in version 0.12.1 (bug?)

### ISSUE THREAD

**Issue by mdk194** [google/jsonnet#596]
I built and used C++ jsonnet.
Maybe name the title as 0.12.1 std.join ignores empty string in array.

std.join generating unexpected output in version 0.12.1:
```
# both version 0.12.1 and 0.11.2 return array of 5 empty strings, which is correct

⚑ jsonnet -e "['' for _ in std.range(0, 4)]"
[
   "",
   "",
   "",
   "",
   ""
]

⚑ jsonnet-0.12.1 -e "std.join('.', ['' for _ in std.range(0, 4)])"
""

⚑ jsonnet-0.11.2 -e "std.join('.', ['' for _ in std.range(0, 4)])"
"...."
```
with version 0.12.1 std.join outputs empty string `""`
with version 0.11.2 std.join outputs `"...."`

I can workaround problem by:
```
⚑ jsonnet-0.12.1 -e "std.join('', ['.' for _ in std.range(1, 4)])"
"...."

⚑ jsonnet-0.11.2 -e "std.join('', ['.' for _ in std.range(1, 4)])"
"...."
```

But, I think this is a bug with std.join in version 0.12.1

**Comment by sbarzowski** [comment]
Why do you think 4 dots is incorrect? It is a separator, and there are 4 gaps between 5 elements. What would you expect?

Python does the same thing:
```python -c 'print(".".join(["" for i in range(0,5)]))'
....
```

(note range(0,5) in Python - because in Jsonnet the `std.range` function is inclusive and in Python it's upper-bound exclusive)

**Comment by mdk194** [comment]
ah, yes, i'm wrong
However version 0.12.1 returns `""` is incorrect right ?

**Comment by sparkprime** [comment]
Yes this is fixed in HEAD and I need to do another release because of it
