### ISSUE TITLE
std.split max stack frames exceeded when external variable name is unquoted

### ISSUE THREAD

**Issue by Hashfyre** [google/jsonnet#610]
I have the following on `sample.libsonnet` (part of a set of ksonnet manifests):
```
domainList=a.myorg.com,b.myorg.com
local domainList = std.split(std.extVar(domainList), ",");
```
the resultant error is:
```
RUNTIME ERROR: max stack frames exceeded.
	./sample.libsonnet:5:98-120
	./sample.libsonnet:5:87-121	thunk <str>
	std.jsonnet:100:17-20
	std.jsonnet:100:8-21	thunk <a>
	std.jsonnet:100:8-33	function <anonymous>
	std.jsonnet:100:8-33	function <anonymous>
	./sample.libsonnet:5:77-127	thunk <domainList>
	./sample.libsonnet:5:98-120
	./sample.libsonnet:5:87-121	thunk <str>
	std.jsonnet:100:17-20
	...
	./sample.libsonnet:38:48-68	thunk <containers>
	vendor/ksonnet/ksonnet.beta.3/k8s.libsonnet:1729:209-219	thunk <containers>
	vendor/ksonnet/ksonnet.beta.3/k8s.libsonnet:2007:65-75
	vendor/ksonnet/ksonnet.beta.3/k8s.libsonnet:2007:56-76	thunk <a>
	vendor/ksonnet/ksonnet.beta.3/k8s.libsonnet:2007:56-87	function <anonymous>
	vendor/ksonnet/ksonnet.beta.3/k8s.libsonnet:2007:56-87	function <anonymous>
	vendor/ksonnet/ksonnet.beta.3/k8s.libsonnet:1729:164-220	function <anonymous>
	./sample.libsonnet:38:7-80	object <anonymous>
	main.jsonnet:339:27-46	object <anonymous>
	During manifestation
```
I see `std.split(str, c)` uses `std.splitLimit(str,c,maxsplits)` which has `tailstrict`, so not sure why we are getting the above error.

Similar Issues:
 - https://github.com/google/jsonnet/issues/531

I'd like to understand this and raise a PR.

**Comment by sbarzowski** [comment]
This is not a problem with `std.split`, you just hit a little Jsonnet-ism. In Jsonnet variables can be self-recursive. You can write things like `local infinite_structure = [1, infinite_structure];`. You forgot to put quotes around extVar name. so now when it tries to evaluate std.extVar(domainList) it tries to evaluate `domainList` value which evaluates `std.extVar(domainList)` and the circle is complete. BTW stack limit is there exactly for this reason - so Jsonnet doesn't eat all your RAM when infinite recursion happens.

So what you probably meant was (note the quotation marks):
`local domainList = std.split(std.extVar("domainList"), ",");`

Please let me know if that resolves your issue.

**Comment by Hashfyre** [comment]
@sbarzowski thanks, but shouldn't that throw a much cleaner error like "[ERROR] Unquoted external variable"

**Comment by sbarzowski** [comment]
Well, in general it's valid to use a variable there. You can do something like:
```local name="domainList"; std.extVar(name)"
```
It's quite unusual, I think, so maybe that's something which can be added to the linter later.

**Comment by sparkprime** [comment]
I suspect this is part of a class of infinite recursions that would be fairly easy to statically detect.

**Comment by Hashfyre** [comment]
Thanks everyone, 
`local domainList = std.split(std.extVar("domainList"), ",");` indeed solved my immediate issue. 

But as @sbarzowski pointed out `local name="domainList"; std.extVar(name)` should still be valid, which is not the case.

So, not sure if I should keep this issue open or close it as my specific problem got solved.

**Comment by sbarzowski** [comment]
What I meant was that `local name="domainList"; std.extVar(name)` is valid and it _works_ right now. It was just the argument why we cannot just error out on `std.extVar(domainName)`, because you can pass variable to extVar. 

E.g:
```
$ jsonnet -e 'local name="domainList"; local domainList = std.split(std.extVar(name), ","); domainList' --ext-str domainList="a.com,b.com"
[
   "a.com",
   "b.com"
]  
```

So this issue is definitely resolved AFAIC. There is a useful suggestion for the linter coming out of it (to heuristically detect such cases), but I don't think we need to keep this issue around.
