### ISSUE TITLE
Add --- on top of each YAML object in .yml files

### ISSUE THREAD

**Issue by gbergere** [google/jsonnet#614]
Hello,

Would it be possible to prepend each YAML object in `.yml` files with `---`? I personally need to read several YAML files from a `cat` command so without this it doesn't work as I don't know where each YAML object starts.

Thanks
Geoffrey

**Comment by seh** [comment]
You are asking for [the _c-directives-end_ production](https://yaml.org/spec/1.2/spec.html#c-directives-end) from §9.1.2 of the YAML specification. I'd rather see an optional [_c-document-end_](https://yaml.org/spec/1.2/spec.html#c-document-end) at the end of document, assuming that you're never writing directives at the start of a document. [§9.2 of the specification](https://yaml.org/spec/1.2/spec.html#id2801681)—_Streams_—describes the options for separating documents in a (concatenated) stream.

From that section:
> **Concatenating Streams**
> Concatenating two YAML streams requires both to use the same character encoding. In addition, it is necessary to separate the last document of the first stream and the first document of the second stream. This is easily ensured by inserting a document end marker between the two streams. Note that this is safe regardless of the content of either stream. In particular, either or both may be empty, and the first stream may or may not already contain such a marker.

**Comment by gbergere** [comment]
Yes that's correct

**Comment by sparkprime** [comment]
So if I'm following this correctly, neither of the following work for you because you can't concat either of them with cat.

```
dcunnin@dcunnin1:~$ jsonnet -Se 'std.manifestYamlDoc({x: 3, y: 2})'
"x": 3
"y": 2
dcunnin@dcunnin1:~$ jsonnet -Se 'std.manifestYamlStream([{x: 3, y: 2}])'
---
"x": 3
"y": 2
...
```

So you're asking for a new feature that would output just the `---` without the terminating `...`.

There are some workarounds in bash though:

```
for f in *.yml; do echo '---''; cat "$f"; done
```
(Or just echo --- before running Jsonnet).

Alternatively, using awk in a pipe:

```
jsonnet -eS 'std.manifestYamlDoc({x: 3, y: 4})' | awk 'BEGIN{print "---"}; {print}'
```

**Comment by gbergere** [comment]
Thanks for the trick.

I'm using it with Kapitan not sure how I could do this with Kapitan as Kapitan handle Jsonnet call.

Geoffrey

**Comment by sparkprime** [comment]
It'd also be pretty trivial to add a param to disable the `...` which would look like `std.manifestYamlStream([{x: 3, y: 4}], disable_c_document_end=true)`
