### ISSUE TITLE
access object attributes when formatting string

### ISSUE THREAD

**Issue by mariusgrigoriu** [google/jsonnet#617]
I am hoping to access object attributes when formatting a string. For example:

```
{
  str5: |||
    %(e.f)s
  ||| % {e: {f: 'hi'}},
}
```
Returns: `RUNTIME ERROR: No such field: e.f`

Am I doing it wrong or is this not possible right now?

**Comment by sbarzowski** [comment]
The thing you put inside parentheses is treated as one field. So for example:

```
{
  str5: |||
    %(e.f)s
  ||| % {"e.f": 'hi'},
}
```
produces:
```
{
   "str5": "hi\n"
}
```

It is not currently possible to do indexing inside format string. Jsonnet's `%` is almost exactly the same thing as Python's `%` operator.

**Comment by mariusgrigoriu** [comment]
Got it. We can pass the inner object / compose a new object when dealing with large text files so it shouldn't be a big deal to go without that feature.

**Comment by EdSchouten** [comment]
> It is not currently possible to do indexing inside format string. Jsonnet's `%` is almost exactly the same thing as Python's `%` operator.

It would be nice if Jsonnet ever gained support for something similar to [Python's f-strings](https://www.python.org/dev/peps/pep-0498/).
