### ISSUE TITLE
libjsonnet.js: function Pointer_stringify was removed / UTF8ToString is not exported

### ISSUE THREAD

**Issue by rbicker** [google/jsonnet#621]
Hi

I built the javascript library by running ```make libjsonnet.js```. When I tried to use the resulting lib like shown in https://jsonnet.org/js/demo.js, I got an error stating that the function Pointer_stringify was removed and that UTF8ToString should be used instead. However this function is not exported.

I think the solution would be adding the function to the Makefile in line 134?
JS_RUNTIME_METHODS = 'EXTRA_EXPORTED_RUNTIME_METHODS=["cwrap", "_free", "getValue", "lengthBytesUTF8", "_malloc", "Pointer_stringify", "setValue", "stringToUTF8", "addFunction", "UTF8ToString"]'

Should I open a pull request?

Thanks

**Comment by sparkprime** [comment]
Yeah that looks like the right thing to do.  What emscripten version did you use?
