### ISSUE TITLE
No error occurs when the number of spaces is incorrect

### ISSUE THREAD

**Issue by Xindahuang** [google/jsonnet#623]
Via `jsonnet fmt --test filepath` command, I can't get any error returned when there is incorrect number of spaces. However I can get a diff result via diff command. Also I can get a non-zero digit via `echo $?`. This means jsonnet fmt detects error without reporting it.

Example:
`{
  "recommendations": [
    "zxh404.vscode-proto3" ,
  ]
}`

**Comment by sbarzowski** [comment]
This doesn't have anything to do with spaces in particular. The behavior is the same for any formatting change.

The way `--test` option works is that it changes exit code if the file is not already formatted and it never prints anything (assuming the program is syntactically correct, etc.) . It's designed mostly for use in scripts.

**Comment by sparkprime** [comment]
Yeah this is working as intended.
