### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by michaeljs1990** [google/jsonnet#631]
Sorry to bother you but I was wondering if you would mind cutting a new release for me. #618 has a fix that is needed for my code to run. I have built it locally and it works great but I don't want to scare my team off jsonnet by having to have them compile it from source before they can run my code which is why I wanted to update the homebrew default version.

**Comment by sparkprime** [comment]
I'm vacation for 3 weeks but yes it's well overdue because of the std.join bug in the last release as well

**Comment by sparkprime** [comment]
Done (only took me 2 months!)

**Comment by michaeljs1990** [comment]
Thank you! https://github.com/zys-contribs/homebrew-core/pull/298/commits/1e582eac610e128bea7dd4f78e8e51256e8a4094 was already landed upstream for version 13.
