### ISSUE TITLE
Unhide hidden fields

### ISSUE THREAD

**Issue by Roshek** [google/jsonnet#632]
I was wondering if it was possible to "unhide" a hidden field?
So for example something like this:
```
local unhide = {
    a: super.a
};

{
    obj: {
        a:: 'hidden'
    } + unhide
}
```

would produce this:
```
{
    "obj": {
        "a": "hidden"
    }
}
```

with the current release the result is this:
```
{
    "obj": { }
}
```

**Comment by sbarzowski** [comment]
Yes. The `:::` does that. 

E.g.:
```
jsonnet -e '{a:: "x"} + {a::: super.a}'
```

However there's a question to what extent it should be used from the style and clarity point of view. Usually things either should be simply hidden (because they are some "operational" internals) or always be visible (exported data).

**Comment by Roshek** [comment]
Oh, sorry, didn't find that one in the docs.

I'm currently experimenting with ways to generate a large number of different config files based on the same set of basic values and a lot of calculated ones, using a single (list of) object(s) as a kind of "single source of truth" and do projections from it based on the needs of a particular format.

Anyways, thanks for the quick help!
