### ISSUE TITLE
Live examples don't work on firefox

### ISSUE THREAD

**Issue by gdetrez** [google/jsonnet#633]
Hi! I just discovered jsonnet but I stumbled on some issues when I tried to play with the examples on the site (https://jsonnet.org).  If I take the first example and start adding `person3: self.person1 { name: "Cat" },` it seems to work find at first but after a few keystroke, I get the output:
```
abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.
```
![image](https://user-images.githubusercontent.com/38019/56122405-a7584080-5f72-11e9-892a-4e2f08a0be09.png)

And then it doesn't work anymore, even if I restore the original example.

Some observations:
- I'm not sure but this looks like an error message from emscripten
- if I just paste the new line instead of typing it in, it works fine

I'm using Firefox 62 on Fedora but I also tested with firefox 66 and got the same issue.  I does seem to work fine on Chromium.

**Comment by sbarzowski** [comment]
Thanks for the report!  I was able to reproduce and I have a local fix (basically the same thing as suggested in the error).
