### ISSUE TITLE
jsonnet reports errors to STDOUT, not STDERR

### ISSUE THREAD

**Issue by moritz** [google/jsonnet#638]
jsonnet prints errors to STDERR, not to STDOUT:

    $ jsonnet -e '{};'
    STATIC ERROR: <cmdline>:1:3: Did not expect: ";"
    $ jsonnet -e '{};' |wc -l
    1

This is contrary to the intended use cases of STDOUT and STDERR, and makes it much harder to build shell pipelines. For example,

    $ jsonnet -e '{a: 2;}' | jq .a
    parse error: Invalid numeric literal at line 1, column 7

only shows the parse error from jq trying to parse jsonnet's error message as JSON.

If jsonnet instead printed the error message to `STDERR`, it would be visible despite its use within a pipeline.

**Comment by sbarzowski** [comment]
I agree. It should also be quite easy to fix, I'm only a bit worried about breaking existing users.

FYI I think the go implementation (https://github.com/google/go-jsonnet) doesn't have this issue, you may want to try it.

**Comment by seh** [comment]
> I'm only a bit worried about breaking existing users.

That would break this PR of mine (mgyucht/jsonnet-mode#12) against _jsonnet-mode_, which assumes that _jsonnet eval_ writes errors to standard output. However, I could revise the patch to separate the output streams in the call to [`call-process`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Synchronous-Processes.html) like I did in the call to _jsonnet fmt_.

**Comment by sparkprime** [comment]
Looks like this got fixed:
```
dcunnin@dcunnin1:~/jsonnet$ jsonnet -e '{};' | wc -l
STATIC ERROR: <cmdline>:1:3: did not expect: ";"
0

```
