### ISSUE TITLE
String interpolation message unclear when values inconsistent

### ISSUE THREAD

**Issue by uberspot** [google/jsonnet#644]
Interpolating the following string in jsonnet `'%(var) rate > 50%' % some_variable,` would produce a stacktrace with ` RUNTIME ERROR: Not enough values to format, got 1` 
Which is valid but not really clear on what the problem is.
Same for string like: `'%(var) rate > %(var)' % some_variable,`

Could we make the error message easier to understand and hint more about the problem so it's easier to resolve in large codebases?

Maybe something like `String interpolation failed. Expected x values but received y` ?

**Comment by sbarzowski** [comment]
Here's where it comes from: https://github.com/google/jsonnet/blob/206ed1cb2068e47df8b6e3ab03f062b339e0e5f3/stdlib/std.jsonnet#L663
(and two similar lines below it)

I guess we could do it in the same way as with too many values.
