### ISSUE TITLE
Support `1 in [1, 2, 3]`

### ISSUE THREAD

**Issue by sparkprime** [google/jsonnet#667]

**Comment by seh** [comment]
Would this assume that the array is a set (using binary search), or would it use linear search?

**Comment by sbarzowski** [comment]
I think linear search is safer here. It may be really confusing otherwise.

**Comment by seh** [comment]
I think we should document that this is _not_ sugar for `std.setMember`, and vice versa, that `std.setMember` is not implemented in terms of this.

**Comment by sbarzowski** [comment]
Duplicate of #513.
