### ISSUE TITLE
jsonnetfmt binary not available in Docker image

### ISSUE THREAD

**Issue by tom-haines** [google/jsonnet#669]
The docker build image created from the Dockerfile does not contain the jsonnetfmt binary.

This would be solved with the addition of
```
COPY --from=builder /opt/jsonnet/jsonnetfmt /usr/local/bin
```

**Comment by tom-haines** [comment]
Opened https://github.com/google/jsonnet/pull/670

**Comment by sbarzowski** [comment]
Fixed by #670, thanks again
