### ISSUE TITLE
Fix importstr

### ISSUE THREAD

**Issue by nikolay** [google/jsonnet#671]
Many editors leave a trailing newline, which unfortunately is picked by Jsonnet. Final newline should be stripped.

**Comment by sbarzowski** [comment]
So let's say you have the following file `a.txt`:
```
a
b
c
```
(with a newline after `c`)

You expect `importstr 'a.txt'` to return `"a\nb\nc"`, right?

**Comment by sbarzowski** [comment]
It's easy to write a function to do that in Jsonnet. It may be even easier if #733 is implemented. Stripping it by default could be confusing and it would make it impossible to return exactly the same content byte-by-byte (which the user might want). It's a safer option to include the whole contents.
