### ISSUE TITLE
Feature request: Native comments-preserving conversion from YAML -> JSONNET

### ISSUE THREAD

**Issue by josdotso** [google/jsonnet#698]
In the evolution of piles of YAML to JSONNET, we find ourselves converting YAML -> JSON -> JSONNET a _lot_. When we do this, YAML comments are dropped in the lossy conversion from YAML -> JSON.  However, if the conversion were from YAML -> JSONNET that conversion needn't and shouldn't be lossy with respect to comments.

Thoughts?

Thanks!

**Comment by sparkprime** [comment]
Know of a YAML parser that preserves whitespace and comments?
YAML is a very complex format so writing a parser is hard.

**Comment by sbarzowski** [comment]
This could be pretty useful. I think it should be a completely separate tool, unless there is a some reason for tighter integration.

The only parser that doesn't drop comments that I could find was is [ruamel.yaml](https://yaml.readthedocs.io/en/latest/). However comment extraction seems to be far from trivial: https://stackoverflow.com/questions/55130078/yaml-parsing-with-comments-for-doc-purpose

**Comment by josdotso** [comment]
Thanks for the replies.  I looked at ruamel.yaml and https://github.com/mohsen1/yawn-yaml as well, neither of which would easily integrate with either jsonnet's two implementations. A freestanding tool would be fine with me.  Feel free to close this since standalone is the only practical way forward at this time.

**Comment by sparkprime** [comment]
Maybe it's possible to use that to make a YAML -> JSON+comments converter, which can then be input into `jsonnetfmt`.

**Comment by sbarzowski** [comment]
This is tracked by https://github.com/google/jsonnet/issues/765.
