### ISSUE TITLE
std.thisFile should not contain the file path

### ISSUE THREAD

**Issue by buremba** [google/jsonnet#699]
The documentation states that `std.thisFile` returns `the current Jsonnet filename as a string.` but when I try to compile a file with the content:
```
{
    fileName: std.thisFile
}
```

`jsonnet user/test.jsonnet` command returns the output below is I'm not in the same path.
```
{
   "fileName": "user/test.jsonnet"
}

```

**Comment by buremba** [comment]
Is this the expected behavior? In that case, is there any easy way to extract the filename from the path?

**Comment by sparkprime** [comment]
The std.thisFile is the same filename that is reported in stack traces.  It is a relative path from the current working directory when you ran the Jsonnet executable.  You can split it by / if you want the basename.

**Comment by sparkprime** [comment]
```
$ cat a/test.jsonnet 
std.thisFile
$ jsonnet -J a -e 'import "test.jsonnet"'
"a/test.jsonnet"
$ jsonnet -J a -e 'local parts = std.split(import "test.jsonnet", "/"); parts[std.length(parts) - 1]'
"test.jsonnet"
```

**Comment by buremba** [comment]
It looks like it's the expected behavior, thanks for sharing the snippet!
