### ISSUE TITLE
Add std.flatMap

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#705]
FlatMap is a popular operation, widely available in other languages (flatMap in Java, Scala, ECMAScript 2019, concatMap in Haskell).

It is there already in go-jsonnet as a builtin and the Jsonnet-level implementation is trivial.

**Comment by buremba** [comment]
For now, `std.flattenArrays` can be used as a workaround.

**Comment by netomi** [comment]
FlatMap is already present in the stdlib, maybe this ticket can be closed.

**Comment by sbarzowski** [comment]
Yep
