### ISSUE TITLE
Feature request: using `*` (or std.repeat) as a shorthand to duplicate strings and lists?

### ISSUE THREAD

**Issue by lihaoyi-databricks** [google/jsonnet#715]
Scripting languages like Python and Ruby allow this, and it makes creating boilerplate constant lists or strings very easy:

```python
Python 2.7.10 (default, Feb 22 2019, 21:55:15)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> [1] * 5
[1, 1, 1, 1, 1]
>>> "1" * 5
'11111'
```
```ruby
irb(main):001:0> [1] * 5
=> [1, 1, 1, 1, 1]
irb(main):002:0> "1" * 5
=> "11111"
```

The closest way of doing it jsonnet is still pretty verbose:

```javascript
[1 for x in std.range(0, 4)]
```

**Comment by sbarzowski** [comment]
I'm not a big fan of using `*` operator for that. Generally, when the types are not known statically, overloading operators can be quite confusing.

I think a safer option would be to add a function `std.repeat`. For example `std.repeat([1, 2, 3], 3)` would result in `[1, 2, 3, 1, 2, 3, 1, 2, 3]`.

**Comment by lihaoyi-databricks** [comment]
Yeah `std.repeat` would work too
