### ISSUE TITLE
Single quote strings

### ISSUE THREAD

**Issue by sparkprime** [google/jsonnet#72]
These would be the same as " " strings except you would not have to quote " inside them.  You'd have to quote ' instead though.  Same as Python.

**Comment by sparkprime** [comment]
Related to #45

**Comment by jbeda** [comment]
Looking at the lexer, it looks like this is supported but undocumented.

**Comment by sparkprime** [comment]
Hmm yes it looks like I got partially through implementing it and then forgot about it.  I'll finish off the implementation, close this, and then work on the docs.

**Comment by jbeda** [comment]
No hurries on my part.  I'm just working from the lexer on up and haven't hit the unimplemented parts yet.

**Comment by devth** [comment]
Would be great to get this released :+1:
