### ISSUE TITLE
What's the tool described here?

### ISSUE THREAD

**Issue by steeling** [google/jsonnet#721]
https://github.com/google/jsonnet/blob/9e3b60a9e82f18d1f011dcbfd96bf492617febe7/doc/articles/kubernetes.html#L120

The docs reference a conversion tool, but don't name it, or describe how to use it

**Comment by sbarzowski** [comment]
The YAML example below is editable. You can put your YAML there and get Jsonnet.

If you want to use it in a script, the idea is very simple. It converts YAML to JSON and then formats it nicely using jsonnetfmt.
