### ISSUE TITLE
$ is not lazy evaluated

### ISSUE THREAD

**Issue by steeling** [google/jsonnet#723]
This code: 
```
local b = {
  m: $.meta,
};


{
  meta:: 'this does not work',
  a: b,
} 
```

Results in an error: `RUNTIME ERROR: field does not exist: meta`

However if we use the value of b directly:
```
{
  meta:: 'this does work',
  a: {
    m: $.meta,
  },
}
```

We get the output we expect:
```
{
   "a": {
      "m": "this does work"
   }
}
```

With lazy evaluation I would think that the first scenario would work

**Comment by sbarzowski** [comment]
The `$` expression is just a syntax sugar for a **lexically** outermost object. In other words it is precisely equivalent to writing the following every time an object literal appears in the source code outside of other object literals:
```
local my_dollar = {
    ...
}; my_dollar
```
In particular it doesn't let you do anything that a regular local wouldn't do, like accessing object which are not known yet at this code location.

So this behavior is correct (compliant with the spec and the intention behind `$`).

**Comment by steeling** [comment]
Is there a way to reference a resulting object's fields from a template? I'd like to have something like `local a = {m: $.data}; local b = {m: $.data}; { data: {...}, a: a{}, b: b{} }`

**Comment by sbarzowski** [comment]
Yes, but it's going to be a bit more verbose. Jsonnet tries to avoid any hidden dependencies, so we will need to specify the dependence on the parent explicitly.

# Approach 1 - parametrize with functions

```
local a(root) = {m: root.data};
local b(root) = {m: root.data}; 
{
  data: {...},
  a: a($),
  b: b($),
}
```

Generally, I would recommend using functions as the default way of parametrization, if there is no compelling reason to use a different approach.

# Approach 2 - parametrize with inheritance

```
local a = {
  root:: error "not provided", // we could skip this line, but it's more explicit this way
  m: self.root.data,
};
local b = {
  root:: error "not provided", // we could skip this line, but it's more explicit this way
  m: self.root.data,
};

local b(root) = {m: root.data}; 
{
  data: {...},
  a: a { root: $ },
  b: b { root: $ },
}
```

# A note on style

It's another question whether this is the best way to organize the code. My feeling is that it's best to pass as small part of the data as possible (in this case, just the field `data`, rather than the whole "main object"). Ofc I don't know your specific case and YMMV.

**Comment by steeling** [comment]
Thanks for the thorough response! #1 sounds like our best bet then

**Comment by seh** [comment]
> it is precisely equivalent to writing the following every time an object literal appears in the source code outside of other object literals

I ran the following, and was surprised that it works:

> _jsonnet -e 'local my = {a: [1, my.a[0]+1]}; my'_

In particular, for the expression `my.a` inside of the object, how does Jsonnet resolve the reference to "my?" Can the body of a value bound to a local variable refer to the name of that local variable? Is that what's happening here?

**Comment by sbarzowski** [comment]
> Can the body of a value bound to a local variable refer to the name of that local variable? Is that what's happening here?

Yes and yes. The most commonly used example of that is recursive functions. But there is nothing special about functions there in Jsonnet - generally a local value can be used in its own definition. The variable body is evaluated when a reference to this variable is evaluated for the first time. Ofc. this way we can construct an endless loop e.g. local x = x + 1 (in the new linter implementation there is a check which can catch some of these issues - https://github.com/google/go-jsonnet/pull/325/files#diff-454ba691c6329c435eeeb2731e2ac359R1). But for objects, arrays, functions etc. it may sometimes make sense to have recursive definitions.
