### ISSUE TITLE
Feature Request: Array expansion with ...

### ISSUE THREAD

**Issue by mustafaakin** [google/jsonnet#725]
What do you think about implementing the following feature:

```
local a = [4,5,6];

[
  1,2,3, a...
]
```

**Comment by sbarzowski** [comment]
So for example `[expr1, expr2, expr3..., expr4, expr5...]` would be a syntax sugar for `[expr1, expr2] + expr3 + [expr4] + expr5`?

**Comment by sparkprime** [comment]
There's very little difference between the two:

```jsonnet
[expr1, expr2, expr3..., expr4, expr5...]
[expr1, expr2] + expr3 + [expr4] + expr5
```

So I don't think it's worth burdening the parser, language spec, documentation and tooling with the additional construct.  Sorry!
