### ISSUE TITLE
RuntimeError: RUNTIME ERROR: Not enough values to format: 1, expected at least 1

### ISSUE THREAD

**Issue by gagandeep** [google/jsonnet#726]
I am getting the following error
```RuntimeError: RUNTIME ERROR: Not enough values to format: 1, expected at least 1```

That code is running for others but failing for just one. I am not able to pin-point the exact case where it's failing.

Using Python jsonnet version 0.14
Downgrading jsonnet version to <0.14 don't solved the Runtime Error.

**Comment by gagandeep** [comment]
The unuseful error message because of the following. 
https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet#L687

In this case, the error message shouldn't be `expected at least` as it should be `expected more than`

**Comment by gagandeep** [comment]
Got the issue. The array contained null values and I was doing string formatting upon those null values. Changed following,
```local entry_ids(entries) = [{'id':'%(extractor)s_%(id)s' % entry, 'index':entry['playlist_index']} for entry in entries];```
to
```local entry_ids(entries) = [if entry != null then {'id':'%(extractor)s_%(id)s' % entry, 'index':entry['playlist_index']} for entry in entries];```

This solved my error. Maybe helpful for any other also.

However, the error message was totally useless and counter-intuitive.

**Comment by sbarzowski** [comment]
Thank you very much for getting to the bottom of this and the PR!
