### ISSUE TITLE
Weird results for basic add/sub with big numbers

### ISSUE THREAD

**Issue by LorisFriedel** [google/jsonnet#730]
I noticed some big numbers basic calculation are giving weird results, such as the one bellow:
`jsonnet -e "(83+18085679255350848+18519735557479268352-282588738364857)"`

This should give **18537538647996254426** but jsonnet calculates it to **18537538647996256256**

I'm on macOS 10.14.16 and I tried with both Go and C++ executable.

Any idea?

**Comment by sbarzowski** [comment]
All numbers in Jsonnet are represented as double (as defined in IEEE754). An unfortunate consequence of this is that very big numbers are represented only with certain precision, even if they are integers.

You can easily reproduce both the precise answer and Jsonnet's answer in Python:
```
>>> 83+18085679255350848+18519735557479268352-282588738364857
18537538647996254426L
>>> 83.0+18085679255350848.0+18519735557479268352.0-282588738364857.0
1.8537538647996256e+19
```

**Comment by LorisFriedel** [comment]
Thank you for your quick answer!

If this is by design, I guess the only workaround would be to add custom functions to support big integers? Or is there any other way to have exact results without custom code?

**Comment by sbarzowski** [comment]
Well, you could always implement bignums on top of strings in Jsonnet. They would be reaaally slow, but if you just need addition and subtraction in a few places it may be fine. I may help you with that if you want.

We may also consider adding native support to Jsonnet (that is stdlib functions operating on bignums represented as strings/arrays).

**Comment by LorisFriedel** [comment]
Thank you for your help!
I think I'll try to find another solution to my problem that does not involve doing the computation in jsonnet, but having functions to manipulate big numbers natively could be really useful!
