### ISSUE TITLE
emscripten: Attempt to set a non-existent setting: 'OUTLINING_LIMIT'

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#743]
I'm trying to rebuild the stuff for the website:

$ em++ --version
emcc (Emscripten gcc/clang-like replacement) 1.39.4 (commit a0d34f6a61e0f7182e92636c280004dc994083ee)

$ make doc/js/libjsonnet.js
em++ -s WASM=0 -s 'EXPORTED_FUNCTIONS=["_jsonnet_make", "_jsonnet_evaluate_snippet", "_jsonnet_fmt_snippet", "_jsonnet_ext_var", "_jsonnet_ext_code", "_jsonnet_tla_var", "_jsonnet_tla_code", "_jsonnet_realloc", "_jsonnet_destroy", "_jsonnet_import_callback"]' -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["cwrap", "_free", "getValue", "lengthBytesUTF8", "_malloc", "UTF8ToString", "setValue", "stringToUTF8", "addFunction"]' -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -g0 -Os --memory-init-file 0 -s DISABLE_EXCEPTION_CATCHING=0 -s OUTLINING_LIMIT=10000 -s RESERVED_FUNCTION_POINTERS=20 -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1  core/desugarer.cpp core/formatter.cpp core/lexer.cpp core/libjsonnet.cpp core/parser.cpp core/pass.cpp core/static_analysis.cpp core/string_utils.cpp core/vm.cpp third_party/md5/md5.cpp -o libjsonnet.js
shared:ERROR: Attempt to set a non-existent setting: 'OUTLINING_LIMIT'
 - did you mean one of INLINING_LIMIT?
 - perhaps a typo in emcc's  -s X=Y  notation?
 - (see src/settings.js for valid values)
make: *** [Makefile:191: libjsonnet.js] Error 1

**Comment by sparkprime** [comment]
I got this too and fixed it in #775 (i think)
