### ISSUE TITLE
Don't require emscripten for casually serving the website

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#744]
We should encourage updating and building the website (to keep it complete and up-to-date). Currently emscripten adds significant amount of pain to it. For 99% of changes the old libjsonnet.js can be used just as well.

**Comment by sbarzowski** [comment]
Actually we're not that far currently. The interactive parts won't work, but otherwise the setup is complete. It may be enough to write in the README that compiling of libjsonnet.js is optional.

**Comment by sparkprime** [comment]
Or just `wget https://jsonnet.org/js/libjsonnet.js`
