### ISSUE TITLE
Using Discourse as discussion forum instead Google forum

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [google/jsonnet#753]
Let's use the open-source [Discourse](https://github.com/discourse/discourse) as a discussion forum rather than a Google forum. We can still use GCP to host it.

**Comment by sparkprime** [comment]
Sorry, moving would be a pain and since this is a Google project, Google groups is fine :)

We are on kubernetes slack #jsonnet too if you want a more interactive discussion.
