### ISSUE TITLE
Include function from another file

### ISSUE THREAD

**Issue by kaihendry** [google/jsonnet#755]
Is it possible to include a function from another file? i.e. test2 uses function defined in test? I can't make it work:

```
[hendry@t480s dashboards]$ cat test.jsonnet
local Person(name='Alice') = {
  name: name,
  welcome: 'Hello ' + name + '!',
};
{
  person1: Person(),
  person2: Person('Bob'),
}
[hendry@t480s dashboards]$ cat test2.jsonnet
local Person = import 'test.jsonnet';
{
  person2: Person.Person('Test2'),
}
```

Error is ```RUNTIME ERROR: field does not exist: Person
        test2.jsonnet:3:12-25   object <anonymous>
        During manifestation
make: *** [Makefile:6: test2.json] Error 1```

Thank you,

**Comment by terryyylim** [comment]
local Person in `test.jsonnet` is a private function and will not be available outside of the file. 

What `local Person = import 'test.jsonnet';` is essentially doing is importing 
`{
  person1: Person(),
  person2: Person('Bob'),
}`. If you try `person2: Person.person1` in test2.jsonnet, it should work.
