### ISSUE TITLE
Tutorial: top-level arguments as config unclear

### ISSUE THREAD

**Issue by dsharp-pivotal** [google/jsonnet#757]
The tutorial says:
> The config can be imported as a library and called as a function
https://github.com/google/jsonnet/blob/1ca90669fbcabf36644092f00bfc6972e98ed8c3/doc/learning/tutorial.html#L649

We are uncertain what this means. Can you please clarify? It sounds like TLAs could be isolated to a library, but I can't come up with a way to do that.

CC: @jvigil-pivotal

**Comment by sbarzowski** [comment]
The config refers to the Jsonnet program in that sentence not to TLAs.

You can have a Jsonnet program which evaluates to a function and then call this function directly from commandline or import it from another Jsonnet file, e.g.:

`hello.libsonnet`:
```
function(who) "Hello, " + who
```

Calling from commandline:
```
jsonnet --tla-str who=Alice hello.libsonnet
```

Calling from another Jsonnet program:
```
local hello = import "hello.libsonnet"; // imported as a library
hello("Bob") // and called as a function
```

**Comment by dsharp-pivotal** [comment]
Thanks, I'm reading it correctly now. Maybe I was trying to read it wishfully so that it would work the way I wanted. But I think "the config" is ambiguous. Maybe this bullet could be reworded:

"A config with top-level arguments can also be imported as a library and called as a function with parameters passed in"

**Comment by sbarzowski** [comment]
> Maybe I was trying to read it wishfully so that it would work the way I wanted.

Can you explain what did you want to achieve?

**Comment by dsharp-pivotal** [comment]
Yeah, sure. I was hoping to basically have the best of both worlds (TLAs and external vars) by having the TLAs be part of a module. Then whenever we needed to reference a parameter value, we could just import the module and grab the necessary value. The module would be the source-of-record for set of TLAs (that is, I wanted to avoid repeating the parameter list in multiple places). The module would also be able to take care of default values.

We did actually find something that works for us, but not quite the same. It's a module that has a function "Apply(this)" that we can use in the top-level module. It returns a function that takes the TLAs and returns `this` with a hidden field `tla` added to it. Then the only tricky part is getting a reference to `tla` from all the locations that need it, but usually it can be found with `$.tla`.

 It looks something like this:

```jsonnet
// tla.libsonnet
{
Apply(this):: function(boolarg=true, stringarg1="", stringarg2="arg2")
    this {
        tla:: {
            boolarg: boolarg,
            stringarg1: stringarg1,
            stringarg2: stringarg2,
        }
    }
}
```

Used something like this in a topl-level config:
```jsonnet
local tla = import "tla.libsonnet";

local obj1 = {
    local this = self,
    aList+: [ { name: this.tla.stringarg1 } ],
};

local obj2 = {
    local this = self,
    aList+: if this.tla.boolarg then [{name: this.tla.stringarg2}] else [],
    // (if obj1 or obj2 are in a module, then `this.tla` can be `$.tla`)
};

tla.Apply(obj1 + obj2)
```

**Comment by sparkprime** [comment]
It sounds like these are you constraints:
- You want to use TLAs, because you want default values
- You want to have multiple distinct entrypoints (i.e. jsonnet <foo.jsonnet>) that all share the same parameters, you call these modules, and you also want to mix modules together.
- You don't want to duplicate the list of arguments and default values everywhere.

There's a slight change to what you already proposed that avoids the field pollution ($.tla):
```
local tla = (
  // tla.libsonnet
  {
    MixWithTlas(objs):: function(boolarg=true, stringarg1='', stringarg2='arg2')
      local tlas = {
        boolarg: boolarg,
        stringarg1: stringarg1,
        stringarg2: stringarg2,
      };
      std.foldl(function(a, obj) a + obj(tlas), objs, {}),
  }
);  
      
local obj1(tla) = {
  aList+: [{ name: tla.stringarg1 }],
};

local obj2(tla) = {
  aList+: if tla.boolarg then [{ name: tla.stringarg2 }] else [],
};

tla.MixWithTlas([obj1, obj2]) 
```

Or split the function if you like:
```
local tla = (
  // tla.libsonnet
  {
    StandardParams(func):: function(boolarg=true, stringarg1='', stringarg2='arg2')
      func({
        boolarg: boolarg,
        stringarg1: stringarg1,
        stringarg2: stringarg2,
      })
  }   
  {
    MixWithSameTlas(objs):: function(tlas)
      std.foldl(function(a, obj) a + obj(tlas), objs, {}),
  }
);

local obj1(tla) = {
  aList+: [{ name: tla.stringarg1 }],
};

local obj2(tla) = {
  aList+: if tla.boolarg then [{ name: tla.stringarg2 }] else [],
};

tla.StandardParams(tla.MixWithSameTlas([obj1, obj2]))
```

This would be easier if we had a `**kwargs` thing like Python.

Another thing you might be able to do is specify all of your parameters as a single JSON blob, then mix that on top of a set of defaults in a library.  Because all of the code passes the single JSON blob as a single variable, you're not duplicating the set of parameters everywhere.

**Comment by sparkprime** [comment]
Actually if we did have **kwargs, you could just write all your code as:
```
function(**kwargs))
  ... kwargs.foo ... kwargs.bar ...
```

But you'd still need something like the tla.MixWithSameTlas function in order to mix the objects together in the context of the same set of input arguments.

**Comment by sparkprime** [comment]
By the way, I think that change you proposed to the tutorial is a good improvement

**Comment by dsharp-pivotal** [comment]
Cool, thanks for those suggestions. 

> You want to have multiple distinct entrypoints (i.e. jsonnet <foo.jsonnet>) that all share the same parameters, you call these modules, and you also want to mix modules together.

fwiw, we don't actually have multiple entrypoints. We simply organize parts of a large object into smaller objects (with the same schema) that we merge together. It's a [Concourse](https://concourse-ci.org) pipeline, if you're interested. Each "module" we write as a "mini-pipeline", and then merge them all together into the main pipeline. The main pipeline is currently the only entrypoint. But each "mini-pipeline" needs access to the top-level args.

**Comment by sparkprime** [comment]
Updated the tutorial per the suggestion in #775
