### ISSUE TITLE
Rename `osx` release identifier to `darwin`

### ISSUE THREAD

**Issue by lucendio** [google/jsonnet#760]
I'm currently automating the installation of some dependencies. Unfortuantly `jsonnet` stood out.
It seems to be common sense in release culture to use the output of `uname` when naming the artifact, therefore, I would like to ask you to rename `osx` to `darwin`.

Thank you very much!

**Comment by sbarzowski** [comment]
We used `$TRAVIS_OS_NAME`, but I can see how `uname` may be a better choice.

Feel free to send a PR to change it here (https://github.com/google/jsonnet/blob/v0.14.0/.travis.yml#L43). I'll rename the latest release then as well.

**Comment by lucendio** [comment]
Yes, I realized I can just change it. Here you go https://github.com/google/jsonnet/pull/761

**Comment by sbarzowski** [comment]
Thanks! I've also added `darwin` release for 0.14. I've left `osx` as well (so we have both osx and darwin for 0.14, which are the same thing), because I didn't want to break people who use the old url.

**Comment by lucendio** [comment]
Thanks so much. That makes my life way easier :)
