### ISSUE TITLE
How to use '%' in string format?

### ISSUE THREAD

**Issue by jonnyyu** [google/jsonnet#774]
I have a situation to format a Windows command, which embeds windows environment variables. 
```
command: 'cp %s %TMP%' % filename
```
Jsonnet compiler give me `RUNTIME ERROR: Unrecognised conversion C'

Is there anyway to express % as a literal? Thanks!

**Comment by sbarzowski** [comment]
Yes: `'cp %s %%TMP%%' % filename`, same as in Python and C.

Just to be clear - there is nothing special about `%` in a string, they don't require escaping or anything. It's the operator `%` which interprets the string which treats `%` like a special character for formatting (again, like printf in C or `%` in Python).

**Comment by jonnyyu** [comment]
thank you!
