### ISSUE TITLE
Partial evaluation for outputting jsonnet

### ISSUE THREAD

**Issue by Qinusty** [google/jsonnet#787]
Currently, I cannot see a way to produce jsonnet files currently without the addition of some form of partial evaluation.

Ideally evaluation of certain expressions could be overlooked during the first interpretation to allow the produced jsonnet file to contain expressions which can be evaluated at runtime.

#### Use Case:
Producing several templated .jsonnet configuration files for an application. The goal is to produce these configurations and distribute them to their appropriate servers and allow the application to load them as jsonnet files (evaluating any remaining expressions).

Related: https://github.com/google/jsonnet/issues/478.

**Comment by sbarzowski** [comment]
1) Can you provide a concrete example of how that would look like? 
2) Why not pass the original template to the application along with all necessary data and evaluate it in one go (perhaps passing some data along the way, wrapping it in a function and calling from another file or something like that). 
3) "Ideally evaluation of certain expressions could be overlooked during the first interpretation to allow the produced jsonnet file to contain expressions which can be evaluated at runtime." - What's the criteria for evaluating in the first interpretation vs at runtime?

**Comment by Qinusty** [comment]
1: Not exactly, I'm not sure whether this should be achieved via keywords to prohibit evaluation of expressions or simply a function to render jsonnet as jsonnet (without evaluation).
2: Likely a valid option, generate my config on the server to json to be used as a template for the `.jsonnet` file loaded by my application which patches the necessary fields with data from environment variables etc.

3: This is due to the configuration files being generated alongside the kubernetes resource files (also jsonnet) and placed into an object which kubernetes uses for uploading configurations. 

The desired yaml output from jsonnet would be. Meaning that the value for `data.` needs to be rendered jsonnet with preferably partial evaluation.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: default
data:
  application.jsonnet: |-
    local someDeploymentConfiguration = import "deploy-config.libsonnet"
    {
      foo: std.extVar("VARIABLE_WHEN_DEPLOYING"),
      bar: std.extVar("VARIABLE_ON_SERVER")
    }
```

**Comment by sbarzowski** [comment]
My recommendation would be to go forward with (2). I would probably organize the code along these lines:
* Most of the logic resides in a function Application(server_data, runtime_data) which produces a final JSON used by the application at runtime. 
* On server you serialize the server-side data to JSON.
* On the application side you gather the serialized data and all the application-level inputs from the server and call the function.
Of course I don't know the details, so it may not make sense in your case.

Regarding partial evaluation, we currently do not support anything similar to what you describe. There are many problems with that (not all values can be turned back into Jsonnet source and it's often ambiguous what can and what cannot be partially evaluated). You should always be able to get the results of partial evaluation by extracting values unknown at partial evaluation time to  function parameters, serialize any additional data you need and create a "closure" this way. This way is probably easier to debug and test, and more in line with what you would do in other programming languages. 

Ah, and technically you can of course produce Jsonnet code with custom manifester. You could then support something like that:
```
{
  foo: value_inserted_at_runtime,
  bar: lib.quoted("std.extVar('VARIABLE_ON_RUNTIME_SERVER')")
}
```
You can construct _a string_ with snippets of Jsonnet code and have a custom manifester to stitch it together (just like JSON manifester, but skipping the quotation marks for strings marked as Jsonnet). This may make sense if your case is really simple (e.g. only extVars and simple expressions), but generally I wouldn't recommend that.

**Comment by sbarzowski** [comment]
I'm closing this for now. Feel free to reopen if you have any further questions and/or proposals.
