### ISSUE TITLE
undefined symbol: _Z15jsonnet_desugarP9AllocatorRP3AST

### ISSUE THREAD

**Issue by dgarstang** [google/jsonnet#81]
Currently getting this:

```
(venv)root@default-vagrant:~# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _jsonnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /root/venv/local/lib/python2.7/site-packages/_jsonnet.so: undefined symbol: _Z15jsonnet_desugarP9AllocatorRP3AST
```

Latest refresh of Ubuntu 14.04.

Doug

**Comment by sparkprime** [comment]
Missed a file in the setup.py, should be fixed now

sudo pip install jsonnet --upgrade

**Comment by dgarstang** [comment]
Thanks David. I probably shouldn't have been building from the master branch anyway. I just tried v0.8.4 and seem to have the same issue. I guess, even though you've fixed it in the master branch, I'd prefer to pull from a specific release to not have this happen again. Any ideas?

**Comment by sparkprime** [comment]
In fact the release was broken but I just pushed a new one to pip to fix
it.  Since it seems you prefer to build from setup.py, I'll create a new
tag on github with this fix.

**Comment by sparkprime** [comment]
Fixed in 0a15204876feec2f810a281e24cc346848984bfe

**Comment by cristicbz** [comment]
@sparkprime This doesn't seem to be fixed in pip. Doing `pip install jsonnet` installs 0.8.4, which breaks in the way described in the original issue.

**Comment by sparkprime** [comment]
I verified, will do a new release to fix this.
