### ISSUE TITLE
[Python bindings] Release the GIL when evaluating jsonnet code

### ISSUE THREAD

**Issue by palkeo** [google/jsonnet#813]
Hi,

It's good practice for libraries that can block for a long time in non-Python code to release the Python Global Interpreter Lock.

Given that non-trivial Jsonnet files can be slow to evaluate (I work with some files that take 100+ ms) it's would allow other Python threads of the same process to run during the computation.

See: https://docs.python.org/3/c-api/init.html#thread-state-and-the-global-interpreter-lock

I'm sending a companion PR as well.

**Comment by sbarzowski** [comment]
Fixed in #814.
