### ISSUE TITLE
Javascript binding via Gopherjs

### ISSUE THREAD

**Issue by buremba** [google/jsonnet#818]
Is there any plan to release a new binding for Javascript using GopherJS instead of Emscripten? We have a discussion here as well: https://groups.google.com/forum/#!topic/jsonnet/FjZoPFvdTaA

**Comment by sbarzowski** [comment]
It's something we definitely want to try. We just haven't got to it yet. If you (or anyone) want to help with this, it will be very much appreciated :-).

**Comment by buremba** [comment]
I had a hard time reproducing the same steps initially because I don't know Go. :( We managed to get the output via using Docker images of Gopherjs and made it work in JS but proper support would be using Gopherjs bindings in the library to be able to make the VM work in Javascript reliably.

**Comment by buremba** [comment]
@sbarzowski should we move this issue to https://github.com/google/go-jsonnet as this repo only contains the C++ version?

**Comment by sbarzowski** [comment]
Yeah. We already have https://github.com/google/go-jsonnet/issues/295, so I think we can track it there.

**Comment by buremba** [comment]
Thanks! 👍
