### ISSUE TITLE
Allow empty lines in multi-line blocks

### ISSUE THREAD

**Issue by slnovak** [google/jsonnet#82]
Hi,

I noticed that having empty lines in a multi-line block renders a `Text bock not terminated with |||` exception.

Example:

```
{
  message: |||
    Hello

    World
  |||
}
```
(note the blank line has no spaces)

results in:

```
STATIC ERROR: test.jsonnet:2:12: Text block not terminated with |||
```

YAML on the other hand allows you to have empty lines without spaces for indentation. Example:

```yaml
message: |
  Hello

  World
````

**Comment by sparkprime** [comment]
Good point, and probably a one-line fix :)
