### ISSUE TITLE
Allow `<` on arrays.

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#834]
I was sure it was supported. This is a very natural thing to have – otherwise the only way to compare complex values is to serialize them to strings/numbers.

It is trivial in go-jsonnet, but it may be a bit tricky here (need to a new FRAME_BUILTIN_x).

**Comment by seh** [comment]
What does it mean, though? Do the two arrays have to have the same length? If they don't, do you compare any of the elements, or is the shorter array always less than the longer array?

**Comment by sbarzowski** [comment]
It would mean the same thing as on strings or [std::lexicographical_compare in C++](https://en.cppreference.com/w/cpp/algorithm/lexicographical_compare) or [comparisons in Python](https://docs.python.org/3/tutorial/datastructures.html#comparing-sequences-and-other-types). 

So the two arrays would be compared element by element. In case one is a prefix of the other, the shorter one is smaller.

It would allow doing things like: `std.sort(cars, keyF=function(car) [car.brand, car.price])` to sort the cars first by brand and then by price.

**Comment by sbarzowski** [comment]
BTW I thought it already works this way and I put it in the language reference (which is now inaccurate about this): https://jsonnet.org/ref/language.html#array. @sparkprime read that stuff and didn't catch it, so I guess it really does fit in :-).

**Comment by seh** [comment]
> It would mean the same thing as on strings or [std::lexicographical_compare in C++](https://en.cppreference.com/w/cpp/algorithm/lexicographical_compare) or [comparisons in Python](https://docs.python.org/3/tutorial/datastructures.html#comparing-sequences-and-other-types).

That makes sense. I was going to appeal to precedent like that, but I wasn't sure if you were thinking of something simpler and less powerful. The bit about being able to specify fields for a lexicographical comparison—without needing to write the chaining comparisons manually—is a nice touch.

**Comment by sbarzowski** [comment]
Implemented in #846.
