### ISSUE TITLE
Linux Dashboards are showing Windows pods

### ISSUE THREAD

**Issue by sachinmsft** [google/jsonnet#837]
Hi,
Dashboard **Kubernetes / Compute Resources / Pod**  is showing Windows pod also in drop down.
reason is that we are getting all the pods form the kube_pod_info 

label_values(kube_pod_info{%(clusterLabel)s="$cluster", namespace="$namespace"}, pod)' % $._config.clusterLabel

I tried to solve it by using container_network_receive_packets_total metrics instead of kube_pod_info but this metrics does not have cluster information to filter the pods for cluster.

what is the correct way to fix this ?

**Comment by sbarzowski** [comment]
I think you opened this issue in a wrong repo. This repo is for the programming language itself. This is clearly problem with some library. Based on your example, I'm guessing https://github.com/grafana/grafonnet-lib.

**Comment by sachinmsft** [comment]
Ah. Thanks @sbarzowski 
I wanted to open it on https://github.com/kubernetes-monitoring/kubernetes-mixin

Closed it here.
