### ISSUE TITLE
`TypeError: bad argument type for built-in operation` when using integers in ext_vars 

### ISSUE THREAD

**Issue by bendavis78** [google/jsonnet#873]
If I have an integer value in `ext_vars`, I get a `TypeError`:

```python
>>> ext_vars = {"some_id": 5000}
>>> json_str = _jsonnet.evaluate_file('test.jsonnet', ext_vars=ext_vars)

TypeError: bad argument type for built-in operation
```

**Comment by sbarzowski** [comment]
It may feel awkward from Python perspective, but ext_vars can only be verbatim strings.

You can use ext_codes to pass arbitrary Jsonnet. So, in particular, if you have non-string data, you can pass it as serialized JSON (e.g. with `json.dumps`) and pass it through ext_codes.
