### ISSUE TITLE
Failed to install jsonnet with pip

### ISSUE THREAD

**Issue by wutong8023** [google/jsonnet#874]
`
 [twu@m3-login2 few-joint]$ pip install jsonnet
Collecting jsonnet
  Using cached jsonnet-0.17.0.tar.gz (259 kB)
Building wheels for collected packages: jsonnet
  Building wheel for jsonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /fs03/da33/tong/envs/astone_few_joint/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-knbtzu_3
       cwd: /tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_ext
  g++ -c -I/usr/local/gcc/5.4.0/include -Iinclude -Ithird_party/md5 -Ithird_party/json core/desugarer.cpp -o core/desugarer.o
  In file included from core/lexer.h:30:0,
                   from core/ast.h:29,
                   from core/desugarer.cpp:21:
  core/unicode.h:30:31: error: ‘encode_utf8’ declared as an ‘inline’ variable
   static inline int encode_utf8(char32_t x, std::string &s)
                                 ^
  core/unicode.h:30:31: error: ‘char32_t’ was not declared in this scope
  core/unicode.h:30:55: error: expected primary-expression before ‘&’ token
   static inline int encode_utf8(char32_t x, std::string &s)
                                                         ^
  core/unicode.h:30:56: error: ‘s’ was not declared in this scope
   static inline int encode_utf8(char32_t x, std::string &s)
                                                          ^
  core/unicode.h:30:57: error: expression list treated as compound expression in initializer [-fpermissive]
   static inline int encode_utf8(char32_t x, std::string &s)
                                                           ^
  core/unicode.h:31:1: error: expected ‘,’ or ‘;’ before ‘{’ token
   {
   ^
  make: *** [core/desugarer.o] Error 1
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py", line 75, in <module>
      test_suite="python._jsonnet_test",
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py", line 54, in run
      raise Exception('Could not build %s' % (', '.join(LIB_OBJECTS)))
  Exception: Could not build core/desugarer.o, core/formatter.o, core/libjsonnet.o, core/lexer.o, core/parser.o, core/pass.o, core/static_analysis.o, core/string_utils.o, core/vm.o, third_party/md5/md5.o

  ERROR: Failed building wheel for jsonnet
  Running setup.py clean for jsonnet
Failed to build jsonnet
Installing collected packages: jsonnet
    Running setup.py install for jsonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /fs03/da33/tong/envs/astone_few_joint/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uuzo2kyy/install-record.txt --single-version-externally-managed --compile --install-headers /fs03/da33/tong/envs/astone_few_joint/include/python3.6m/jsonnet
         cwd: /tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/
    Complete output (53 lines):
    running install
    running build
    running build_ext
    g++ -c -I/usr/local/gcc/5.4.0/include -Iinclude -Ithird_party/md5 -Ithird_party/json core/desugarer.cpp -o core/desugarer.o
    In file included from core/lexer.h:30:0,
                     from core/ast.h:29,
                     from core/desugarer.cpp:21:
    core/unicode.h:30:31: error: ‘encode_utf8’ declared as an ‘inline’ variable
     static inline int encode_utf8(char32_t x, std::string &s)
                                   ^
    core/unicode.h:30:31: error: ‘char32_t’ was not declared in this scope
    core/unicode.h:30:55: error: expected primary-expression before ‘&’ token
     static inline int encode_utf8(char32_t x, std::string &s)
                                                           ^
    core/unicode.h:30:56: error: ‘s’ was not declared in this scope
     static inline int encode_utf8(char32_t x, std::string &s)
                                                            ^
    core/unicode.h:30:57: error: expression list treated as compound expression in initializer [-fpermissive]
     static inline int encode_utf8(char32_t x, std::string &s)
                                                             ^
    core/unicode.h:31:1: error: expected ‘,’ or ‘;’ before ‘{’ token
     {
     ^
    make: *** [core/desugarer.o] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py", line 75, in <module>
        test_suite="python._jsonnet_test",
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/fs03/da33/tong/envs/astone_few_joint/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py", line 54, in run
        raise Exception('Could not build %s' % (', '.join(LIB_OBJECTS)))
    Exception: Could not build core/desugarer.o, core/formatter.o, core/libjsonnet.o, core/lexer.o, core/parser.o, core/pass.o, core/static_analysis.o, core/string_utils.o, core/vm.o, third_party/md5/md5.o
    ----------------------------------------
ERROR: Command errored out with exit status 1: /fs03/da33/tong/envs/astone_few_joint/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j0jzuakk/jsonnet_01083fc06dfa4c8dbd1575e27c81e589/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uuzo2kyy/install-record.txt --single-version-externally-managed --compile --install-headers /fs03/da33/tong/envs/astone_few_joint/include/python3.6m/jsonnet Check the logs for full command output.

`

**Comment by sbarzowski** [comment]
Thanks for reporting. The errors look very weird. It might be something wrong with your build chain. What happens when you build Jsonnet normally, from git?

```
git clone git@github.com:google/jsonnet.git
cd jsonnet
make
```

**Comment by VivaLaRobo** [comment]
Having the same issue on our Windows VMs. Same error message when installing via pip. Python is setup via Anaconda. I am able to clone the repo and run "make" successfully though.

**Comment by VivaLaRobo2** [comment]
Having the same issue on our Windows VMs. Same error message when installing via pip. Python is setup via Anaconda. I am able to clone the repo and run "make" successfully though.

**Comment by sbarzowski** [comment]
I think I have a fix here: https://github.com/sbarzowski/jsonnet/tree/fix-missing-header

Can someone who experienced this problem check it out and run the following command?
```
python setup.py build
```

I have no way of reproducing the problem locally, so this is the only way for me to confirm that it actually worked.

**Comment by VivaLaRobo2** [comment]
@sbarzowski thanks! I will test and report back

**Comment by VivaLaRobo2** [comment]
Looks like I get a different error:

```
fatal error LNK1143: invalid or corrupt file: no symbol for COMDAT section 0x5

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1143
```

**Comment by sbarzowski** [comment]
Can you paste the whole log? I'm wondering if the compilation itself went through fine (it probably did).  

This error appears when trying to use with VS linker with the object files produced by GCC. This is probably caused by Python fetching some system-specific default and our Makefile defaulting to GCC. 

You can try to fix this by setting LDSHARED env var (but I'm not sure how it works on Windows).

**Comment by wutong8023** [comment]
((od -v -Anone -t u1 stdlib/std.jsonnet \
        | tr " " "\n" \
        | grep -v "^$" \
        | tr "\n" "," ) && echo "0") > core/std.jsonnet.h
echo >> core/std.jsonnet.h
g++ -c -I/usr/local/gcc/5.4.0/include -Iinclude -Ithird_party/md5 -Ithird_party/json core/desugarer.cpp -o core/desugarer.o
In file included from core/lexer.h:30:0,
                 from core/ast.h:29,
                 from core/desugarer.cpp:21:
core/unicode.h: In function ‘void encode_utf8(const UString&, std::__cxx11::string&)’:
core/unicode.h:128:24: warning: range-based ‘for’ loops only available with -std=c++11 or -std=gnu++11
     for (char32_t cp : s)
                        ^
core/unicode.h: In member function ‘UStringStream& UStringStream::operator<<(T)’:
core/unicode.h:174:23: warning: range-based ‘for’ loops only available with -std=c++11 or -std=gnu++11
         for (char c : ss.str())
                       ^
In file included from core/ast.h:29:0,
                 from core/desugarer.cpp:21:
core/lexer.h: In function ‘void fodder_push_back(Fodder&, const FodderElement&)’:
core/lexer.h:145:15: error: ‘Fodder {aka class std::vector<FodderElement>}’ has no member named ‘emplace_back’
             a.emplace_back(FodderElement::PARAGRAPH, elem.blanks, elem.indent, elem.comment);
               ^
core/lexer.h:153:15: error: ‘Fodder {aka class std::vector<FodderElement>}’ has no member named ‘emplace_back’
             a.emplace_back(FodderElement::LINE_END, 0, elem.indent, std::vector<std::string>());
               ^
core/lexer.h: In function ‘void ensureCleanNewline(Fodder&)’:
core/lexer.h:196:85: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         fodder_push_back(fodder, FodderElement(FodderElement::Kind::LINE_END, 0, 0, {}));
                                                                                     ^
core/lexer.h:196:47: error: expected primary-expression before ‘(’ token
         fodder_push_back(fodder, FodderElement(FodderElement::Kind::LINE_END, 0, 0, {}));
                                               ^
core/lexer.h:196:63: error: ‘FodderElement::Kind’ is not a class or namespace
         fodder_push_back(fodder, FodderElement(FodderElement::Kind::LINE_END, 0, 0, {}));
                                                               ^
core/lexer.h:196:85: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         fodder_push_back(fodder, FodderElement(FodderElement::Kind::LINE_END, 0, 0, {}));
                                                                                     ^
core/lexer.h: In function ‘int countNewlines(const Fodder&)’:
core/lexer.h:214:22: error: ISO C++ forbids declaration of ‘elem’ with no type [-fpermissive]
     for (const auto &elem : fodder) {
                      ^
core/lexer.h:214:29: warning: range-based ‘for’ loops only available with -std=c++11 or -std=gnu++11
     for (const auto &elem : fodder) {
                             ^
core/lexer.h:215:34: error: no matching function for call to ‘countNewlines(const int&)’
         sum += countNewlines(elem);
                                  ^
core/lexer.h:200:19: note: candidate: int countNewlines(const FodderElement&)
 static inline int countNewlines(const FodderElement &elem)
                   ^
core/lexer.h:200:19: note:   no known conversion for argument 1 from ‘const int’ to ‘const FodderElement&’
core/lexer.h:211:19: note: candidate: int countNewlines(const Fodder&)
 static inline int countNewlines(const Fodder &fodder)
                   ^
core/lexer.h:211:19: note:   no known conversion for argument 1 from ‘const int’ to ‘const Fodder& {aka const std::vector<FodderElement>&}’
core/lexer.h: In function ‘std::ostream& operator<<(std::ostream&, const Fodder&)’:
core/lexer.h:223:22: error: ISO C++ forbids declaration of ‘f’ with no type [-fpermissive]
     for (const auto &f : fodder) {
                      ^
core/lexer.h:223:26: warning: range-based ‘for’ loops only available with -std=c++11 or -std=gnu++11
     for (const auto &f : fodder) {
                          ^
In file included from core/desugarer.cpp:21:0:
core/ast.h: In constructor ‘ArgParam::ArgParam(const Fodder&, const Identifier*, const Fodder&)’:
core/ast.h:152:45: error: ‘nullptr’ was not declared in this scope
         : idFodder(id_fodder), id(id), expr(nullptr), commaFodder(comma_fodder)
                                             ^
core/ast.h: In constructor ‘ArgParam::ArgParam(AST*, const Fodder&)’:
core/ast.h:157:14: error: ‘nullptr’ was not declared in this scope
         : id(nullptr), expr(expr), commaFodder(comma_fodder)
              ^
core/ast.h: In constructor ‘BuiltinFunction::BuiltinFunction(const LocationRange&, const string&, const Identifiers&)’:
core/ast.h:375:47: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         : AST(lr, AST_BUILTIN_FUNCTION, Fodder{}), name(name), params(params)
                                               ^
core/ast.h: In constructor ‘Index::Index(const LocationRange&, const Fodder&, AST*, const Fodder&, const Fodder&, const Identifier*)’:
core/ast.h:480:17: error: ‘nullptr’ was not declared in this scope
           index(nullptr),
                 ^
core/ast.h: In constructor ‘Index::Index(const LocationRange&, const Fodder&, AST*, const Fodder&, bool, AST*, const Fodder&, AST*, const Fodder&, AST*, const Fodder&)’:
core/ast.h:501:14: error: ‘nullptr’ was not declared in this scope
           id(nullptr)
              ^
core/ast.h: In constructor ‘LiteralNumber::LiteralNumber(const LocationRange&, const Fodder&, const string&)’:
core/ast.h:567:37: error: ‘nullptr’ was not declared in this scope
           value(strtod(str.c_str(), nullptr)),
                                     ^
In file included from /usr/local/gcc/5.4.0/include/c++/5.4.0/cassert:43:0,
                 from core/lexer.h:20,
                 from core/ast.h:29,
                 from core/desugarer.cpp:21:
core/ast.h: In constructor ‘ObjectField::ObjectField(ObjectField::Kind, const Fodder&, const Fodder&, const Fodder&, const Fodder&, ObjectField::Hide, bool, bool, AST*, const Identifier*, const LocationRange&, const ArgParams&, bool, const Fodder&, AST*, AST*, const Fodder&)’:
core/ast.h:674:43: error: ‘nullptr’ was not declared in this scope
         assert(kind != FIELD_ID || (id != nullptr && expr1 == nullptr));
                                           ^
In file included from core/desugarer.cpp:21:0:
core/ast.h: In static member function ‘static ObjectField ObjectField::Local(const Fodder&, const Fodder&, const Fodder&, const Fodder&, bool, const Identifier*, const ArgParams&, bool, const Fodder&, AST*, const Fodder&)’:
core/ast.h:693:28: error: ‘nullptr’ was not declared in this scope
                            nullptr,
                            ^
core/ast.h: In static member function ‘static ObjectField ObjectField::Local(const Fodder&, const Fodder&, const Identifier*, const Fodder&, AST*, const Fodder&)’:
core/ast.h:709:34: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
                            Fodder{},
                                  ^
core/ast.h:710:34: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
                            Fodder{},
                                  ^
core/ast.h:714:28: error: ‘nullptr’ was not declared in this scope
                            nullptr,
                            ^
core/ast.h:717:37: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
                            ArgParams{},
                                     ^
core/ast.h: In static member function ‘static ObjectField ObjectField::LocalMethod(const Fodder&, const Fodder&, const Fodder&, const Fodder&, const Identifier*, const ArgParams&, bool, const Fodder&, AST*, const Fodder&)’:
core/ast.h:738:28: error: ‘nullptr’ was not declared in this scope
                            nullptr,
                            ^
core/ast.h: In static member function ‘static ObjectField ObjectField::Assert(const Fodder&, AST*, const Fodder&, AST*, const Fodder&)’:
core/ast.h:753:34: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
                            Fodder{},
                                  ^
core/ast.h:754:34: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
                            Fodder{},
                                  ^
core/ast.h:755:34: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
                            Fodder{},
                                  ^
core/ast.h:759:28: error: ‘nullptr’ was not declared in this scope
                            nullptr,
                            ^
core/ast.h:762:37: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
                            ArgParams{},
                                     ^
core/ast.h: In constructor ‘DesugaredObject::DesugaredObject(const LocationRange&, const ASTs&, const Fields&)’:
core/ast.h:812:47: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         : AST(lr, AST_DESUGARED_OBJECT, Fodder{}), asserts(asserts), fields(fields)
                                               ^
core/ast.h: In constructor ‘ObjectComprehensionSimple::ObjectComprehensionSimple(const LocationRange&, AST*, AST*, const Identifier*, AST*)’:
core/ast.h:844:58: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         : AST(lr, AST_OBJECT_COMPREHENSION_SIMPLE, Fodder{}),
                                                          ^
core/ast.h: At global scope:
core/ast.h:948:29: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class T, class... Args>
                             ^
core/ast.h:949:18: error: expected ‘,’ or ‘...’ before ‘&&’ token
     T *make(Args &&... args)
                  ^
core/ast.h:949:28: error: parameter packs not expanded with ‘...’:
     T *make(Args &&... args)
                            ^
core/ast.h:949:28: note:         ‘Args’
core/ast.h: In member function ‘T* Allocator::make(<type error>)’:
core/ast.h:951:14: error: ‘r’ does not name a type
         auto r = new T(std::forward<Args>(args)...);
              ^
core/ast.h:952:29: error: ‘r’ was not declared in this scope
         allocated.push_back(r);
                             ^
core/ast.h: In member function ‘T* Allocator::clone(T*)’:
core/ast.h:959:14: error: ‘r’ does not name a type
         auto r = new T(*ast);
              ^
core/ast.h:960:29: error: ‘r’ was not declared in this scope
         allocated.push_back(r);
                             ^
core/ast.h: In member function ‘const Identifier* Allocator::makeIdentifier(const UString&)’:
core/ast.h:969:14: error: ‘it’ does not name a type
         auto it = internedIdentifiers.find(name);
              ^
core/ast.h:970:13: error: ‘it’ was not declared in this scope
         if (it != internedIdentifiers.end()) {
             ^
core/ast.h:973:14: error: ‘r’ does not name a type
         auto r = new Identifier(name);
              ^
core/ast.h:974:37: error: ‘r’ was not declared in this scope
         internedIdentifiers[name] = r;
                                     ^
core/ast.h: In destructor ‘Allocator::~Allocator()’:
core/ast.h:979:19: error: ‘x’ does not name a type
         for (auto x : allocated) {
                   ^
core/ast.h:982:9: error: expected ‘;’ before ‘allocated’
         allocated.clear();
         ^
core/ast.h:982:24: error: could not convert ‘((Allocator*)this)->Allocator::allocated.std::__cxx11::list<_Tp, _Alloc>::clear<AST*, std::allocator<AST*> >()’ from ‘void’ to ‘bool’
         allocated.clear();
                        ^
core/ast.h:983:9: error: expected primary-expression before ‘for’
         for (const auto &x : internedIdentifiers) {
         ^
core/ast.h:983:9: error: expected ‘)’ before ‘for’
core/ast.h:983:26: error: ISO C++ forbids declaration of ‘x’ with no type [-fpermissive]
         for (const auto &x : internedIdentifiers) {
                          ^
core/ast.h:983:30: warning: range-based ‘for’ loops only available with -std=c++11 or -std=gnu++11
         for (const auto &x : internedIdentifiers) {
                              ^
core/ast.h:984:22: error: request for member ‘second’ in ‘x’, which is of non-class type ‘const int’
             delete x.second;
                      ^
core/ast.h: At global scope:
core/ast.h:1078:6: error: ‘precedence_map’ does not name a type
 auto precedence_map = build_precedence_map();
      ^
core/ast.h:1079:6: error: ‘unary_map’ does not name a type
 auto unary_map = build_unary_map();
      ^
core/ast.h:1080:6: error: ‘binary_map’ does not name a type
 auto binary_map = build_binary_map();
      ^
core/desugarer.cpp: In function ‘BuiltinDecl jsonnet_builtin_decl(long unsigned int)’:
core/desugarer.cpp:41:24: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         case 0: return {U"makeArray", {U"sz", U"func"}};
                        ^
core/desugarer.cpp:41:25: error: ‘U’ was not declared in this scope
         case 0: return {U"makeArray", {U"sz", U"func"}};
                         ^
core/desugarer.cpp:41:26: error: expected ‘}’ before string constant
         case 0: return {U"makeArray", {U"sz", U"func"}};
                          ^
core/desugarer.cpp:41:26: error: could not convert ‘{<expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘BuiltinDecl’
core/desugarer.cpp:41:26: error: expected ‘;’ before string constant
core/desugarer.cpp:41:39: error: expected primary-expression before ‘{’ token
         case 0: return {U"makeArray", {U"sz", U"func"}};
                                       ^
core/desugarer.cpp:42:9: error: case label ‘1’ not within a switch statement
         case 1: return {U"pow", {U"x", U"n"}};
         ^
core/desugarer.cpp:42:24: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
         case 1: return {U"pow", {U"x", U"n"}};
                        ^
core/desugarer.cpp:42:25: error: ‘U’ was not declared in this scope
         case 1: return {U"pow", {U"x", U"n"}};
                         ^
core/desugarer.cpp:42:26: error: expected ‘}’ before string constant
         case 1: return {U"pow", {U"x", U"n"}};
                          ^
core/desugarer.cpp:42:26: error: could not convert ‘{<expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘BuiltinDecl’
core/desugarer.cpp:42:26: error: expected ‘;’ before string constant
core/desugarer.cpp:42:33: error: expected primary-expression before ‘{’ token
         case 1: return {U"pow", {U"x", U"n"}};
                                 ^
core/desugarer.cpp: At global scope:
core/desugarer.cpp:43:9: error: expected unqualified-id before ‘case’
         case 2: return {U"floor", {U"x"}};
         ^
make: *** [core/desugarer.o] Error 1

**Comment by wutong8023** [comment]
(astone_fewjoint) [twu@m3-login1 ~]$ git clone https://github.com/google/jsonnet.git
Cloning into 'jsonnet'...
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 12906 (delta 69), reused 63 (delta 33), pack-reused 12767
Receiving objects: 100% (12906/12906), 41.38 MiB | 8.83 MiB/s, done.
Resolving deltas: 100% (6857/6857), done.
Checking out files: 100% (4001/4001), done.
(astone_fewjoint) [twu@m3-login1 ~]$ ls
astone_start  da33_scratch  jsonnet-master        slurm-mpi-job-script                slurm-openmp-job-script  smux-17103082.err  smux-17103256.err
da33          jsonnet       slurm-gpu-job-script  slurm-mpi_openmp_hybrid-job-script  slurm-serial-job-script  smux-17103082.out  smux-17103256.out
(astone_fewjoint) [twu@m3-login1 ~]$ cd jsonnet
(astone_fewjoint) [twu@m3-login1 jsonnet]$ make
((od -v -Anone -t u1 stdlib/std.jsonnet \
        | tr " " "\n" \
        | grep -v "^$" \
        | tr "\n" "," ) && echo "0") > core/std.jsonnet.h
echo >> core/std.jsonnet.h
g++ -c -I/usr/local/gcc/5.4.0/include -Iinclude -Ithird_party/md5 -Ithird_party/json core/desugarer.cpp -o core/desugarer.o
In file included from core/lexer.h:30:0,
                 from core/ast.h:29,
                 from core/desugarer.cpp:21:
core/unicode.h:30:31: error: ‘encode_utf8’ declared as an ‘inline’ variable
 static inline int encode_utf8(char32_t x, std::string &s)
                               ^
core/unicode.h:30:31: error: ‘char32_t’ was not declared in this scope
core/unicode.h:30:55: error: expected primary-expression before ‘&’ token
 static inline int encode_utf8(char32_t x, std::string &s)
                                                       ^
core/unicode.h:30:56: error: ‘s’ was not declared in this scope
 static inline int encode_utf8(char32_t x, std::string &s)
                                                        ^
core/unicode.h:30:57: error: expression list treated as compound expression in initializer [-fpermissive]
 static inline int encode_utf8(char32_t x, std::string &s)
                                                         ^
core/unicode.h:31:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
make: *** [core/desugarer.o] Error 1

**Comment by wutong8023** [comment]
Hi @sbarzowski, thanks for your suggestions. I just tried them on Australian M3, and got the full log above. It is still a wired error, would you please have a further check over it？

**Comment by sbarzowski** [comment]
Thanks. The problem should go away if you upgrade the compiler to a newer version. You compiler version is over 4 years old.

We might still want to fix this if there is an easy way. One fix I tried (https://github.com/sbarzowski/jsonnet/tree/fix-missing-header) causes problems with some other compiler versions.

**Comment by wutong8023** [comment]
Thank you @sbarzowski , I will have a try today.

**Comment by wutong8023** [comment]
[twu@m3-login1 jsonnet]$ make
g++ -L/usr/local/cmake/3.15.4-gcc8/lib -L/usr/local/gcc/8.1.0/lib64 core/desugarer.o core/formatter.o core/lexer.o core/libjsonnet.o core/parser.o core/pass.o core/static_analysis.o core/string_utils.o core/vm.o third_party/md5/md5.o -shared -Wl,-soname,libjsonnet.so.0 -o libjsonnet.so.0.17.0
/bin/ld: core/desugarer.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: core/formatter.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: core/lexer.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: core/libjsonnet.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: core/parser.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: core/pass.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: core/static_analysis.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: core/string_utils.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: core/vm.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: third_party/md5/md5.o: relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [libjsonnet.so.0.17.0] Error 1

**Comment by wutong8023** [comment]
Hi @sbarzowski, sorry for all of my questions. I loaded a higher version gcc module today, yet got the listed error. Would you please share some ideas with me?

**Comment by wutong8023** [comment]
Hi @sbarzowski, thank you for all your help! Finally, succeed!
