### ISSUE TITLE
Looking for migration tool and rename variable tool

### ISSUE THREAD

**Issue by loynoir** [google/jsonnet#906]
1. Are there any tools or workaround, can convert yaml to jsonnet, while keeping comments?
Or saying migration tool.

2.  Related to issues/862, are there any workaround, can rename variable thru pointer?
 Like <F2> in vscode, changing variable from `foo=42` to `bar=42` in `fileA`, will update variable thru pointer in `fileA` and `fileB`?

**Comment by sbarzowski** [comment]
1) Yes:  https://github.com/waisbrot/yaml2jsonnet. See #765. I haven't tried it personally, though.
2) I don't understand the question, sorry. Could you provide more context? Do you want to perform some automated refactoring?

**Comment by loynoir** [comment]
### Prepare
```js
// A.ts
export const A = 42

// B.ts
import { A } from './A'
console.log(A)
```

### Rename Variable
*Action*

Press `<F2>` "Rename Symbols" within vscode

*Before*
```js
// A.ts
export const <HERE>A</HERE> = 42
```
*After*
```js
// A.ts
export const A2 = 42
```

*Vscode Automated*
```txt
import { A2 } from './A'
console.log(A2)
```

### Rename File
*Action*

Press `<F2>` within vscode explorer,  change filename from 'A.ts' to 'A2.ts'

*Before*
```txt
$ tree
.
├── A.ts
└── B.ts
```
*After*
```txt
$ tree
.
├── A2.ts
└── B.ts
```

*Vscode Automated*
```js
// B.ts
import { A2 } from './A2'
console.log(A2)
```

**Comment by loynoir** [comment]
Guess it is done by language server.

**Comment by sbarzowski** [comment]
I see. We have some groundwork done to support things like that, but we don't have a proper tool yet.

By groundwork I mean that we have library support for analyzing and modifying AST which is used for the formatter, the linter and the dependency analyzer. Internally we have functionality to find all uses of a variable. But as I said we don't have actual renaming tools or integration with VS Code. If you or someone would be interested in picking this up, I can help probably.

**Comment by sbarzowski** [comment]
> Guess it is done by language server.

It can be. My understanding is that for Typescript in particular vscode doesn't use a language server (but they could implement it this way if they wanted to).
