### ISSUE TITLE
Refering an array element without using its index

### ISSUE THREAD

**Issue by maingoh** [google/jsonnet#909]
I have an array of objects. I would like one object to depend on another one in the array, but it might not always be at the same index in the array, it would be nice to be able to reference it thanks to one of its attributes (A `name` field for example).

I know I could register each objects in a global map, but it would be nice if it was incorporated into the language. Or maybe extend it to a query language (I found out https://github.com/json-path/JsonPath maybe)

**Comment by sbarzowski** [comment]
Could you provide a more detailed description of what you're trying to accomplish? Also, I would appreciate some examples of how you imagine it would like.

**Comment by maingoh** [comment]
Sorry, I would like to identify an object in an array, either by specifiying an id or using a more generic query expression. 
The basic need would look like this:
```python
{
    "array": [{
        id:: "object_id",  // "id::" would indicate it is globally accessible using `object_id`; this field is hidden
        "name": "my_name"
    }, {
        id:: "object_id2",
        "name": "%s2" % object_id.name,
    }]
}
```
Alternatively this makes me think about how javascript can query inside a HTML DOM depending on attributes:
```python
{
    "array": [{
        "id": "object_id",
        "name": "my_name"
    }, {
        "id": "object_id2",
        "name": "%s2" % self.parent.find('[id=object_id]')[0].name,
    }]
}
```
Or using the JSONPath syntax which seem to be a good fit.

**Comment by sbarzowski** [comment]
I see. There are two approaches to this.

First is that you can often just give your element a name. This is especially useful if you want self-reference within on element of the array:
```
[   
    {
        "id": "object_id",
        "name": "my_name"
    }, local obj = {
        "id": "object_id2",
        "name": "object with id: " + obj.id,
    }; obj
]
```
You can also introduce named values before constructing the array and have them reference each other:
```
local obj1 = {
  "id": "object_id",
  "name": "my_name"
}, obj2 = {
  id: obj1.id + " 2",
  name: obj1.name + " 2"
};
[
  obj1,
  obj2
]
```
The second way is to do what you described with array comprehensions:
```
{
    "array": [{
        "id": "object_id",
        "name": "my_name"
    }, {
        "id": "object_id2",
        "name": "%s2" % [x for x in $.array if x.id == "object_id"][0].name
    }],
}
```
In most cases I would expect the 2nd approach to be harder to read (and also much slower).
