### ISSUE TITLE
Using tla with Python Jsonnet binding

### ISSUE THREAD

**Issue by Jeet007** [google/jsonnet#911]
I am new to Jsonnet and trying to use it via python binding for templatizing.  I have a top level function in a test.libsonnet file like below: 
```
function(y) {
   local func = (import 'func.libsonnet')(y['x']),
    local test =  {
        "test" : y['x']
    },
    local test1 = ( if y['x']==3 then {
        "test1": "conditon"
    } else {}),
    return: test + test1
}.return
```

trying to call this via python. I have defined below dict: 
```
thisdict = {
  "y": {
      "x": 5
  }
}
```

Call is like below: 
```
json_str = _jsonnet.evaluate_file("test.libsonnet", tla_codes=thisdict)
```

This is giving me below error: 
```
TypeError: bad argument type for built-in operation
```

As I am new to Jsonnet, can please someone guide me on what I might be doing wrong here?

**Comment by Jeet007** [comment]
Just an update if I do json.dumps on my python dict, I am getting below error: 

`RuntimeError: RUNTIME ERROR: function parameter y not bound in call.
	Top-level function`

**Comment by sbarzowski** [comment]
@Jeet007  The `tla_codes` is supposed to be a dict from variable name to strings containing Jsonnet code. Here's what should work:
```
thisdict = {
  "y": json.dumps({
      "x": 5
  })
}
```

**Comment by sbarzowski** [comment]
BTW you don't need the `{ return: ...} .return` stuff. You can produce the value directly:

```
function(y)
  local func = (import 'func.libsonnet')(y.x),
        test = {
            test: y.x,
        },
        test1 = (if y.x == 3 then {
                   test1: 'conditon',
                 } else {});
  test + test1
```
