### ISSUE TITLE
CMake support for python extension

### ISSUE THREAD

**Issue by jcpunk** [google/jsonnet#922]
When building up the jsonnet libraries, it would be nice if I could also pass something like `BUILD_PYTHON3_SUPPORT:BOOL=ON` to get the python extension built at the same time.

And ideally, it would respect the `BUILD_SHARED_BINARIES:BOOL`....

**Comment by sbarzowski** [comment]
The PR is closed, so I suppose this can also be closed. Feel free to reopen, though.
