### ISSUE TITLE
Please tag new release?

### ISSUE THREAD

**Issue by robbat2** [google/jsonnet#925]
Hi,

It's been just over 6 months since the last tagged release.

Could you please issue a new one to include the `std.format` fix and Toml/Yaml work?

Thanks in Advance

**Comment by sbarzowski** [comment]
Yeah, it's probably about time. Thanks for the reminder. 

The release process takes quite a lot of effort due to multiple implementations, multiple platforms, Python support etc. That's why we don't do it very often.

**Comment by duedal** [comment]
Would really appreciate a new release for std.parseYaml() in particular. It enables nice workflows in upstream projects like ArgoCD.

**Comment by groodt** [comment]
I'd also appreciate a new release. I think there are a few downstream projects that would be interested such as tanka, qbec, and rules_jsonnet.

**Comment by groodt** [comment]
Any updates on an expected date for a new release?

**Comment by sparkprime** [comment]
Next week I think work will slow down for Christmas so I should be able to do it then.

**Comment by sparkprime** [comment]
I'm doing it now, however ran into a problem with a test failing...

**Comment by sparkprime** [comment]
All done
