### ISSUE TITLE
std.ParseJson fails on "1." and ".1" - dumps core

### ISSUE THREAD

**Issue by glenntrewitt** [google/jsonnet#931]
% jsonnet -e 'std.parseJson(".1")'                                                                [master]
Something went wrong during jsonnet_evaluate_snippet, please report this: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '.'

% jsonnet -e 'std.parseJson("1.")'                                                                [master]
Something went wrong during jsonnet_evaluate_snippet, please report this: [json.exception.parse_error.101] parse error at line 1, column 3: syntax error while parsing value - invalid number; expected digit after '.'; last read: '1.'

**Comment by sbarzowski** [comment]
This is not valid JSON as per spec. It should be a proper runtime error rather than a core dump, though.

**Comment by hanazuki** [comment]
Duplicate of #680

**Comment by sbarzowski** [comment]
Ok, so presumably this is fixed. Feel free to reopen if it fails on tip.
