### ISSUE TITLE
add equivalent of -c (sjsonnet) args to create output dir automatically

### ISSUE THREAD

**Issue by fvigotti** [google/jsonnet#932]
as in the title.. I find -c very useful in complex output builds, this will create automatically all required directory hierarchies in output path ,
I use both application and lacking this feature also break compatibility forcing a manual directory creation for the jsonnet binary

**Comment by sbarzowski** [comment]
We support this in https://github.com/google/go-jsonnet which is a better implementation anyway for 95% of cases (the remaining ones are cases where go runtime is unacceptable, mostly when using as a library and using `fork` without `exec`). If you use it as a command, it should be strictly better.

That said, if someone contributes the support for `-c` here, we'll accept it.

**Comment by fvigotti** [comment]
thank you, I've switched to go-jsonnet :)
