### ISSUE TITLE
install jsonnet by pip but still got command not found

### ISSUE THREAD

**Issue by Boltzmachine** [google/jsonnet#947]
I install by
```
pip install jsonnet
```
successfully.

But when I type jsonnet, it still says
```
jsonnet: command not found
```

So where is the executable installed?

**Comment by shwnyao** [comment]
same issue

**Comment by johnbartholomew** [comment]
The Python package does not (is not intended to) provide the jsonnet command line tool. There are some instructions for installing the command line tool (the Go implementation) here: https://github.com/google/go-jsonnet?tab=readme-ov-file#installation-instructions
