### ISSUE TITLE
non-go std.manifestYamlDoc and std.manifestJsonEx are (very) slow

### ISSUE THREAD

**Issue by pmorch** [google/jsonnet#953]
Here I show how a sample 166 KB json file takes 15 seconds to manifest with either `std.manifestYamlDoc()` and `std.manifestJsonEx()`.

That is 457 times slower than `jq` and 56 times slower than `yq` respectively. So this is quite painful for larger structures.

What can I/we do about that?

Here is the output from `test.sh` (shown below):

```
+ wget -O sample.json 'https://docs.google.com/uc?export=download&id=14Pfp0MrnA-0M0KDzkG8bW0ZoQNGCv3wz'

+ ls -lh sample.json
-rw-r--r-- 1 peter peter 166K Dec 14 16:16 sample.json

+ jsonnet -e 'import "sample.json"'

real	0m0.087s
user	0m0.050s
sys	0m0.012s

+ jsonnet -e 'std.manifestJsonEx(import "sample.json", "")'

real	0m15.081s
user	0m15.041s
sys	0m0.040s

+ jq . sample.json

real	0m0.033s
user	0m0.033s
sys	0m0.000s

+ jsonnet -e 'std.manifestYamlDoc(import "sample.json")'

real	0m15.408s
user	0m15.398s
sys	0m0.010s

+ yq -P e . sample.json

real	0m0.275s
user	0m0.442s
sys	0m0.012s
```

`test.sh`:
```bash
#!/bin/bash
set -e
set -x
wget -O sample.json https://docs.google.com/uc\?export\=download\&id\=14Pfp0MrnA-0M0KDzkG8bW0ZoQNGCv3wz > /dev/null 2>&1

ls -lh sample.json

time jsonnet -e 'import "sample.json"' > /dev/null

time jsonnet -e 'std.manifestJsonEx(import "sample.json", "")' > /dev/null
time jq . sample.json > /dev/null

time jsonnet -e 'std.manifestYamlDoc(import "sample.json")' > /dev/null
time yq -P e . sample.json > /dev/null
```

I can see that both  [`std.manifestJsonEx`](https://github.com/google/jsonnet/blob/71a128e0c4a107b4c5dfd5b782d3ee6c48f787e9/stdlib/std.jsonnet#L1007) and [`std.manifestYamlDoc`](https://github.com/google/jsonnet/blob/71a128e0c4a107b4c5dfd5b782d3ee6c48f787e9/stdlib/std.jsonnet#L1044) are written i jsonnet.

Is that the main reason I'm seeing these performance numbers?

Using jsonnet v0.17.0

**Comment by pmorch** [comment]
I can see that both  [`std.manifestJsonEx`](https://github.com/google/jsonnet/blob/71a128e0c4a107b4c5dfd5b782d3ee6c48f787e9/stdlib/std.jsonnet#L1007) and [`std.manifestYamlDoc`](https://github.com/google/jsonnet/blob/71a128e0c4a107b4c5dfd5b782d3ee6c48f787e9/stdlib/std.jsonnet#L1044) are written i jsonnet.

Is that the main reason I'm seeing these performance numbers?

**Comment by sparkprime** [comment]
Have you tried using the go-jsonnet version?  It should be much faster.

**Comment by pmorch** [comment]
Yup... Time went from 7.06s to 0.499s - so the go version is 14 times faster in this instance :-) :

```bash
$ jsonnet --version
Jsonnet commandline interpreter v0.17.0

$ time jsonnet -J vendor helm.jsonnet > /dev/null
jsonnet -J vendor helm.jsonnet > /dev/null  7.03s user 0.03s system 99% cpu 7.061 total

$ brew uninstall jsonnet
Uninstalling /home/linuxbrew/.linuxbrew/Cellar/jsonnet/0.17.0... (6 files, 1.7MB)

$ brew install go-jsonnet
<removed>

$ jsonnet --version
Jsonnet commandline interpreter (Go implementation) v0.18.0

$ time jsonnet -J vendor helm.jsonnet > /dev/null
jsonnet -J vendor helm.jsonnet > /dev/null  0.79s user 0.07s system 173% cpu 0.499 total
```

**Comment by sparkprime** [comment]
Yeah the Go version has application level optimisations that the C++ one does not have.  It also has native implementations of more builtins.  It doesn't look like manifestJson is one of them, but it probably uses functions in its implementation that are native in the Go one (but not in the C++ one).

**Comment by sbarzowski** [comment]
@pmorch We prioritize performance work on the Go side.

We can further optimize Go version, but I don't want to spend much time on C++ implementation (I will review 3rd party PRs, if someone cares enough to send them, though). 

Closing now, but feel free to reopen / comment, if go-jsonnet is not satisfactory.
