### ISSUE TITLE
Add std.all(arr) and std.any(arr)

### ISSUE THREAD

**Issue by yegle** [google/jsonnet#954]
I'm a bit surprised there's no short hand for testing a list of boolean values in Jsonnet.

I'll admit it can be trivially implemented using `std.foldl` but still it would be convenient if it can be implemtend as part of the stdlib:

```jsonnet
// all/any implemented using std.foldl
local all(arr) = std.foldl(function(x, y) x && y, arr, true);
local any(arr) = std.foldl(function(x, y) x || y, arr, false);

{
  test_all: all([true, false]),
  test_any: any([true, false]),
}

/*
$ jsonnet test.jsonnet 
{
   "test_all": false,
   "test_any": true
}
*/
```

Example usecase: construct a predicate with multiple rules:

```jsonnet
local predicate(x) = all([
  x.foo == 'a',
  x.bar == 'b',
])
```

**Comment by sbarzowski** [comment]
Good idea. Feel free to send a PR which adds this simple implementation to stdlib.

We can think of a more efficient native implementation later, but this implementation should be the starting point.
