### ISSUE TITLE
Provide consistant binary assets

### ISSUE THREAD

**Issue by nudgegoonies** [google/jsonnet#958]
Some releases have as assets only the sources zip and tar (current 0.18 for example).
Others have only linux binaries (0.17 for example)
Others have linux, mac and windows binaries (0.14 for example)

Please provide consistant binary assets for all supported os and not shuffled for between releases.

**Comment by sparkprime** [comment]
I suspect this has something to do with us losing travis...

**Comment by loeffel-io** [comment]
I think you can go with those ones https://github.com/google/go-jsonnet/releases/tag/v0.19.1

**Comment by nudgegoonies** [comment]
Thank you, i will switch to go-jsonnet where binaries for all architectures are built.
