### ISSUE TITLE
Problematic reference in std lib. Different results from same code.

### ISSUE THREAD

**Issue by KetchupBomb** [google/jsonnet#965]
Hello Jsonnet,

I am preparing to submit a PR for expanding `std.splitLimit()` (and by extensions `std.split()`) to support multi-character delimiters.

<details>
  <summary>Example</summary>

```shell
# Current behavior
$ echo 'std.split("foo//bar", "//")' | jsonnet -
RUNTIME ERROR: std.split second parameter should have length 1, got 2
        std.jsonnet:(115:5)-(116:31)    function <anonymous>
        <stdin>:1:1-28

# PR behavior
$ echo 'std.split("foo//bar", "//")' | jsonnet -
  - foo
  - bar
```
</details>

However, I am getting inconsistent results. If I take my source code, and put in a file and run by itself, it works. But if I take the same code and slap it in to `stdlib/std.jsonnet`, it doesn't work.

<details>
  <summary>Working, local development</summary>

```json
test:
  - foo
  - bar
```

  <details>
    <summary>Source file</summary>

```jsonnet
{
  split(str, c)::
    assert std.isString(str) : 'std.split first parameter should be a string, got ' + std.type(str);
    assert std.isString(c) : 'std.split second parameter should be a string, got ' + std.type(c);
    $.splitLimit(str, c, -1),

  splitLimit(str, c, maxsplits)::
    assert std.isString(str) : 'std.splitLimit first parameter should be a string, got ' + std.type(str);
    assert std.isString(c) : 'std.splitLimit second parameter should be a string, got ' + std.type(c);
    assert std.isNumber(maxsplits) : 'std.splitLimit third parameter should be a number, got ' + std.type(maxsplits);
    local aux(str, delim, i, arr, v) = 
      local c = str[i : i + std.length(delim) : 1];
      if i >= std.length(str) then
        arr + [v]
      else if c == delim && (maxsplits == -1 || std.length(arr) < maxsplits) then
        aux(str, delim, i + std.length(c), arr + [v], '') tailstrict
      else
        aux(str, delim, i + 1, arr, v + str[i]) tailstrict;

    aux(str, c, 0, [], ''),

  test: $.split('foo//bar', '//'),
}
```
  </details>
</details>

<details>
  <summary>Non-working fork</summary>

```shell
$ git branch -v
* master 90a9f9a Explicitly define what the super keyword means in tutorial (#960)

$ make clean && make

$ echo 'std.split("foo//bar", "//")' | ./jsonnet -
[
   "foo",
   "",
   "bar"
]
```

  <details>
    <summary>Snippet of changes to stdlib/std.jsonnet</summary>

```jsonnet
  split(str, c)::
    assert std.isString(str) : 'std.split first parameter should be a string, got ' + std.type(str);
    assert std.isString(c) : 'std.split second parameter should be a string, got ' + std.type(c);
    std.splitLimit(str, c, -1),

  splitLimit(str, c, maxsplits)::
    assert std.isString(str) : 'std.splitLimit first parameter should be a string, got ' + std.type(str);
    assert std.isString(c) : 'std.splitLimit second parameter should be a string, got ' + std.type(c);
    assert std.isNumber(maxsplits) : 'std.splitLimit third parameter should be a number, got ' + std.type(maxsplits);
    local aux(str, delim, i, arr, v) = 
      local c2 = str[i : i + std.length(delim) : 1];
      if i >= std.length(str) then
        arr + [v]
      else if c2 == delim && (maxsplits == -1 || std.length(arr) < maxsplits) then
        aux(str, delim, i + std.length(c2), arr + [v], '') tailstrict
      else
        aux(str, delim, i + 1, arr, v + str[i]) tailstrict;
    aux(str, c, 0, [], ''),
```
  </details>
</details>

---

The nuanced difference here is the "`$`" usage vs "`std`" local variable between the two files respectively, but I don't think that's an immediate concern?...

For the life of me I cannot see why this is failing to work when it's nearly literally the same code, so I'm wondering if there's outside influence from files beyond `stdlib/std.jsonnet`.

Thank you for looking.

**Comment by KetchupBomb** [comment]
Preface: I am not great with C or C++ languages, nor their compilation and "extension" features. So please have patience.

It seems like `std.splitLimit()`, while defined in `stdlib/std.jsonnet`, is also a builtin to the underlying C++ binary. At least that's what `core/desugarer.cpp` and `core/vm.cpp` make me think:

https://github.com/google/jsonnet/blob/90a9f9a9693f774a26aeedd184996609faedd415/core/desugarer.cpp#L69

https://github.com/google/jsonnet/blob/90a9f9a9693f774a26aeedd184996609faedd415/core/vm.cpp#L1457

---

This would explain why, when I copy and paste my `stdlib/std.jsonnet` changes I added to a new field, call it `splitLimit2()`, it actually works:

```shell
$ echo 'std.splitLimit2("foo//bar", "//", -1)' | bazel run -c opt //cmd:jsonnet 2> /dev/null -- -
[
   "foo",
   "bar"
]
```

Does this mean I need to modify underlying C++ code to implement the changes I intended to perform in native Jsonnet? If so, what's strange is that my very first change to `std.splitLimit()` was to remove the single character assertion:

https://github.com/google/jsonnet/blob/90a9f9a9693f774a26aeedd184996609faedd415/stdlib/std.jsonnet#L121

And it actually worked! It no longer throws assertion errors when attempting to call -- it just doesn't execute _the rest_ of the code I've demonstrated.

**Comment by sbarzowski** [comment]
Yes, the reason you see different results is that there exists a builtin implementation of splitLimit. It replaces the Jsonnet implementation (the idea is that the two should be equivalent). We don't have tests to enforce this yet, but ideally we would have a development switch whether to use performance-enhancing, but non-essential builtin implementations or not.

We would need to change the builtin as well to add this functionality. It's not very complicated – https://github.com/google/jsonnet/blob/90a9f9a9693f774a26aeedd184996609faedd415/core/vm.cpp#L1469 – here is the condition for matching a single character of the separator. It can be replaced with a check for longer separator and https://github.com/google/jsonnet/blob/90a9f9a9693f774a26aeedd184996609faedd415/core/vm.cpp#L1476 will have to be changed to skip the appropriate number of characters.

A naive check for pattern match is fine (separators tend to be short, so implementing something like [KMP](https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm) is probably not worth it).

**Comment by MRSCARTER06** [comment]
- https://calendly.com/d/cgj-nrj- -mvp/meeting
