### ISSUE TITLE
Pythonic bool function

### ISSUE THREAD

**Issue by KetchupBomb** [google/jsonnet#968]
I'd like to propose a [Pythonic](https://docs.python.org/3/library/stdtypes.html#truth-value-testing) [`bool()`](https://docs.python.org/3/library/functions.html?highlight=bool#bool)-like function:

```jsonnet
std.toBool([])                        // false, empty Array
std.toBool([null])                    // true, Array with items
std.toBool(true)                      // true
std.toBool(false)                     // false
std.toBool(function() null)           // true, Functions are always true...
std.toBool(function(a) a)             // true, ...regardless of signature
std.toBool(0)                         // false
std.toBool(1)                         // true
std.toBool(-1)                        // true
std.toBool({})                        // false, empty Object
std.toBool({ foo: null })             // true, visible fields
std.toBool({ foo:: null })            // false, appears to be an empty Object
std.toBool({ foo:: null }, all=true)  // true, visible fields
std.toBool('')                        // false
std.toBool(' ')                       // true
std.toBool(null)                      // false
```

I am not sure if it ought to have an opinion on YAML conventions like mentioned in:
https://github.com/google/jsonnet/blob/ffb50aee5b246ba3342d23547ce8fa0e2d986fb0/stdlib/std.jsonnet#L1053-L1060

Should such values, like `"no"`, evaluate to `false`?

**Comment by sbarzowski** [comment]
Thanks for the suggestion.

We've considered that before, but decided it's going to bring too much confusion. You can write the conditions explicitly instead of depending on conventions like that, which isn't much more verbose, but much more clear.

Of course nothing stops you from writing a function like you propose to use in your projects.

**Comment by KetchupBomb** [comment]
Understood. I made a [`pythonic-bool` branch on my fork](https://github.com/KetchupBomb/jsonnet/tree/pythonic-bool) to do this for any future parties that are interested.

**Comment by sbarzowski** [comment]
fwiw you don't need to create a fork. You can just have a regular library you can import with whatever utilities you like...

**Comment by KetchupBomb** [comment]
I mentioned my fork for others that may search for such a function and want to utilize the code I had already written.
