### ISSUE TITLE
Broken tutorial, with stupidly high level of complexity for a beginner tutorial

### ISSUE THREAD

**Issue by richlysakowski** [google/jsonnet#999]
This is why I stay away from JavaScript and Cloud services...   

https://jsonnet.org/articles/fractal.1.html

The fractal tutorial demo referenced in the jsonnet documentation has a grossly contrived example of complexity, selecting and saving fractals using a Tiling Service to a Cassandra database, on top of Flask, Nginx, uWSGI and a C++ compiler???  WTF?? !$**##.   

Whoever came up with this contrived example was not interested in providing a good tutorial, but proving their extreme inability to express ideas simply for newcomers to learn from.  FIX this demo.  It would take hours to set this up and fix.   It is insipidly complex.  FIX IT. 

From the demo description...

"Both the Application server and the tile generation service use Nginx, uWSGI and flask to host their content. For the application Server, this means transforming HTTP requests into database accesses and/or serving content (code [here](https://github.com/google/jsonnet/blob/master/case_studies/fractal/appserv/main.py)). For the tile generation service, this means invoking a compiled C++ [executable](https://github.com/google/jsonnet/blob/master/case_studies/fractal/tilegen/mandelbrot.cpp) from the Flask [handler](https://github.com/google/jsonnet/blob/master/case_studies/fractal/tilegen/mandelbrot_service.py) in order to construct a PNG for a given tile / thumbnail of the fractal. Both services consist of a group of [instances](https://cloud.google.com/compute/docs/instances) behind a layer 3 cloud load balancer with a static IP and a simple [health check](https://cloud.google.com/compute/docs/load-balancing/health-checks). The Cassandra database is simply a set of instances, as the Cassandra client library (used by the Application Server) does client-side load balancing and transparent failover, thus does not need a cloud load balancer."

**Comment by sparkprime** [comment]
This is not intended to be a beginner or any other kind of tutorial but to demonstrate how Jsonnet can be used in more realistic situations where there is a lot of stuff going on.  So the complexity is not avoidable.

I wonder how did you come to think that this was intended as a beginner tutorial?  We have a tutorial linked on the website that is much simpler than the fractal case study.  This one is called a "case study" and is filed under "articles".
